
# =============================================================================
# SECTION 49: FIRST-TIME ADOPTION OF IND AS
# =============================================================================

FIRST_TIME_ADOPTION_IND_AS = {
    'transition_framework': {
        'key_dates': [
            'date_of_transition_to_ind_as',
            'transition_date',
            'beginning_of_earliest_comparative_period',
            'first_ind_as_reporting_period',
            'first_ind_as_financial_statements',
            'opening_ind_as_balance_sheet',
            'comparative_period',
            'previous_gaap',
            'indian_gaap',
            'igaap',
        ],
        'first_time_adopter': [
            'first_time_adopter',
            'first_ind_as_financial_statements',
            'explicit_and_unreserved_statement_of_compliance',
            'compliance_with_ind_as',
        ],
    },
    'opening_balance_sheet': {
        'recognition_and_derecognition': [
            'recognize_all_assets_and_liabilities_required_by_ind_as',
            'derecognize_assets_and_liabilities_not_permitted',
            'assets_not_qualifying_under_ind_as',
            'liabilities_not_qualifying_under_ind_as',
            'provisions_not_meeting_ind_as_criteria',
            'deferred_costs_not_qualifying',
            'intangibles_not_meeting_criteria',
        ],
        'reclassification': [
            'reclassify_items',
            'reclassification_as_per_ind_as',
            'compound_financial_instruments',
            'embedded_derivatives',
            'investment_classification',
            'lease_classification',
        ],
        'measurement': [
            'measure_all_assets_and_liabilities',
            'measurement_as_per_ind_as',
            'fair_value_measurement',
            'amortized_cost_measurement',
            'deemed_cost',
        ],
    },
    'mandatory_exceptions': {
        'estimates': [
            'estimates_consistent_with_previous_gaap',
            'no_hindsight',
            'estimates_at_transition_date',
            'estimates_at_end_of_comparative_period',
            'unless_objective_evidence_of_error',
        ],
        'derecognition_of_financial_assets_and_liabilities': [
            'derecognition_requirements',
            'applied_prospectively',
            'transactions_before_transition_date',
            'financial_assets_derecognized_under_previous_gaap',
        ],
        'hedge_accounting': [
            'hedge_accounting_applied_prospectively',
            'hedging_relationships_qualifying_under_ind_as',
            'hedging_documentation',
            'hedge_effectiveness',
            'discontinuation_of_hedge_accounting',
        ],
        'classification_and_measurement_of_financial_assets': [
            'assessment_based_on_facts_at_transition',
            'business_model_assessment',
            'sppi_assessment',
        ],
        'impairment_of_financial_assets': [
            'reasonable_and_supportable_information',
            'undue_cost_or_effort',
            'credit_risk_at_initial_recognition',
            'low_credit_risk_simplification',
        ],
        'embedded_derivatives': [
            'assessment_at_date_entity_first_became_party',
            'conditions_at_date_of_contract',
        ],
        'government_loans': [
            'government_loans_at_below_market_rate',
            'applied_prospectively',
            'loans_existing_at_transition',
        ],
        'non_controlling_interests': [
            'requirements_for_nci',
            'applied_prospectively',
            'total_comprehensive_income_attribution',
            'changes_in_ownership_without_loss_of_control',
        ],
    },
    'optional_exemptions': {
        'business_combinations': [
            'business_combinations_exemption',
            'not_restate_past_business_combinations',
            'business_combinations_before_transition_date',
            'same_classification',
            'carrying_amount_as_deemed_cost',
            'goodwill_carrying_amount',
            'derecognized_intangibles',
            'impairment_test_at_transition',
        ],
        'deemed_cost': {
            'property_plant_equipment': [
                'fair_value_as_deemed_cost',
                'previous_gaap_revaluation_as_deemed_cost',
                'carrying_amount_under_previous_gaap',
                'election_for_individual_assets',
            ],
            'intangible_assets': [
                'fair_value_as_deemed_cost_for_intangibles',
                'previous_gaap_revaluation',
                'active_market_requirement',
            ],
            'investment_property': [
                'fair_value_as_deemed_cost_for_investment_property',
                'previous_gaap_revaluation',
                'cost_model_or_fair_value_model',
            ],
            'right_of_use_assets': [
                'deemed_cost_for_rou_assets',
                'measurement_at_transition',
            ],
        },
        'leases': [
            'lease_exemption',
            'assessment_at_transition_date',
            'previous_gaap_assessment',
            'operating_leases_transitional_provisions',
            'finance_leases_transitional_provisions',
        ],
        'cumulative_translation_differences': [
            'cumulative_translation_differences_exemption',
            'deemed_zero_at_transition',
            'foreign_currency_translation_reserve',
            'reset_fctr_to_zero',
        ],
        'investments_in_subsidiaries_associates_jv': [
            'deemed_cost_for_investments',
            'cost_under_previous_gaap',
            'fair_value_as_deemed_cost',
            'separate_financial_statements',
        ],
        'compound_financial_instruments': [
            'compound_instruments_exemption',
            'no_separation_if_liability_settled',
            'equity_component_determination',
        ],
        'designation_of_financial_instruments': [
            'designation_at_transition_date',
            'fvtpl_designation',
            'fvoci_designation_for_equity',
            'designation_of_hedging_relationships',
        ],
        'fair_value_measurement': [
            'fair_value_measurement_exemption',
            'transactions_measured_at_fair_value',
            'prospective_application',
        ],
        'service_concession_arrangements': [
            'service_concession_arrangements_exemption',
            'transitional_provisions',
            'carrying_amounts_under_previous_gaap',
        ],
        'borrowing_costs': [
            'borrowing_costs_exemption',
            'capitalize_from_transition_date',
            'prospective_capitalization',
            'qualifying_assets_at_transition',
        ],
        'share_based_payment_transactions': [
            'share_based_payment_exemption',
            'equity_instruments_granted_before_transition',
            'equity_instruments_vested_before_transition',
            'liabilities_from_cash_settled_arrangements',
        ],
        'insurance_contracts': [
            'insurance_contracts_exemption',
            'transitional_provisions',
        ],
        'decommissioning_liabilities': [
            'decommissioning_liabilities_exemption',
            'changes_in_liabilities',
            'included_in_cost_of_asset',
        ],
        'joint_ventures': [
            'transition_from_proportionate_consolidation',
            'joint_ventures_to_equity_method',
            'investment_at_transition',
        ],
        'stripping_costs': [
            'stripping_costs_exemption',
            'mining_activities',
            'surface_mining',
            'production_stripping_costs',
        ],
    },
    'reconciliations': {
        'equity_reconciliation': [
            'reconciliation_of_equity',
            'equity_under_previous_gaap',
            'adjustments_to_ind_as',
            'equity_under_ind_as',
            'reconciliation_at_transition_date',
            'reconciliation_at_end_of_last_previous_gaap_period',
        ],
        'total_comprehensive_income_reconciliation': [
            'reconciliation_of_total_comprehensive_income',
            'profit_or_loss_under_previous_gaap',
            'adjustments_to_ind_as',
            'profit_or_loss_under_ind_as',
            'other_comprehensive_income_adjustments',
            'total_comprehensive_income_under_ind_as',
        ],
        'cash_flow_statement': [
            'material_adjustments_to_cash_flow_statement',
            'cash_flows_from_operating_activities_adjustments',
            'cash_flows_from_investing_activities_adjustments',
            'cash_flows_from_financing_activities_adjustments',
        ],
        'explanation_of_adjustments': [
            'explanation_of_material_adjustments',
            'nature_of_adjustment',
            'impact_on_financial_statements',
        ],
    },
    'common_ind_as_adjustments': {
        'revenue': [
            'revenue_recognition_differences',
            'percentage_of_completion_adjustments',
            'multiple_element_arrangements',
            'principal_vs_agent',
            'variable_consideration',
            'significant_financing_component',
        ],
        'financial_instruments': [
            'financial_instruments_adjustments',
            'classification_differences',
            'fair_value_measurement',
            'amortized_cost_measurement',
            'expected_credit_loss',
            'hedge_accounting_adjustments',
            'embedded_derivatives_separation',
            'equity_vs_liability_classification',
        ],
        'leases': [
            'lease_adjustments',
            'right_of_use_assets_recognition',
            'lease_liabilities_recognition',
            'operating_lease_adjustments',
            'finance_lease_adjustments',
            'sale_and_leaseback_adjustments',
        ],
        'employee_benefits': [
            'employee_benefits_adjustments',
            'defined_benefit_plans_remeasurement',
            'actuarial_gains_losses_in_oci',
            'past_service_cost_recognition',
        ],
        'share_based_payments': [
            'share_based_payment_adjustments',
            'fair_value_of_options',
            'expense_recognition',
            'graded_vesting_adjustment',
        ],
        'business_combinations': [
            'business_combination_adjustments',
            'transaction_costs',
            'contingent_consideration',
            'goodwill_measurement',
        ],
        'fair_value': [
            'fair_value_adjustments',
            'investment_property_at_fair_value',
            'biological_assets_at_fair_value',
            'financial_instruments_at_fair_value',
        ],
        'consolidation': [
            'consolidation_adjustments',
            'control_assessment',
            'structured_entities',
            'nci_measurement',
        ],
        'foreign_currency': [
            'foreign_currency_adjustments',
            'functional_currency_determination',
            'translation_reserve_adjustments',
        ],
        'income_taxes': [
            'deferred_tax_adjustments',
            'tax_effect_of_ind_as_adjustments',
            'temporary_differences',
            'uncertain_tax_positions',
        ],
    },
    'disclosures': {
        'first_time_adoption_disclosures': [
            'explanation_of_transition',
            'reconciliations',
            'exemptions_used',
            'exceptions_applied',
            'deemed_cost_elections',
            'fair_value_measurements_used',
            'significant_judgments',
            'estimates_in_applying_ind_as',
        ],
    },
}

# =============================================================================
# SECTION 50: CSR EXPENDITURE
# =============================================================================

CSR_EXPENDITURE = {
    'csr_applicability': {
        'applicability_criteria': [
            'net_worth_of_rupees_500_crore_or_more',
            'turnover_of_rupees_1000_crore_or_more',
            'net_profit_of_rupees_5_crore_or_more',
            'preceding_financial_year',
            'applicability_to_companies',
            'applicability_to_holding_companies',
            'applicability_to_subsidiary_companies',
            'applicability_to_foreign_companies',
        ],
        'csr_committee': [
            'csr_committee_constitution',
            'csr_committee_composition',
            'three_or_more_directors',
            'at_least_one_independent_director',
            'csr_committee_responsibilities',
            'csr_policy_formulation',
            'csr_policy_recommendation',
            'csr_expenditure_monitoring',
        ],
    },
    'csr_amount': {
        'calculation': [
            'csr_amount_calculation',
            'two_percent_of_average_net_profits',
            'average_net_profits_of_three_preceding_years',
            'net_profit_calculation_section_198',
            'minimum_csr_spending_requirement',
            'prescribed_csr_amount',
        ],
        'net_profit_computation': [
            'profit_before_tax',
            'less_dividend_income_from_indian_companies',
            'less_profit_on_sale_of_undertaking',
            'less_profit_from_overseas_branches',
            'adjustments_as_per_section_198',
            'net_profit_for_csr',
        ],
    },
    'eligible_csr_activities': {
        'schedule_vii_activities': [
            'eradicating_hunger_poverty_malnutrition',
            'promoting_education',
            'promoting_gender_equality',
            'empowering_women',
            'ensuring_environmental_sustainability',
            'protection_of_national_heritage',
            'measures_for_benefit_of_armed_forces_veterans',
            'training_to_promote_sports',
            'contribution_to_prime_ministers_relief_fund',
            'contribution_to_central_government_funds',
            'rural_development_projects',
            'slum_area_development',
            'disaster_management',
            'covid_19_related_activities',
            'healthcare_including_preventive_healthcare',
            'sanitation_and_safe_drinking_water',
            'livelihood_enhancement_projects',
            'vocational_skills_development',
            'senior_citizens_and_differently_abled',
            'orphans_and_widows',
            'technology_incubators',
            'contributions_to_technology_incubators',
        ],
        'excluded_activities': [
            'activities_for_benefit_of_employees',
            'activities_for_benefit_of_their_families',
            'one_off_events',
            'sponsorships_not_qualifying',
            'contributions_to_political_parties',
            'activities_outside_india',
        ],
    },
    'csr_implementation': {
        'modes_of_implementation': [
            'direct_implementation_by_company',
            'through_section_8_company',
            'through_registered_trust',
            'through_registered_society',
            'implementing_agency',
            'csr_registration_number',
            'form_csr_1',
            'collaboration_with_other_companies',
            'ongoing_projects',
            'multi_year_projects',
        ],
        'geographical_preference': [
            'local_area_preference',
            'areas_around_company_operations',
            'other_areas_as_decided_by_board',
        ],
    },
    'csr_expenditure_treatment': {
        'accounting_treatment': [
            'csr_expenditure_as_expense',
            'charge_to_statement_of_profit_and_loss',
            'not_a_provision',
            'actual_expenditure_recognized',
            'no_provision_for_unspent_amount',
        ],
        'unspent_csr_amount': {
            'ongoing_projects': [
                'unspent_csr_amount_ongoing_projects',
                'transfer_to_unspent_csr_account',
                'separate_bank_account',
                'within_30_days_from_end_of_financial_year',
                'spend_within_three_financial_years',
                'transfer_to_schedule_vii_fund_if_not_spent',
            ],
            'other_than_ongoing_projects': [
                'unspent_csr_amount_other_projects',
                'transfer_to_schedule_vii_fund',
                'prime_ministers_relief_fund',
                'other_notified_funds',
                'within_six_months_from_end_of_financial_year',
            ],
        },
        'excess_csr_expenditure': [
            'excess_csr_expenditure',
            'set_off_against_future_requirements',
            'set_off_in_succeeding_three_financial_years',
            'subject_to_conditions',
        ],
        'administrative_overheads': [
            'administrative_overheads',
            'capped_at_5_percent',
            'five_percent_of_total_csr_expenditure',
        ],
        'impact_assessment': [
            'impact_assessment_requirement',
            'projects_of_rupees_1_crore_or_more',
            'independent_agency',
            'impact_assessment_report',
            'impact_assessment_cost',
            'capped_at_5_percent_or_50_lakhs',
        ],
    },
    'csr_disclosures': {
        'board_report_disclosures': [
            'composition_of_csr_committee',
            'csr_policy',
            'web_link_to_csr_policy',
            'average_net_profit',
            'prescribed_csr_expenditure',
            'details_of_csr_spent',
            'amount_spent_on_ongoing_projects',
            'amount_spent_on_other_than_ongoing_projects',
            'amount_unspent',
            'manner_of_transfer_of_unspent_amount',
            'nature_of_csr_activities',
            'details_of_implementing_agency',
            'reasons_for_not_spending',
            'impact_assessment_details',
        ],
        'financial_statement_disclosures': [
            'csr_expenditure_during_year',
            'shortfall_in_csr_expenditure',
            'total_spending_in_previous_years',
            'details_of_ongoing_projects',
            'details_of_assets_created',
            'provision_for_csr_liability',
            'csr_liability_outstanding',
            'unspent_csr_account_balance',
            'set_off_amount_available',
        ],
        'annual_report_on_csr': [
            'format_annexed_to_rules',
            'csr_annual_report',
            'projects_undertaken',
            'amount_spent_on_each_project',
            'location_of_projects',
            'beneficiaries',
        ],
    },
    'csr_related_provisions': [
        'provision_for_csr_unspent_amount',
        'liability_for_csr_obligation',
        'unspent_csr_account_liability',
        'schedule_vii_fund_transfer_liability',
        'asset_created_under_csr',
        'csr_assets_transfer',
        'csr_assets_held_in_trust',
    ],
}

# =============================================================================
# SECTION 51: AUDIT REPORT TERMS
# =============================================================================

AUDIT_REPORT_TERMS = {
    'audit_opinion': {
        'types_of_opinion': [
            'unmodified_opinion',
            'unqualified_opinion',
            'clean_opinion',
            'modified_opinion',
            'qualified_opinion',
            'adverse_opinion',
            'disclaimer_of_opinion',
        ],
        'basis_for_opinion': [
            'basis_for_opinion',
            'audit_conducted_in_accordance_with_standards',
            'standards_on_auditing',
            'sa',
            'independence',
            'ethical_requirements',
            'code_of_ethics',
            'sufficient_appropriate_audit_evidence',
        ],
    },
    'key_audit_matters': {
        'kam_definition': [
            'key_audit_matters',
            'kam',
            'matters_of_most_significance',
            'matters_communicated_to_those_charged_with_governance',
            'professional_judgment',
            'significant_auditor_attention',
        ],
        'kam_areas': [
            'revenue_recognition',
            'impairment_of_goodwill',
            'impairment_of_assets',
            'expected_credit_loss',
            'valuation_of_investments',
            'valuation_of_inventory',
            'valuation_of_financial_instruments',
            'fair_value_measurements',
            'provisions_and_contingencies',
            'related_party_transactions',
            'business_combinations',
            'going_concern',
            'tax_matters',
            'litigation_and_claims',
            'fraud_risk',
            'management_override_of_controls',
        ],
        'kam_response': [
            'audit_response_to_kam',
            'audit_procedures_performed',
            'key_observations',
            'conclusions',
        ],
    },
    'emphasis_of_matter': {
        'definition': [
            'emphasis_of_matter_paragraph',
            'eom',
            'matter_appropriately_presented_or_disclosed',
            'fundamental_importance_to_users_understanding',
            'does_not_modify_opinion',
        ],
        'common_matters': [
            'uncertainty_relating_to_future_outcome_of_litigation',
            'early_application_of_accounting_standard',
            'major_catastrophe',
            'significant_related_party_transactions',
            'subsequent_events',
        ],
    },
    'other_matter': {
        'definition': [
            'other_matter_paragraph',
            'matter_not_presented_or_disclosed',
            'relevant_to_users_understanding',
            'does_not_modify_opinion',
        ],
        'common_matters': [
            'prior_period_audited_by_predecessor_auditor',
            'comparative_information',
            'other_information_in_annual_report',
            'restriction_on_distribution_of_auditors_report',
        ],
    },
    'going_concern': {
        'auditor_responsibilities': [
            'going_concern_assessment',
            'appropriateness_of_going_concern_basis',
            'material_uncertainty',
            'adequate_disclosure',
        ],
        'reporting': [
            'going_concern_section_in_report',
            'material_uncertainty_related_to_going_concern',
            'reference_to_note_in_financial_statements',
            'no_modification_if_adequate_disclosure',
            'qualified_or_adverse_if_inadequate_disclosure',
        ],
    },
    'other_information': {
        'definition': [
            'other_information',
            'annual_report',
            'management_discussion_and_analysis',
            'directors_report',
            'corporate_governance_report',
            'chairman_statement',
            'operating_and_financial_review',
        ],
        'auditor_responsibilities': [
            'reading_other_information',
            'considering_consistency_with_financial_statements',
            'considering_consistency_with_audit_knowledge',
            'material_misstatement_of_other_information',
            'reporting_uncorrected_material_misstatement',
        ],
    },
    'management_and_governance_responsibilities': {
        'management_responsibilities': [
            'preparation_of_financial_statements',
            'fair_presentation',
            'true_and_fair_view',
            'compliance_with_ind_as',
            'compliance_with_companies_act',
            'internal_controls',
            'prevention_and_detection_of_fraud',
            'going_concern_assessment',
            'selection_of_accounting_policies',
            'accounting_estimates',
        ],
        'governance_responsibilities': [
            'oversight_of_financial_reporting_process',
            'those_charged_with_governance',
            'audit_committee',
            'board_of_directors',
        ],
    },
    'auditor_responsibilities': {
        'general_responsibilities': [
            'obtaining_reasonable_assurance',
            'expressing_opinion',
            'professional_skepticism',
            'professional_judgment',
            'identifying_risks_of_material_misstatement',
            'designing_audit_procedures',
            'obtaining_sufficient_appropriate_evidence',
            'evaluating_appropriateness_of_accounting_policies',
            'evaluating_reasonableness_of_estimates',
            'evaluating_overall_presentation',
        ],
        'fraud_responsibilities': [
            'identifying_risks_of_material_misstatement_due_to_fraud',
            'fraud_risk_assessment',
            'management_override_of_controls',
            'revenue_recognition_fraud_risk',
        ],
        'internal_control_responsibilities': [
            'understanding_internal_control',
            'relevant_to_audit',
            'not_expressing_opinion_on_effectiveness',
        ],
    },
    'companies_act_reporting': {
        'section_143_matters': [
            'section_143_2_matters',
            'books_of_account_maintained',
            'branch_audit_reports',
            'balance_sheet_and_profit_loss_in_agreement_with_books',
            'compliance_with_accounting_standards',
            'compliance_with_ind_as',
            'section_143_3_matters',
            'disqualification_of_directors',
            'section_164_2_disqualification',
            'adequate_internal_financial_controls',
            'internal_financial_controls_operating_effectively',
            'reporting_under_section_197',
            'directors_remuneration',
            'pending_litigations_and_impact',
            'provision_for_material_foreseeable_losses',
            'transfer_to_iepf',
            'compliance_with_nfra_orders',
        ],
        'caro_reporting': [
            'caro_2020',
            'companies_auditors_report_order',
            'property_plant_equipment_records',
            'physical_verification_of_ppe',
            'title_deeds_of_immovable_properties',
            'physical_verification_of_inventory',
            'loans_to_related_parties',
            'compliance_with_section_185_186',
            'deposits_from_public',
            'cost_records_maintenance',
            'statutory_dues',
            'undisclosed_income',
            'default_in_repayment_of_loans',
            'utilization_of_funds_raised',
            'fraud_by_or_on_company',
            'related_party_transactions',
            'nidhi_company_requirements',
            'non_cash_transactions_with_directors',
            'registration_under_rbi_act',
            'core_investment_company',
            'cash_losses',
            'resignation_of_statutory_auditor',
            'material_uncertainty_on_going_concern',
            'csr_spending',
            'transfer_of_unspent_csr_amount',
            'qualifications_in_subsidiary_audits',
            'one_person_company_compliance',
        ],
    },
    'internal_financial_controls': {
        'ifc_opinion': [
            'internal_financial_controls_over_financial_reporting',
            'ifcofr',
            'reasonable_assurance_on_ifc',
            'material_weakness',
            'significant_deficiency',
            'deficiency_in_design',
            'deficiency_in_operation',
        ],
        'ifc_reporting': [
            'annexure_on_ifc',
            'separate_report_on_ifc',
            'qualified_opinion_on_ifc',
            'adverse_opinion_on_ifc',
            'disclaimer_of_opinion_on_ifc',
        ],
    },
    'consolidated_audit_report': {
        'group_audit': [
            'group_audit',
            'principal_auditor',
            'component_auditor',
            'other_auditor',
            'unaudited_components',
            'reliance_on_other_auditors',
            'reference_to_other_auditors',
            'responsibility_for_group_opinion',
        ],
        'component_disclosures': [
            'component_assets',
            'component_revenues',
            'component_net_assets',
            'unaudited_financial_information',
            'magnitude_of_components_audited_by_others',
        ],
    },
}

# =============================================================================
# SECTION 52: DIRECTOR'S REPORT TERMS
# =============================================================================

DIRECTORS_REPORT_TERMS = {
    'financial_performance': {
        'summary_of_operations': [
            'state_of_company_affairs',
            'financial_summary',
            'operational_highlights',
            'revenue_from_operations',
            'profit_before_tax',
            'profit_after_tax',
            'earnings_per_share',
            'return_on_net_worth',
            'return_on_capital_employed',
            'comparison_with_previous_year',
            'percentage_change',
            'year_on_year_growth',
        ],
        'segment_performance': [
            'segment_wise_performance',
            'business_segment_review',
            'geographical_segment_review',
            'segment_revenue',
            'segment_profit',
        ],
    },
    'dividend': {
        'dividend_declaration': [
            'dividend',
            'final_dividend',
            'interim_dividend',
            'special_dividend',
            'dividend_per_share',
            'dividend_payout_ratio',
            'dividend_distribution_policy',
            'dividend_recommendation',
            'dividend_proposed',
            'dividend_paid_during_year',
            'total_dividend',
            'dividend_percentage',
            'record_date_for_dividend',
            'unclaimed_dividend',
            'transfer_to_iepf',
        ],
        'dividend_policy': [
            'dividend_distribution_policy',
            'regulation_43a_sebi_lodr',
            'factors_considered_for_dividend',
            'circumstances_for_dividend_non_declaration',
            'internal_and_external_factors',
            'use_of_retained_earnings',
        ],
    },
    'reserves_and_surplus': {
        'transfers_to_reserves': [
            'transfer_to_reserves',
            'transfer_to_general_reserve',
            'transfer_to_capital_redemption_reserve',
            'transfer_to_debenture_redemption_reserve',
            'transfer_to_special_reserve',
            'amount_proposed_to_carry_forward',
            'retained_earnings',
        ],
    },
    'share_capital': {
        'capital_structure': [
            'share_capital',
            'authorized_share_capital',
            'issued_share_capital',
            'subscribed_share_capital',
            'paid_up_share_capital',
            'changes_in_share_capital',
            'increase_in_authorized_capital',
            'issue_of_shares',
            'allotment_of_shares',
            'buyback_of_shares',
            'reduction_of_share_capital',
            'equity_shares_with_differential_rights',
            'sweat_equity_shares',
        ],
        'issue_of_securities': [
            'public_issue',
            'rights_issue',
            'preferential_issue',
            'private_placement',
            'qualified_institutional_placement',
            'issue_of_debentures',
            'issue_of_bonds',
            'convertible_securities',
            'warrants',
        ],
    },
    'deposits': {
        'public_deposits': [
            'public_deposits',
            'deposits_from_members',
            'deposits_under_chapter_v',
            'deposits_accepted',
            'deposits_outstanding',
            'deposits_due_for_repayment',
            'deposits_claimed_but_not_paid',
            'unclaimed_deposits',
            'details_of_deposit_defaults',
            'interest_on_deposits',
            'compliance_with_deposit_rules',
        ],
    },
    'directors_and_kmp': {
        'board_composition': [
            'composition_of_board',
            'board_of_directors',
            'executive_directors',
            'non_executive_directors',
            'independent_directors',
            'woman_director',
            'nominee_directors',
            'managing_director',
            'whole_time_directors',
            'chairman',
            'composition_requirements',
        ],
        'changes_in_directors': [
            'changes_in_directors',
            'appointment_of_directors',
            'resignation_of_directors',
            'retirement_by_rotation',
            're_appointment_of_directors',
            'cessation_of_directors',
            'disqualification_of_directors',
            'brief_profile_of_directors',
        ],
        'key_managerial_personnel': [
            'key_managerial_personnel',
            'kmp',
            'chief_executive_officer',
            'chief_financial_officer',
            'company_secretary',
            'manager',
            'changes_in_kmp',
            'appointment_of_kmp',
            'resignation_of_kmp',
        ],
        'directors_responsibility_statement': [
            'directors_responsibility_statement',
            'section_134_5',
            'applicable_accounting_standards_followed',
            'accounting_policies_selected_and_applied_consistently',
            'judgments_and_estimates_reasonable_and_prudent',
            'proper_and_sufficient_care_for_maintenance_of_records',
            'financial_statements_prepared_on_going_concern_basis',
            'internal_financial_controls_in_place',
            'proper_systems_to_ensure_compliance',
            'prevention_and_detection_of_frauds',
        ],
        'declaration_by_independent_directors': [
            'declaration_of_independence',
            'section_149_6',
            'schedule_iv',
            'independence_criteria',
            'pecuniary_relationship',
            'material_relationship',
            'registration_with_databank',
            'proficiency_test',
        ],
        'board_meetings': [
            'number_of_board_meetings',
            'board_meetings_held',
            'attendance_at_board_meetings',
            'gap_between_meetings',
            'quorum_requirements',
        ],
    },
    'committees': {
        'audit_committee': [
            'audit_committee',
            'composition_of_audit_committee',
            'terms_of_reference',
            'audit_committee_meetings',
            'attendance_at_audit_committee_meetings',
            'audit_committee_recommendations',
        ],
        'nomination_and_remuneration_committee': [
            'nomination_and_remuneration_committee',
            'nrc',
            'composition_of_nrc',
            'terms_of_reference',
            'nrc_meetings',
            'remuneration_policy',
            'policy_on_directors_appointment',
            'criteria_for_board_evaluation',
        ],
        'stakeholders_relationship_committee': [
            'stakeholders_relationship_committee',
            'src',
            'composition_of_src',
            'investor_grievance_redressal',
            'complaints_received',
            'complaints_resolved',
            'complaints_pending',
        ],
        'csr_committee': [
            'csr_committee',
            'composition_of_csr_committee',
            'csr_policy',
            'csr_initiatives',
            'annual_report_on_csr',
        ],
        'risk_management_committee': [
            'risk_management_committee',
            'composition_of_risk_management_committee',
            'risk_management_policy',
            'risk_identification',
            'risk_mitigation',
        ],
        'other_committees': [
            'executive_committee',
            'finance_committee',
            'investment_committee',
            'allotment_committee',
            'borrowing_committee',
        ],
    },
    'policies': {
        'mandatory_policies': [
            'vigil_mechanism_policy',
            'whistle_blower_policy',
            'related_party_transaction_policy',
            'remuneration_policy',
            'risk_management_policy',
            'csr_policy',
            'dividend_distribution_policy',
            'policy_on_board_diversity',
            'policy_on_determination_of_materiality',
            'archival_policy',
            'code_of_conduct',
            'code_for_prevention_of_insider_trading',
            'policy_for_preservation_of_documents',
        ],
        'policy_disclosure': [
            'web_link_to_policies',
            'salient_features_of_policies',
            'key_provisions_of_policies',
        ],
    },
    'remuneration': {
        'directors_remuneration': [
            'remuneration_of_directors',
            'remuneration_of_managing_director',
            'remuneration_of_whole_time_directors',
            'sitting_fees',
            'commission_to_directors',
            'details_of_remuneration',
            'elements_of_remuneration',
            'ratio_of_remuneration',
            'median_remuneration_of_employees',
            'percentage_increase_in_remuneration',
            'affirmation_of_remuneration_policy',
        ],
        'employee_remuneration': [
            'particulars_of_employees',
            'section_197_12',
            'rule_5_of_companies_rules',
            'employees_drawing_remuneration_exceeding_limits',
            'top_ten_employees',
            'employees_throughout_the_year',
            'employees_for_part_of_year',
        ],
    },
    'related_party_transactions': {
        'rpt_disclosures': [
            'related_party_transactions',
            'material_related_party_transactions',
            'form_aoc_2',
            'contracts_with_related_parties',
            'ordinary_course_of_business',
            'arms_length_basis',
            'omnibus_approval',
            'prior_approval_of_audit_committee',
            'shareholders_approval',
            'justification_for_transactions',
        ],
    },
    'loans_and_investments': {
        'section_186_disclosures': [
            'particulars_of_loans',
            'particulars_of_guarantees',
            'particulars_of_investments',
            'particulars_of_securities',
            'purpose_of_loan_or_guarantee',
            'utilization_by_recipient',
            'compliance_with_section_186',
        ],
    },
    'statutory_disclosures': {
        'conservation_of_energy': [
            'conservation_of_energy',
            'steps_taken_for_conservation',
            'steps_taken_for_utilizing_alternate_sources',
            'capital_investment_on_energy_conservation',
            'impact_of_measures',
        ],
        'technology_absorption': [
            'technology_absorption',
            'efforts_for_technology_absorption',
            'benefits_derived',
            'imported_technology',
            'expenditure_on_r_and_d',
            'r_and_d_as_percentage_of_turnover',
        ],
        'foreign_exchange': [
            'foreign_exchange_earnings',
            'foreign_exchange_outgo',
            'export_initiatives',
            'total_exports',
            'total_imports',
        ],
        'annual_return': [
            'annual_return',
            'extract_of_annual_return',
            'form_mgt_9',
            'web_link_to_annual_return',
        ],
        'secretarial_audit': [
            'secretarial_audit_report',
            'form_mr_3',
            'secretarial_auditor',
            'secretarial_standards_compliance',
            'observations_in_secretarial_audit',
            'management_response',
        ],
        'cost_audit': [
            'cost_audit',
            'cost_auditor_appointment',
            'cost_audit_report',
            'cost_records_maintenance',
        ],
        'internal_audit': [
            'internal_audit',
            'internal_auditor',
            'internal_audit_report',
            'adequacy_of_internal_controls',
        ],
        'fraud_reporting': [
            'fraud_reporting',
            'section_143_12',
            'frauds_reported_by_auditors',
            'nature_of_fraud',
            'amount_involved',
            'remedial_action_taken',
        ],
        'significant_orders': [
            'significant_and_material_orders',
            'orders_passed_by_regulators',
            'orders_passed_by_courts',
            'orders_passed_by_tribunals',
            'impact_on_going_concern',
            'impact_on_operations',
        ],
        'material_changes': [
            'material_changes_and_commitments',
            'changes_between_financial_year_end_and_date_of_report',
            'material_events_affecting_financial_position',
        ],
        'internal_financial_controls': [
            'internal_financial_controls',
            'adequacy_of_internal_financial_controls',
            'operating_effectiveness',
            'material_weaknesses',
            'remediation_plans',
        ],
        'sexual_harassment': [
            'sexual_harassment_policy',
            'internal_complaints_committee',
            'complaints_received',
            'complaints_disposed',
            'complaints_pending',
            'posh_compliance',
        ],
        'insolvency_and_bankruptcy': [
            'application_made_under_ibc',
            'insolvency_proceedings',
            'status_of_proceedings',
            'one_time_settlement',
        ],
        'difference_in_valuation': [
            'difference_in_valuation',
            'valuation_for_one_time_settlement',
            'valuation_while_taking_loan',
            'details_of_difference',
        ],
    },
    'corporate_governance': {
        'corporate_governance_report': [
            'corporate_governance_report',
            'compliance_with_sebi_lodr',
            'compliance_certificate',
            'declaration_on_code_of_conduct',
            'ceo_cfo_certification',
        ],
        'management_discussion_and_analysis': [
            'management_discussion_and_analysis',
            'mda',
            'industry_structure_and_developments',
            'opportunities_and_threats',
            'segment_wise_performance',
            'outlook',
            'risks_and_concerns',
            'internal_control_systems',
            'human_resources',
            'key_financial_ratios',
            'change_in_return_on_net_worth',
        ],
        'business_responsibility_report': [
            'business_responsibility_report',
            'brr',
            'business_responsibility_and_sustainability_report',
            'brsr',
            'principle_wise_performance',
            'national_voluntary_guidelines',
            'esg_disclosures',
            'sustainability_initiatives',
        ],
    },
    'acknowledgements': [
        'acknowledgement',
        'gratitude_to_stakeholders',
        'thanks_to_shareholders',
        'thanks_to_employees',
        'thanks_to_customers',
        'thanks_to_suppliers',
        'thanks_to_bankers',
        'thanks_to_government_authorities',
        'thanks_to_auditors',
        'appreciation_of_support',
    ],
}
