
# =============================================================================
# SECTION 31: SEGMENT REPORTING
# =============================================================================

SEGMENT_REPORTING = {
    'segment_identification': {
        'basis_of_segmentation': [
            'basis_of_segmentation',
            'operating_segments',
            'reportable_segments',
            'management_approach',
            'chief_operating_decision_maker',
            'codm',
            'segment_identification_criteria',
            'products_and_services_basis',
            'geographical_basis',
            'customer_type_basis',
            'legal_entity_basis',
            'aggregation_criteria',
            'quantitative_thresholds',
            'revenue_test',
            'profit_or_loss_test',
            'assets_test',
        ],
        'segment_types': [
            'business_segments',
            'geographical_segments',
            'primary_segment',
            'secondary_segment',
            'operating_segment',
            'reportable_segment',
            'all_other_segments',
            'unallocated_segment',
            'corporate_segment',
            'eliminations_segment',
        ],
    },
    'segment_revenue': {
        'external_revenue': [
            'segment_revenue',
            'revenue_from_external_customers',
            'external_revenue_by_segment',
            'sales_to_external_customers',
            'revenue_from_contracts_with_customers_by_segment',
        ],
        'inter_segment_revenue': [
            'inter_segment_revenue',
            'inter_segment_sales',
            'revenue_from_transactions_with_other_segments',
            'transfer_pricing_revenue',
            'internal_revenue',
        ],
        'total_segment_revenue': [
            'total_segment_revenue',
            'gross_segment_revenue',
            'segment_revenue_before_eliminations',
        ],
        'revenue_reconciliation': [
            'reconciliation_of_segment_revenue_to_total_revenue',
            'elimination_of_inter_segment_revenue',
            'revenue_from_external_customers_total',
            'unallocated_revenue',
            'corporate_revenue',
        ],
    },
    'segment_results': {
        'segment_profit_or_loss': [
            'segment_result',
            'segment_profit',
            'segment_loss',
            'segment_operating_profit',
            'segment_operating_loss',
            'segment_ebitda',
            'segment_ebit',
            'profit_before_interest_and_tax_by_segment',
            'contribution_margin_by_segment',
        ],
        'reconciliation_to_profit': [
            'reconciliation_of_segment_profit_to_profit_before_tax',
            'total_segment_result',
            'unallocated_corporate_expenses',
            'unallocated_income',
            'inter_segment_eliminations',
            'finance_costs_unallocated',
            'finance_income_unallocated',
            'share_of_profit_of_associates',
            'exceptional_items',
            'profit_before_tax',
        ],
    },
    'segment_assets': {
        'segment_assets': [
            'segment_assets',
            'assets_by_segment',
            'operating_assets_by_segment',
            'total_assets_by_segment',
            'capital_employed_by_segment',
        ],
        'reconciliation_to_total_assets': [
            'reconciliation_of_segment_assets_to_total_assets',
            'total_segment_assets',
            'unallocated_assets',
            'corporate_assets',
            'deferred_tax_assets_unallocated',
            'current_tax_assets_unallocated',
            'investments_unallocated',
            'cash_and_cash_equivalents_unallocated',
            'inter_segment_eliminations_assets',
            'total_assets',
        ],
    },
    'segment_liabilities': {
        'segment_liabilities': [
            'segment_liabilities',
            'liabilities_by_segment',
            'operating_liabilities_by_segment',
            'total_liabilities_by_segment',
        ],
        'reconciliation_to_total_liabilities': [
            'reconciliation_of_segment_liabilities_to_total_liabilities',
            'total_segment_liabilities',
            'unallocated_liabilities',
            'corporate_liabilities',
            'borrowings_unallocated',
            'deferred_tax_liabilities_unallocated',
            'current_tax_liabilities_unallocated',
            'inter_segment_eliminations_liabilities',
            'total_liabilities',
        ],
    },
    'other_segment_information': {
        'capital_expenditure': [
            'capital_expenditure_by_segment',
            'additions_to_non_current_assets_by_segment',
            'additions_to_property_plant_equipment_by_segment',
            'additions_to_intangible_assets_by_segment',
            'additions_to_right_of_use_assets_by_segment',
            'additions_to_investment_property_by_segment',
            'segment_capital_expenditure',
        ],
        'depreciation_and_amortization': [
            'depreciation_by_segment',
            'amortization_by_segment',
            'depreciation_and_amortization_by_segment',
            'segment_depreciation_expense',
        ],
        'impairment': [
            'impairment_losses_by_segment',
            'impairment_of_assets_by_segment',
            'reversal_of_impairment_by_segment',
        ],
        'other_non_cash_items': [
            'non_cash_expenses_by_segment',
            'non_cash_income_by_segment',
            'provisions_by_segment',
            'share_based_payment_expense_by_segment',
        ],
    },
    'geographical_information': {
        'revenue_by_geography': [
            'revenue_from_external_customers_by_geography',
            'revenue_from_domestic_operations',
            'revenue_from_india',
            'revenue_from_overseas_operations',
            'revenue_from_exports',
            'revenue_by_country',
            'revenue_from_usa',
            'revenue_from_europe',
            'revenue_from_uk',
            'revenue_from_asia_pacific',
            'revenue_from_middle_east',
            'revenue_from_africa',
            'revenue_from_rest_of_world',
            'revenue_by_region',
        ],
        'assets_by_geography': [
            'non_current_assets_by_geography',
            'assets_located_in_india',
            'assets_located_outside_india',
            'assets_by_country',
            'property_plant_equipment_by_geography',
            'intangible_assets_by_geography',
            'goodwill_by_geography',
        ],
    },
    'major_customers': [
        'revenue_from_major_customers',
        'customers_contributing_more_than_10_percent',
        'concentration_of_revenue',
        'major_customer_disclosure',
        'revenue_from_single_external_customer',
        'segment_reporting_major_customer',
    ],
    'entity_wide_disclosures': {
        'products_and_services': [
            'revenue_from_each_product',
            'revenue_from_each_service',
            'revenue_by_product_line',
            'revenue_by_service_line',
            'revenue_from_each_group_of_similar_products',
        ],
        'geographical_areas': [
            'geographical_area_disclosure',
            'country_of_domicile',
            'foreign_countries',
            'individual_foreign_country_disclosure',
        ],
    },
}

# =============================================================================
# SECTION 32: EARNINGS PER SHARE
# =============================================================================

EARNINGS_PER_SHARE = {
    'basic_eps': {
        'profit_attributable': [
            'profit_attributable_to_equity_shareholders',
            'profit_attributable_to_ordinary_equity_holders',
            'net_profit_for_basic_eps',
            'profit_from_continuing_operations_for_basic_eps',
            'profit_from_discontinued_operations_for_basic_eps',
            'loss_attributable_to_equity_shareholders',
            'net_loss_for_basic_eps',
        ],
        'adjustments_to_profit': [
            'adjustments_to_profit_for_basic_eps',
            'preference_dividends',
            'dividends_on_non_participating_preference_shares',
            'redemption_premium_on_preference_shares',
            'other_similar_effects_of_preference_shares',
        ],
        'weighted_average_shares': [
            'weighted_average_number_of_equity_shares',
            'weighted_average_shares_for_basic_eps',
            'equity_shares_at_beginning_of_period',
            'equity_shares_issued_during_period',
            'equity_shares_bought_back_during_period',
            'bonus_shares_adjustment',
            'time_weighted_adjustment',
            'shares_outstanding_for_part_of_period',
        ],
        'basic_eps_calculation': [
            'basic_earnings_per_share',
            'basic_eps',
            'basic_eps_from_continuing_operations',
            'basic_eps_from_discontinued_operations',
            'basic_eps_from_total_operations',
        ],
    },
    'diluted_eps': {
        'diluted_profit': [
            'profit_for_diluted_eps',
            'net_profit_for_diluted_eps',
            'profit_from_continuing_operations_for_diluted_eps',
            'profit_from_discontinued_operations_for_diluted_eps',
            'loss_for_diluted_eps',
        ],
        'adjustments_to_profit_for_dilution': [
            'adjustments_to_profit_for_diluted_eps',
            'interest_on_convertible_instruments',
            'interest_on_convertible_debentures',
            'interest_on_convertible_bonds',
            'tax_effect_of_interest_adjustment',
            'dividends_on_convertible_preference_shares',
            'other_changes_in_income_or_expense',
        ],
        'dilutive_potential_shares': [
            'weighted_average_shares_for_diluted_eps',
            'dilutive_effect_of_stock_options',
            'dilutive_effect_of_esop',
            'dilutive_effect_of_convertible_debentures',
            'dilutive_effect_of_convertible_bonds',
            'dilutive_effect_of_convertible_preference_shares',
            'dilutive_effect_of_warrants',
            'dilutive_effect_of_rights_issue',
            'contingently_issuable_shares',
            'contracts_settled_in_shares',
            'written_put_options',
            'purchased_call_options',
        ],
        'anti_dilutive_instruments': [
            'anti_dilutive_instruments',
            'instruments_excluded_from_diluted_eps',
            'reason_for_exclusion',
            'out_of_money_options',
        ],
        'diluted_eps_calculation': [
            'diluted_earnings_per_share',
            'diluted_eps',
            'diluted_eps_from_continuing_operations',
            'diluted_eps_from_discontinued_operations',
            'diluted_eps_from_total_operations',
        ],
    },
    'eps_reconciliation': {
        'shares_reconciliation': [
            'reconciliation_of_weighted_average_shares',
            'shares_for_basic_eps',
            'effect_of_dilutive_options',
            'effect_of_dilutive_convertibles',
            'shares_for_diluted_eps',
        ],
        'profit_reconciliation': [
            'reconciliation_of_profit_for_eps',
            'profit_for_basic_eps',
            'adjustments_for_dilutive_instruments',
            'profit_for_diluted_eps',
        ],
    },
    'eps_disclosures': {
        'instruments_affecting_eps': [
            'instruments_that_could_dilute_eps_in_future',
            'instruments_not_included_in_diluted_eps',
            'potential_equity_shares_not_dilutive',
            'changes_in_instruments_after_reporting_period',
        ],
        'transactions_after_reporting_period': [
            'transactions_after_reporting_period_affecting_shares',
            'shares_issued_after_reporting_period',
            'shares_bought_back_after_reporting_period',
            'bonus_issue_after_reporting_period',
            'share_split_after_reporting_period',
            'reverse_share_split_after_reporting_period',
            'rights_issue_after_reporting_period',
        ],
        'face_value': [
            'face_value_per_share',
            'nominal_value_per_share',
            'par_value_per_share',
        ],
    },
    'adjusted_eps': [
        'adjusted_earnings_per_share',
        'adjusted_eps',
        'eps_before_exceptional_items',
        'eps_excluding_one_time_items',
        'normalized_eps',
        'underlying_eps',
        'headline_eps',
        'core_eps',
        'cash_eps',
    ],
}

# =============================================================================
# SECTION 33: FINANCIAL INSTRUMENTS - CLASSIFICATION
# =============================================================================

FINANCIAL_INSTRUMENTS_CLASSIFICATION = {
    'financial_assets_classification': {
        'amortised_cost': {
            'criteria': [
                'held_within_business_model_to_collect_contractual_cash_flows',
                'contractual_cash_flows_solely_payments_of_principal_and_interest',
                'sppi_test_passed',
                'hold_to_collect_business_model',
            ],
            'instruments': [
                'financial_assets_at_amortised_cost',
                'trade_receivables_at_amortised_cost',
                'loans_at_amortised_cost',
                'deposits_at_amortised_cost',
                'debt_instruments_at_amortised_cost',
                'bonds_at_amortised_cost',
                'debentures_at_amortised_cost',
                'government_securities_at_amortised_cost',
                'corporate_bonds_at_amortised_cost',
                'security_deposits_at_amortised_cost',
                'inter_corporate_deposits_at_amortised_cost',
                'cash_and_cash_equivalents',
                'bank_balances',
                'fixed_deposits',
                'interest_accrued',
                'other_financial_assets_at_amortised_cost',
            ],
        },
        'fair_value_through_oci': {
            'debt_instruments_fvoci': {
                'criteria': [
                    'held_within_business_model_to_collect_and_sell',
                    'contractual_cash_flows_solely_payments_of_principal_and_interest',
                    'hold_to_collect_and_sell_business_model',
                ],
                'instruments': [
                    'debt_instruments_at_fvoci',
                    'bonds_at_fvoci',
                    'debentures_at_fvoci',
                    'government_securities_at_fvoci',
                    'corporate_bonds_at_fvoci',
                    'treasury_bills_at_fvoci',
                ],
            },
            'equity_instruments_fvoci': {
                'criteria': [
                    'irrevocable_election_at_initial_recognition',
                    'not_held_for_trading',
                    'equity_instrument_as_per_ind_as_32',
                ],
                'instruments': [
                    'equity_instruments_designated_at_fvoci',
                    'strategic_investments_at_fvoci',
                    'quoted_equity_shares_at_fvoci',
                    'unquoted_equity_shares_at_fvoci',
                    'investment_in_equity_instruments_at_fvoci',
                ],
            },
        },
        'fair_value_through_profit_or_loss': {
            'mandatory_fvtpl': {
                'criteria': [
                    'held_for_trading',
                    'fails_sppi_test',
                    'managed_on_fair_value_basis',
                    'derivative_not_designated_as_hedge',
                ],
                'instruments': [
                    'financial_assets_at_fvtpl',
                    'investments_held_for_trading',
                    'equity_instruments_at_fvtpl',
                    'quoted_equity_shares_at_fvtpl',
                    'unquoted_equity_shares_at_fvtpl',
                    'mutual_fund_investments_at_fvtpl',
                    'debt_funds_at_fvtpl',
                    'equity_funds_at_fvtpl',
                    'hybrid_funds_at_fvtpl',
                    'alternative_investment_funds_at_fvtpl',
                    'venture_capital_funds_at_fvtpl',
                    'private_equity_investments_at_fvtpl',
                    'derivative_assets',
                    'forward_contracts_asset',
                    'options_asset',
                    'futures_asset',
                    'swap_assets',
                    'embedded_derivatives',
                    'contingent_consideration_receivable',
                ],
            },
            'designated_fvtpl': {
                'criteria': [
                    'designation_eliminates_accounting_mismatch',
                    'managed_on_fair_value_basis',
                    'hybrid_contract_with_embedded_derivative',
                ],
                'instruments': [
                    'financial_assets_designated_at_fvtpl',
                    'investments_designated_at_fvtpl',
                    'loans_designated_at_fvtpl',
                ],
            },
        },
    },
    'financial_liabilities_classification': {
        'amortised_cost': [
            'financial_liabilities_at_amortised_cost',
            'borrowings_at_amortised_cost',
            'term_loans_at_amortised_cost',
            'debentures_at_amortised_cost',
            'bonds_at_amortised_cost',
            'commercial_paper_at_amortised_cost',
            'trade_payables_at_amortised_cost',
            'lease_liabilities',
            'deposits_received',
            'security_deposits_received',
            'retention_money',
            'other_financial_liabilities_at_amortised_cost',
        ],
        'fair_value_through_profit_or_loss': {
            'mandatory_fvtpl': [
                'financial_liabilities_held_for_trading',
                'derivative_liabilities',
                'forward_contracts_liability',
                'options_liability',
                'futures_liability',
                'swap_liabilities',
                'contingent_consideration_payable',
            ],
            'designated_fvtpl': [
                'financial_liabilities_designated_at_fvtpl',
                'liabilities_designated_to_eliminate_accounting_mismatch',
                'liabilities_managed_on_fair_value_basis',
            ],
        },
    },
    'classification_by_category': {
        'financial_assets_summary': [
            'total_financial_assets_at_amortised_cost',
            'total_financial_assets_at_fvoci',
            'total_financial_assets_at_fvtpl',
            'total_financial_assets',
        ],
        'financial_liabilities_summary': [
            'total_financial_liabilities_at_amortised_cost',
            'total_financial_liabilities_at_fvtpl',
            'total_financial_liabilities',
        ],
    },
    'reclassification': {
        'reclassification_of_financial_assets': [
            'reclassification_from_amortised_cost_to_fvtpl',
            'reclassification_from_amortised_cost_to_fvoci',
            'reclassification_from_fvoci_to_amortised_cost',
            'reclassification_from_fvoci_to_fvtpl',
            'reclassification_from_fvtpl_to_amortised_cost',
            'reclassification_from_fvtpl_to_fvoci',
            'date_of_reclassification',
            'reason_for_reclassification',
            'change_in_business_model',
            'fair_value_at_reclassification_date',
            'effective_interest_rate_at_reclassification',
            'gain_loss_on_reclassification',
        ],
        'reclassification_of_financial_liabilities': [
            'reclassification_of_financial_liabilities_not_permitted',
        ],
    },
    'derecognition': {
        'derecognition_of_financial_assets': [
            'contractual_rights_to_cash_flows_expired',
            'transferred_rights_to_receive_cash_flows',
            'transferred_substantially_all_risks_and_rewards',
            'neither_transferred_nor_retained_but_transferred_control',
            'continuing_involvement',
            'pass_through_arrangement',
            'derecognition_gain',
            'derecognition_loss',
        ],
        'derecognition_of_financial_liabilities': [
            'financial_liability_extinguished',
            'obligation_discharged',
            'obligation_cancelled',
            'obligation_expired',
            'substantial_modification_of_terms',
            'gain_on_derecognition_of_liability',
            'loss_on_derecognition_of_liability',
        ],
    },
    'offsetting': {
        'offsetting_criteria': [
            'legally_enforceable_right_to_set_off',
            'intention_to_settle_on_net_basis',
            'intention_to_realize_asset_and_settle_liability_simultaneously',
        ],
        'offsetting_disclosures': [
            'gross_amounts_of_financial_assets',
            'gross_amounts_set_off',
            'net_amounts_presented',
            'amounts_subject_to_master_netting_arrangements',
            'collateral_received',
            'collateral_pledged',
            'net_amount_after_offsetting',
        ],
    },
}

# =============================================================================
# SECTION 34: FINANCIAL INSTRUMENTS - FAIR VALUE HIERARCHY
# =============================================================================

FINANCIAL_INSTRUMENTS_FAIR_VALUE = {
    'fair_value_hierarchy': {
        'level_1': {
            'description': [
                'quoted_prices_in_active_markets',
                'unadjusted_quoted_prices',
                'active_market_for_identical_assets_or_liabilities',
            ],
            'instruments': [
                'listed_equity_shares',
                'quoted_equity_instruments',
                'listed_mutual_funds',
                'exchange_traded_funds',
                'listed_bonds',
                'listed_debentures',
                'government_securities_quoted',
                'treasury_bills_quoted',
                'exchange_traded_derivatives',
                'commodity_futures',
                'currency_futures',
                'index_futures',
                'stock_futures',
                'exchange_traded_options',
            ],
        },
        'level_2': {
            'description': [
                'observable_inputs_other_than_quoted_prices',
                'quoted_prices_for_similar_assets_in_active_markets',
                'quoted_prices_in_inactive_markets',
                'inputs_other_than_quoted_prices_that_are_observable',
                'inputs_derived_from_observable_market_data',
            ],
            'valuation_techniques': [
                'market_comparable_approach',
                'discounted_cash_flow_with_observable_inputs',
                'option_pricing_models_with_observable_inputs',
                'black_scholes_model',
                'binomial_model',
                'interest_rate_swap_valuation',
                'forward_contract_valuation',
                'currency_swap_valuation',
            ],
            'instruments': [
                'unlisted_bonds_with_observable_inputs',
                'corporate_bonds_with_observable_inputs',
                'over_the_counter_derivatives',
                'forward_foreign_exchange_contracts',
                'interest_rate_swaps',
                'cross_currency_swaps',
                'currency_options_otc',
                'interest_rate_options',
                'commodity_forwards',
                'structured_products_with_observable_inputs',
            ],
            'observable_inputs': [
                'benchmark_interest_rates',
                'yield_curves',
                'credit_spreads',
                'foreign_exchange_rates',
                'commodity_prices',
                'volatility_surface',
                'prepayment_rates',
                'default_rates',
            ],
        },
        'level_3': {
            'description': [
                'unobservable_inputs',
                'inputs_not_based_on_observable_market_data',
                'entity_own_assumptions',
                'inputs_reflecting_entity_own_assumptions',
            ],
            'valuation_techniques': [
                'discounted_cash_flow_with_unobservable_inputs',
                'adjusted_net_asset_value',
                'earnings_multiple_approach',
                'revenue_multiple_approach',
                'comparable_company_analysis',
                'precedent_transaction_analysis',
                'option_pricing_models_with_unobservable_inputs',
                'monte_carlo_simulation',
                'probability_weighted_expected_return',
            ],
            'instruments': [
                'unquoted_equity_investments',
                'unlisted_equity_shares',
                'private_equity_investments',
                'venture_capital_investments',
                'investment_in_startups',
                'investment_in_unlisted_subsidiaries',
                'investment_in_unlisted_associates',
                'contingent_consideration',
                'earnout_arrangements',
                'complex_derivatives',
                'structured_products_with_unobservable_inputs',
                'investments_in_funds_at_nav',
            ],
            'unobservable_inputs': [
                'discount_rate',
                'risk_adjusted_discount_rate',
                'terminal_growth_rate',
                'long_term_revenue_growth_rate',
                'ebitda_margin',
                'earnings_multiple',
                'revenue_multiple',
                'liquidity_discount',
                'control_premium',
                'minority_discount',
                'volatility_assumption',
                'probability_of_achieving_milestones',
                'expected_cash_flows',
                'credit_risk_adjustment',
            ],
        },
    },
    'fair_value_measurement': {
        'recurring_fair_value_measurements': [
            'financial_assets_measured_at_fair_value_recurring',
            'financial_liabilities_measured_at_fair_value_recurring',
            'investments_measured_at_fair_value',
            'derivatives_measured_at_fair_value',
        ],
        'non_recurring_fair_value_measurements': [
            'assets_measured_at_fair_value_non_recurring',
            'assets_held_for_sale_at_fair_value',
            'impaired_assets_measured_at_fair_value',
            'assets_acquired_in_business_combination',
        ],
        'fair_value_disclosures': [
            'carrying_amount',
            'fair_value',
            'fair_value_hierarchy_level',
            'valuation_technique_used',
            'significant_inputs_used',
            'change_in_valuation_technique',
            'reason_for_change_in_valuation_technique',
        ],
    },
    'transfers_between_levels': [
        'transfers_between_level_1_and_level_2',
        'transfers_into_level_3',
        'transfers_out_of_level_3',
        'reason_for_transfers',
        'date_of_transfer',
        'amount_transferred',
        'policy_for_determining_transfers',
    ],
    'level_3_reconciliation': {
        'movements': [
            'level_3_opening_balance',
            'total_gains_or_losses_in_profit_or_loss',
            'total_gains_or_losses_in_oci',
            'purchases',
            'issues',
            'sales',
            'settlements',
            'transfers_into_level_3',
            'transfers_out_of_level_3',
            'level_3_closing_balance',
            'unrealized_gains_losses_for_assets_held_at_period_end',
        ],
        'sensitivity_analysis': [
            'sensitivity_to_changes_in_unobservable_inputs',
            'effect_of_reasonably_possible_alternative_assumptions',
            'sensitivity_to_discount_rate',
            'sensitivity_to_growth_rate',
            'sensitivity_to_earnings_multiple',
            'sensitivity_to_volatility',
            'range_of_unobservable_inputs',
            'weighted_average_of_inputs',
        ],
    },
    'fair_value_of_financial_instruments_not_at_fair_value': {
        'financial_assets': [
            'fair_value_of_loans',
            'fair_value_of_trade_receivables',
            'fair_value_of_deposits',
            'fair_value_of_other_financial_assets',
        ],
        'financial_liabilities': [
            'fair_value_of_borrowings',
            'fair_value_of_term_loans',
            'fair_value_of_debentures',
            'fair_value_of_bonds',
            'fair_value_of_trade_payables',
            'fair_value_of_other_financial_liabilities',
        ],
        'comparison': [
            'carrying_amount_vs_fair_value',
            'difference_between_carrying_amount_and_fair_value',
            'reason_for_difference',
        ],
    },
    'valuation_process': [
        'valuation_policies_and_procedures',
        'valuation_committee',
        'independent_valuers',
        'frequency_of_valuation',
        'valuation_date',
        'validation_of_valuation_models',
        'back_testing_of_models',
        'calibration_of_inputs',
    ],
}

# =============================================================================
# SECTION 35: FINANCIAL INSTRUMENTS - RISK MANAGEMENT
# =============================================================================

FINANCIAL_INSTRUMENTS_RISK_MANAGEMENT = {
    'risk_management_framework': {
        'risk_management_objectives': [
            'risk_management_objectives_and_policies',
            'risk_governance_structure',
            'board_oversight_of_risk',
            'risk_management_committee',
            'risk_management_policy',
            'risk_appetite',
            'risk_tolerance_limits',
        ],
        'risk_identification': [
            'identification_of_risks',
            'risk_assessment_process',
            'risk_monitoring',
            'risk_reporting',
        ],
    },
    'credit_risk': {
        'credit_risk_exposure': [
            'maximum_exposure_to_credit_risk',
            'credit_risk_on_financial_assets',
            'credit_risk_on_trade_receivables',
            'credit_risk_on_loans',
            'credit_risk_on_investments',
            'credit_risk_on_derivatives',
            'credit_risk_on_bank_balances',
            'credit_risk_on_guarantees_given',
            'credit_risk_on_commitments',
            'off_balance_sheet_credit_exposures',
        ],
        'credit_risk_management': [
            'credit_risk_management_practices',
            'credit_approval_process',
            'credit_limits',
            'credit_monitoring',
            'credit_rating_of_counterparties',
            'external_credit_ratings',
            'internal_credit_ratings',
            'collateral_held_as_security',
            'credit_enhancements',
            'netting_arrangements',
            'master_netting_agreements',
        ],
        'credit_quality': [
            'credit_quality_of_financial_assets',
            'credit_quality_analysis',
            'assets_neither_past_due_nor_impaired',
            'assets_past_due_but_not_impaired',
            'assets_individually_impaired',
            'ageing_of_past_due_assets',
            'past_due_less_than_30_days',
            'past_due_31_to_60_days',
            'past_due_61_to_90_days',
            'past_due_more_than_90_days',
        ],
        'expected_credit_loss': {
            'ecl_approach': [
                'expected_credit_loss_model',
                'general_approach',
                'simplified_approach',
                '12_month_ecl',
                'lifetime_ecl',
                'credit_impaired_financial_assets',
                'purchased_or_originated_credit_impaired',
                'poci_assets',
                'significant_increase_in_credit_risk',
                'sicr_criteria',
                'low_credit_risk_exemption',
            ],
            'ecl_measurement': [
                'probability_of_default',
                'pd',
                'loss_given_default',
                'lgd',
                'exposure_at_default',
                'ead',
                'forward_looking_information',
                'macroeconomic_factors',
                'multiple_scenarios',
                'probability_weighted_ecl',
                'base_case_scenario',
                'upside_scenario',
                'downside_scenario',
            ],
            'ecl_staging': [
                'stage_1_assets',
                'stage_2_assets',
                'stage_3_assets',
                'movement_between_stages',
                'criteria_for_stage_transfer',
            ],
            'provision_matrix': [
                'provision_matrix_for_trade_receivables',
                'historical_loss_rates',
                'historical_credit_loss_experience',
                'adjustment_for_forward_looking_factors',
                'expected_loss_rates_by_ageing',
            ],
            'ecl_movement': [
                'loss_allowance_opening_balance',
                'ecl_recognized_during_period',
                'ecl_reversed_during_period',
                'amounts_written_off',
                'amounts_recovered',
                'loss_allowance_closing_balance',
            ],
        },
        'concentration_of_credit_risk': [
            'concentration_of_credit_risk',
            'concentration_by_counterparty',
            'concentration_by_industry',
            'concentration_by_geography',
            'concentration_by_credit_rating',
            'single_counterparty_exposure',
            'group_exposure',
        ],
        'collateral': [
            'collateral_held',
            'type_of_collateral',
            'fair_value_of_collateral',
            'collateral_called',
            'collateral_sold_or_repledged',
            'credit_impaired_assets_and_collateral',
        ],
        'write_offs': [
            'financial_assets_written_off',
            'policy_for_write_offs',
            'amounts_still_subject_to_enforcement',
            'recoveries_of_amounts_previously_written_off',
        ],
    },
    'liquidity_risk': {
        'liquidity_risk_exposure': [
            'liquidity_risk_exposure',
            'liquidity_risk_on_financial_liabilities',
            'contractual_maturities_of_financial_liabilities',
            'undiscounted_cash_flows',
        ],
        'liquidity_risk_management': [
            'liquidity_risk_management_practices',
            'liquidity_policy',
            'cash_flow_forecasting',
            'liquidity_buffer',
            'liquidity_contingency_plan',
            'access_to_credit_facilities',
            'undrawn_borrowing_facilities',
            'committed_credit_lines',
            'uncommitted_credit_lines',
        ],
        'maturity_analysis': {
            'contractual_maturities': [
                'maturity_analysis_of_financial_liabilities',
                'on_demand',
                'less_than_3_months',
                'within_1_year',
                '3_to_12_months',
                '1_to_2_years',
                '2_to_5_years',
                'more_than_5_years',
                'no_stated_maturity',
            ],
            'derivative_maturities': [
                'maturity_of_derivative_liabilities',
                'gross_settled_derivatives',
                'net_settled_derivatives',
                'cash_inflows_from_derivatives',
                'cash_outflows_from_derivatives',
            ],
        },
        'financing_arrangements': [
            'available_credit_facilities',
            'utilized_credit_facilities',
            'unutilized_credit_facilities',
            'terms_of_credit_facilities',
            'covenants_on_credit_facilities',
        ],
    },
    'market_risk': {
        'currency_risk': {
            'exposure': [
                'foreign_currency_risk_exposure',
                'foreign_currency_assets',
                'foreign_currency_liabilities',
                'net_foreign_currency_exposure',
                'exposure_in_usd',
                'exposure_in_eur',
                'exposure_in_gbp',
                'exposure_in_jpy',
                'exposure_in_other_currencies',
                'unhedged_foreign_currency_exposure',
            ],
            'management': [
                'foreign_currency_risk_management',
                'natural_hedging',
                'hedging_policy',
                'hedging_instruments_used',
                'forward_contracts_for_hedging',
                'options_for_hedging',
                'cross_currency_swaps_for_hedging',
            ],
            'sensitivity': [
                'foreign_currency_sensitivity_analysis',
                'impact_of_currency_movement',
                'impact_of_1_percent_appreciation',
                'impact_of_1_percent_depreciation',
                'impact_of_5_percent_movement',
                'impact_of_10_percent_movement',
                'effect_on_profit_before_tax',
                'effect_on_equity',
            ],
        },
        'interest_rate_risk': {
            'exposure': [
                'interest_rate_risk_exposure',
                'fixed_rate_instruments',
                'floating_rate_instruments',
                'fixed_rate_financial_assets',
                'fixed_rate_financial_liabilities',
                'floating_rate_financial_assets',
                'floating_rate_financial_liabilities',
                'repricing_gap',
            ],
            'management': [
                'interest_rate_risk_management',
                'interest_rate_hedging',
                'interest_rate_swaps',
                'interest_rate_caps',
                'interest_rate_floors',
                'interest_rate_collars',
            ],
            'sensitivity': [
                'interest_rate_sensitivity_analysis',
                'impact_of_interest_rate_movement',
                'impact_of_25_basis_points_increase',
                'impact_of_25_basis_points_decrease',
                'impact_of_50_basis_points_movement',
                'impact_of_100_basis_points_movement',
                'effect_on_profit_before_tax',
                'effect_on_equity',
                'cash_flow_sensitivity',
                'fair_value_sensitivity',
            ],
        },
        'price_risk': {
            'equity_price_risk': [
                'equity_price_risk_exposure',
                'equity_investments_exposed_to_price_risk',
                'quoted_equity_investments',
                'unquoted_equity_investments',
                'equity_price_sensitivity_analysis',
                'impact_of_equity_price_movement',
                'impact_of_5_percent_increase',
                'impact_of_5_percent_decrease',
                'effect_on_profit_before_tax',
                'effect_on_oci',
            ],
            'commodity_price_risk': [
                'commodity_price_risk_exposure',
                'exposure_to_raw_material_prices',
                'exposure_to_fuel_prices',
                'exposure_to_metal_prices',
                'exposure_to_agricultural_commodity_prices',
                'commodity_hedging',
                'commodity_forwards',
                'commodity_futures',
                'commodity_options',
                'commodity_price_sensitivity_analysis',
            ],
        },
    },
    'hedge_accounting': {
        'hedging_relationships': [
            'types_of_hedging_relationships',
            'fair_value_hedges',
            'cash_flow_hedges',
            'hedges_of_net_investment_in_foreign_operations',
        ],
        'hedging_instruments': [
            'forward_exchange_contracts',
            'currency_options',
            'interest_rate_swaps',
            'cross_currency_interest_rate_swaps',
            'commodity_forwards',
            'commodity_futures',
            'commodity_options',
        ],
        'hedged_items': [
            'hedged_items_in_fair_value_hedges',
            'hedged_items_in_cash_flow_hedges',
            'hedged_net_investment',
            'forecast_transactions',
            'firm_commitments',
            'recognized_assets',
            'recognized_liabilities',
        ],
        'hedge_effectiveness': [
            'hedge_effectiveness_assessment',
            'prospective_effectiveness_testing',
            'retrospective_effectiveness_testing',
            'sources_of_hedge_ineffectiveness',
            'hedge_ratio',
            'critical_terms_match',
            'dollar_offset_method',
            'regression_analysis',
        ],
        'hedging_disclosures': [
            'nominal_amount_of_hedging_instruments',
            'carrying_amount_of_hedging_instruments',
            'fair_value_of_hedging_instruments',
            'maturity_of_hedging_instruments',
            'average_rate_of_hedging_instruments',
            'change_in_fair_value_of_hedging_instruments',
            'change_in_fair_value_of_hedged_items',
            'hedge_ineffectiveness_recognized',
            'amounts_reclassified_from_hedging_reserve',
            'amounts_remaining_in_hedging_reserve',
        ],
    },
    'capital_management': [
        'capital_management_objectives',
        'capital_management_policies',
        'capital_structure',
        'debt_to_equity_ratio',
        'gearing_ratio',
        'net_debt_to_equity_ratio',
        'net_debt_to_ebitda',
        'interest_coverage_ratio',
        'debt_service_coverage_ratio',
        'externally_imposed_capital_requirements',
        'compliance_with_capital_requirements',
        'changes_in_capital_management',
    ],
}

# =============================================================================
# SECTION 36: LEASES (IND AS 116)
# =============================================================================

LEASES_IND_AS_116 = {
    'lessee_accounting': {
        'right_of_use_assets': {
            'rou_asset_categories': [
                'right_of_use_assets_land',
                'right_of_use_assets_buildings',
                'right_of_use_assets_plant_and_machinery',
                'right_of_use_assets_vehicles',
                'right_of_use_assets_furniture_and_fixtures',
                'right_of_use_assets_office_equipment',
                'right_of_use_assets_computers',
                'right_of_use_assets_leasehold_land',
                'right_of_use_assets_leasehold_buildings',
                'right_of_use_assets_warehouses',
                'right_of_use_assets_retail_stores',
                'right_of_use_assets_data_centers',
            ],
            'rou_asset_movements': [
                'rou_assets_opening_balance',
                'rou_assets_additions',
                'rou_assets_new_leases',
                'rou_assets_lease_modifications',
                'rou_assets_reassessments',
                'rou_assets_depreciation',
                'rou_assets_impairment',
                'rou_assets_disposals',
                'rou_assets_terminated_leases',
                'rou_assets_foreign_exchange',
                'rou_assets_closing_balance',
            ],
            'rou_asset_measurement': [
                'initial_measurement_of_rou_asset',
                'lease_liability_at_commencement',
                'lease_payments_made_at_or_before_commencement',
                'initial_direct_costs',
                'restoration_costs',
                'lease_incentives_received',
                'subsequent_measurement_of_rou_asset',
                'cost_model',
                'revaluation_model',
                'fair_value_model_for_investment_property',
            ],
        },
        'lease_liabilities': {
            'lease_liability_movements': [
                'lease_liabilities_opening_balance',
                'lease_liabilities_additions',
                'new_lease_liabilities',
                'lease_modifications_increase',
                'lease_modifications_decrease',
                'reassessment_of_lease_term',
                'reassessment_of_lease_payments',
                'interest_expense_on_lease_liabilities',
                'lease_payments_made',
                'principal_repayment',
                'interest_payment',
                'termination_of_leases',
                'foreign_exchange_movement',
                'lease_liabilities_closing_balance',
            ],
            'lease_liability_measurement': [
                'initial_measurement_of_lease_liability',
                'present_value_of_lease_payments',
                'fixed_lease_payments',
                'variable_lease_payments_based_on_index_or_rate',
                'amounts_expected_to_be_payable_under_residual_value_guarantees',
                'exercise_price_of_purchase_option',
                'payments_for_penalties_for_terminating_lease',
                'discount_rate_used',
                'incremental_borrowing_rate',
                'interest_rate_implicit_in_lease',
            ],
            'maturity_analysis': [
                'lease_liabilities_maturity_analysis',
                'undiscounted_lease_payments',
                'lease_payments_within_1_year',
                'lease_payments_1_to_2_years',
                'lease_payments_2_to_3_years',
                'lease_payments_3_to_4_years',
                'lease_payments_4_to_5_years',
                'lease_payments_beyond_5_years',
                'total_undiscounted_lease_payments',
                'finance_charge_future_periods',
                'present_value_of_lease_liabilities',
            ],
        },
        'profit_or_loss_items': [
            'depreciation_of_right_of_use_assets',
            'interest_expense_on_lease_liabilities',
            'expense_relating_to_short_term_leases',
            'expense_relating_to_low_value_asset_leases',
            'expense_relating_to_variable_lease_payments',
            'income_from_subleasing_right_of_use_assets',
            'gains_or_losses_from_sale_and_leaseback',
        ],
        'cash_flow_items': [
            'total_cash_outflow_for_leases',
            'principal_portion_of_lease_payments',
            'interest_portion_of_lease_payments',
            'short_term_lease_payments',
            'low_value_asset_lease_payments',
            'variable_lease_payments',
        ],
    },
    'lessor_accounting': {
        'finance_lease': {
            'recognition': [
                'net_investment_in_lease',
                'lease_receivable',
                'unguaranteed_residual_value',
                'initial_direct_costs',
                'derecognition_of_underlying_asset',
                'gain_or_loss_on_finance_lease',
                'selling_profit_or_loss',
            ],
            'measurement': [
                'gross_investment_in_lease',
                'minimum_lease_payments_receivable',
                'unguaranteed_residual_value',
                'unearned_finance_income',
                'net_investment_in_lease',
                'finance_income_recognized',
                'interest_rate_implicit_in_lease',
            ],
            'maturity_analysis': [
                'finance_lease_receivable_maturity',
                'receivable_within_1_year',
                'receivable_1_to_2_years',
                'receivable_2_to_3_years',
                'receivable_3_to_4_years',
                'receivable_4_to_5_years',
                'receivable_beyond_5_years',
                'total_gross_investment',
                'unearned_finance_income',
                'net_investment_in_lease',
            ],
        },
        'operating_lease': {
            'recognition': [
                'lease_income_from_operating_leases',
                'straight_line_rental_income',
                'variable_lease_income',
                'underlying_asset_retained_on_balance_sheet',
                'depreciation_of_underlying_asset',
            ],
            'maturity_analysis': [
                'operating_lease_receivable_maturity',
                'lease_payments_receivable_within_1_year',
                'lease_payments_receivable_1_to_2_years',
                'lease_payments_receivable_2_to_3_years',
                'lease_payments_receivable_3_to_4_years',
                'lease_payments_receivable_4_to_5_years',
                'lease_payments_receivable_beyond_5_years',
                'total_future_minimum_lease_payments',
            ],
        },
    },
    'lease_disclosures': {
        'general_information': [
            'nature_of_leasing_activities',
            'significant_leasing_arrangements',
            'basis_for_determining_variable_lease_payments',
            'existence_of_extension_options',
            'existence_of_termination_options',
            'existence_of_purchase_options',
            'existence_of_residual_value_guarantees',
            'restrictions_imposed_by_lease_contracts',
            'sale_and_leaseback_transactions',
        ],
        'practical_expedients': [
            'short_term_lease_exemption',
            'low_value_asset_lease_exemption',
            'portfolio_application',
            'single_discount_rate_for_portfolio',
            'reliance_on_onerous_lease_assessment',
            'exclusion_of_initial_direct_costs',
            'hindsight_in_determining_lease_term',
        ],
        'assumptions_and_judgments': [
            'discount_rate_determination',
            'incremental_borrowing_rate_determination',
            'lease_term_determination',
            'assessment_of_extension_options',
            'assessment_of_termination_options',
            'assessment_of_purchase_options',
            'variable_lease_payment_estimation',
        ],
    },
    'sublease': {
        'sublease_classification': [
            'sublease_as_finance_lease',
            'sublease_as_operating_lease',
            'classification_based_on_right_of_use_asset',
        ],
        'sublease_accounting': [
            'intermediate_lessor_accounting',
            'derecognition_of_right_of_use_asset',
            'retention_of_lease_liability',
            'sublease_receivable',
            'sublease_income',
        ],
    },
    'sale_and_leaseback': {
        'transfer_is_a_sale': [
            'sale_proceeds_recognized',
            'right_of_use_asset_recognized',
            'gain_or_loss_on_sale',
            'adjustment_for_off_market_terms',
        ],
        'transfer_is_not_a_sale': [
            'financial_liability_recognized',
            'asset_retained_on_balance_sheet',
            'financing_arrangement',
        ],
    },
    'lease_modifications': {
        'modification_accounting': [
            'lease_modification',
            'change_in_scope_of_lease',
            'change_in_consideration',
            'remeasurement_of_lease_liability',
            'adjustment_to_right_of_use_asset',
            'separate_lease_for_increase_in_scope',
            'revised_discount_rate',
        ],
    },
    'covid_19_rent_concessions': [
        'rent_concessions_received',
        'practical_expedient_for_rent_concessions',
        'reduction_in_lease_payments',
        'deferral_of_lease_payments',
        'forgiveness_of_lease_payments',
        'variable_lease_payment_credit',
    ],
}
