
# =============================================================================
# SECTION 17: INVESTMENTS NOTES
# =============================================================================

INVESTMENTS_NOTES = {
    'non_current_investments': {
        'investment_in_subsidiaries': [
            'investment_in_equity_of_subsidiaries',
            'investment_in_preference_shares_of_subsidiaries',
            'investment_in_subsidiaries_at_cost',
            'investment_in_subsidiaries_at_fair_value',
            'investment_in_wholly_owned_subsidiaries',
            'investment_in_indian_subsidiaries',
            'investment_in_foreign_subsidiaries',
            'investment_in_step_down_subsidiaries',
            'capital_contribution_in_subsidiaries',
            'deemed_investment_in_subsidiaries',
            'provision_for_diminution_in_value_of_investment_in_subsidiaries',
            'impairment_of_investment_in_subsidiaries',
        ],
        'investment_in_associates': [
            'investment_in_equity_of_associates',
            'investment_in_associates_at_cost',
            'investment_in_associates_using_equity_method',
            'share_of_profit_of_associates',
            'share_of_oci_of_associates',
            'goodwill_in_associates',
            'investment_in_indian_associates',
            'investment_in_foreign_associates',
            'provision_for_diminution_in_value_of_investment_in_associates',
            'impairment_of_investment_in_associates',
        ],
        'investment_in_joint_ventures': [
            'investment_in_equity_of_joint_ventures',
            'investment_in_joint_ventures_at_cost',
            'investment_in_joint_ventures_using_equity_method',
            'share_of_profit_of_joint_ventures',
            'share_of_oci_of_joint_ventures',
            'goodwill_in_joint_ventures',
            'investment_in_indian_joint_ventures',
            'investment_in_foreign_joint_ventures',
            'capital_contribution_in_joint_ventures',
            'provision_for_diminution_in_value_of_investment_in_jv',
            'impairment_of_investment_in_joint_ventures',
        ],
        'investment_in_partnership_firms': [
            'investment_in_partnership_firms',
            'capital_contribution_in_partnership_firms',
            'share_of_profit_of_partnership_firms',
            'investment_in_llp',
            'capital_contribution_in_llp',
        ],
        'equity_instruments': [
            'investment_in_equity_instruments',
            'quoted_equity_shares',
            'unquoted_equity_shares',
            'listed_equity_shares',
            'unlisted_equity_shares',
            'equity_instruments_at_fvtpl',
            'equity_instruments_at_fvoci',
            'equity_instruments_designated_at_fvoci',
            'investment_in_equity_shares_of_other_companies',
            'strategic_investments',
            'trade_investments',
            'investment_in_venture_capital_funds',
            'investment_in_private_equity_funds',
            'investment_in_aif',
            'investment_in_reits',
            'investment_in_invits',
        ],
        'preference_shares': [
            'investment_in_preference_shares',
            'quoted_preference_shares',
            'unquoted_preference_shares',
            'cumulative_preference_shares',
            'non_cumulative_preference_shares',
            'redeemable_preference_shares',
            'non_redeemable_preference_shares',
            'convertible_preference_shares',
            'non_convertible_preference_shares',
            'optionally_convertible_preference_shares',
            'compulsorily_convertible_preference_shares',
        ],
        'debt_instruments': [
            'investment_in_debentures',
            'quoted_debentures',
            'unquoted_debentures',
            'secured_debentures',
            'unsecured_debentures',
            'convertible_debentures',
            'non_convertible_debentures',
            'optionally_convertible_debentures',
            'compulsorily_convertible_debentures',
            'investment_in_bonds',
            'quoted_bonds',
            'unquoted_bonds',
            'government_bonds',
            'corporate_bonds',
            'infrastructure_bonds',
            'tax_free_bonds',
            'taxable_bonds',
            'psu_bonds',
            'bank_bonds',
            'debt_instruments_at_amortised_cost',
            'debt_instruments_at_fvtpl',
            'debt_instruments_at_fvoci',
        ],
        'government_securities': [
            'investment_in_government_securities',
            'central_government_securities',
            'state_government_securities',
            'treasury_bonds',
            'dated_government_securities',
            'sovereign_gold_bonds',
            'inflation_indexed_bonds',
            'special_securities',
            'government_securities_at_amortised_cost',
            'government_securities_at_fvtpl',
            'government_securities_at_fvoci',
        ],
        'other_non_current_investments': [
            'investment_in_national_savings_certificates',
            'nsc_investment',
            'investment_in_kisan_vikas_patra',
            'investment_in_indira_vikas_patra',
            'investment_in_post_office_deposits',
            'investment_in_property',
            'investment_in_gold',
            'investment_in_silver',
            'investment_in_commodities',
            'investment_in_art_and_collectibles',
            'other_investments_non_current',
        ],
    },
    'current_investments': {
        'mutual_funds': [
            'investment_in_mutual_funds',
            'equity_mutual_funds',
            'debt_mutual_funds',
            'hybrid_mutual_funds',
            'liquid_funds',
            'overnight_funds',
            'ultra_short_duration_funds',
            'low_duration_funds',
            'money_market_funds',
            'short_duration_funds',
            'medium_duration_funds',
            'banking_and_psu_funds',
            'corporate_bond_funds',
            'credit_risk_funds',
            'gilt_funds',
            'fixed_maturity_plans',
            'fmp',
            'arbitrage_funds',
            'index_funds',
            'etf_investments',
            'exchange_traded_funds',
            'gold_etf',
            'equity_etf',
            'debt_etf',
        ],
        'money_market_instruments': [
            'treasury_bills',
            '91_day_treasury_bills',
            '182_day_treasury_bills',
            '364_day_treasury_bills',
            'commercial_paper',
            'certificate_of_deposits',
            'cd_investments',
            'cp_investments',
            'repo_investments',
            'reverse_repo_investments',
            'cblo_investments',
            'triparty_repo',
        ],
        'deposits': [
            'fixed_deposits_with_banks',
            'fixed_deposits_with_nbfc',
            'fixed_deposits_with_financial_institutions',
            'fixed_deposits_with_companies',
            'fixed_deposits_more_than_12_months',
            'fixed_deposits_3_to_12_months',
            'margin_money_deposits',
            'security_deposits_with_banks',
            'earmarked_deposits',
            'deposits_under_lien',
            'deposits_pledged',
            'deposits_with_original_maturity_more_than_3_months',
            'deposits_with_original_maturity_more_than_12_months',
        ],
        'quoted_current_investments': [
            'quoted_equity_shares_current',
            'quoted_preference_shares_current',
            'quoted_debentures_current',
            'quoted_bonds_current',
            'quoted_government_securities_current',
        ],
        'unquoted_current_investments': [
            'unquoted_equity_shares_current',
            'unquoted_preference_shares_current',
            'unquoted_debentures_current',
            'unquoted_bonds_current',
        ],
    },
    'investment_disclosures': {
        'classification': [
            'investments_at_amortised_cost',
            'investments_at_fvtpl',
            'investments_at_fvoci',
            'investments_designated_at_fvtpl',
            'investments_designated_at_fvoci',
            'held_to_maturity_investments',
            'available_for_sale_investments',
            'held_for_trading_investments',
        ],
        'measurement': [
            'cost_of_investment',
            'fair_value_of_investment',
            'carrying_value_of_investment',
            'market_value_of_investment',
            'book_value_of_investment',
            'face_value_of_investment',
            'acquisition_cost',
            'amortised_cost',
            'fair_value_gain_on_investments',
            'fair_value_loss_on_investments',
            'unrealized_gain_on_investments',
            'unrealized_loss_on_investments',
            'impairment_of_investments',
            'provision_for_diminution_in_value',
            'expected_credit_loss_on_debt_investments',
        ],
        'fair_value_hierarchy': [
            'level_1_investments',
            'level_2_investments',
            'level_3_investments',
            'quoted_prices_in_active_markets',
            'observable_inputs',
            'unobservable_inputs',
            'valuation_technique',
            'transfer_between_levels',
        ],
        'aggregate_information': [
            'aggregate_cost_of_quoted_investments',
            'aggregate_market_value_of_quoted_investments',
            'aggregate_cost_of_unquoted_investments',
            'aggregate_provision_for_diminution',
            'aggregate_amount_of_impairment',
            'number_of_shares',
            'face_value_per_share',
            'percentage_of_holding',
            'country_of_incorporation',
            'principal_activities',
        ],
        'pledged_and_restricted': [
            'investments_pledged_as_security',
            'investments_under_lien',
            'investments_earmarked',
            'investments_held_by_trustees',
            'restricted_investments',
        ],
    },
}

# =============================================================================
# SECTION 18: INVENTORIES NOTES
# =============================================================================

INVENTORIES_NOTES = {
    'inventory_categories': {
        'raw_materials': [
            'raw_materials',
            'raw_materials_at_factory',
            'raw_materials_at_warehouse',
            'raw_materials_at_ports',
            'raw_materials_in_transit',
            'raw_materials_with_third_parties',
            'imported_raw_materials',
            'indigenous_raw_materials',
            'bonded_raw_materials',
            'duty_paid_raw_materials',
            'duty_free_raw_materials',
        ],
        'work_in_progress': [
            'work_in_progress',
            'wip',
            'semi_finished_goods',
            'goods_under_process',
            'goods_in_production',
            'partially_completed_goods',
            'wip_at_factory',
            'wip_with_third_parties',
            'job_work_in_progress',
        ],
        'finished_goods': [
            'finished_goods',
            'manufactured_goods',
            'finished_products',
            'finished_goods_at_factory',
            'finished_goods_at_warehouse',
            'finished_goods_at_depot',
            'finished_goods_at_showroom',
            'finished_goods_in_transit',
            'finished_goods_with_third_parties',
            'finished_goods_with_consignment_agents',
            'finished_goods_on_consignment',
            'goods_lying_with_customers',
            'goods_sent_on_approval',
            'excisable_goods',
            'non_excisable_goods',
        ],
        'stock_in_trade': [
            'stock_in_trade',
            'traded_goods',
            'goods_purchased_for_resale',
            'merchandise',
            'trading_stock',
            'stock_in_trade_at_warehouse',
            'stock_in_trade_in_transit',
        ],
        'stores_and_spares': [
            'stores_and_spares',
            'stores',
            'spare_parts',
            'consumable_stores',
            'engineering_stores',
            'electrical_stores',
            'mechanical_stores',
            'maintenance_spares',
            'capital_spares',
            'insurance_spares',
            'rotable_spares',
            'stores_in_transit',
            'stores_with_third_parties',
        ],
        'packing_materials': [
            'packing_materials',
            'packaging_materials',
            'containers',
            'bottles',
            'cans',
            'cartons',
            'boxes',
            'drums',
            'bags',
            'labels',
            'caps_and_closures',
            'shrink_wraps',
            'packing_materials_in_transit',
        ],
        'loose_tools': [
            'loose_tools',
            'hand_tools',
            'small_tools',
            'measuring_instruments',
            'gauges',
            'jigs_and_fixtures',
            'dies_and_moulds_inventory',
        ],
        'fuel_and_lubricants': [
            'fuel',
            'diesel',
            'petrol',
            'coal',
            'furnace_oil',
            'natural_gas',
            'lpg',
            'lubricants',
            'oils_and_greases',
        ],
        'chemicals_and_reagents': [
            'chemicals',
            'process_chemicals',
            'laboratory_chemicals',
            'reagents',
            'catalysts',
            'solvents',
        ],
        'scrap_and_waste': [
            'scrap',
            'scrap_materials',
            'waste',
            'by_products',
            'residues',
            'salvage_materials',
            'obsolete_materials',
            'damaged_goods',
            'rejected_goods',
        ],
        'property_development': [
            'land_stock',
            'land_held_for_development',
            'development_rights',
            'construction_work_in_progress',
            'stock_of_flats_under_construction',
            'stock_of_completed_flats',
            'stock_of_commercial_units',
            'stock_of_plots',
            'property_held_for_sale',
            'real_estate_inventory',
        ],
        'others': [
            'food_and_beverages_stock',
            'agricultural_produce',
            'livestock_inventory',
            'biological_assets_inventory',
            'plantation_produce',
            'minerals_and_ores',
            'petroleum_products_stock',
            'other_inventories',
        ],
    },
    'inventory_provisions': [
        'provision_for_obsolete_inventory',
        'provision_for_slow_moving_inventory',
        'provision_for_non_moving_inventory',
        'provision_for_damaged_inventory',
        'provision_for_expired_inventory',
        'provision_for_inventory_write_down',
        'provision_for_net_realizable_value',
        'allowance_for_inventory_losses',
        'inventory_valuation_allowance',
        'write_down_of_inventories',
        'reversal_of_inventory_write_down',
    ],
    'inventory_disclosures': {
        'valuation_method': [
            'cost_or_net_realizable_value_whichever_is_lower',
            'first_in_first_out',
            'fifo',
            'weighted_average_cost',
            'specific_identification',
            'standard_cost',
            'retail_method',
            'net_realizable_value',
            'fair_value_less_costs_to_sell',
        ],
        'cost_components': [
            'cost_of_purchase',
            'cost_of_conversion',
            'other_costs_to_bring_inventory_to_present_location',
            'direct_materials',
            'direct_labour',
            'manufacturing_overheads',
            'fixed_production_overheads',
            'variable_production_overheads',
            'abnormal_waste_excluded',
            'storage_costs_excluded',
            'administrative_overheads_excluded',
            'selling_costs_excluded',
            'borrowing_costs_excluded',
        ],
        'pledged_and_hypothecated': [
            'inventories_pledged_as_security',
            'inventories_hypothecated_to_banks',
            'inventories_under_lien',
            'inventories_with_third_parties',
            'goods_in_transit_insured',
        ],
        'write_downs': [
            'inventories_written_down_to_nrv',
            'amount_of_write_down',
            'circumstances_leading_to_write_down',
            'reversal_of_previous_write_down',
            'amount_of_reversal',
            'circumstances_leading_to_reversal',
        ],
        'ageing': [
            'inventory_less_than_6_months',
            'inventory_6_to_12_months',
            'inventory_1_to_2_years',
            'inventory_more_than_2_years',
            'slow_moving_inventory',
            'non_moving_inventory',
            'obsolete_inventory',
        ],
    },
}

# =============================================================================
# SECTION 19: TRADE RECEIVABLES NOTES
# =============================================================================

TRADE_RECEIVABLES_NOTES = {
    'trade_receivables_categories': {
        'by_security': [
            'trade_receivables_secured',
            'trade_receivables_secured_considered_good',
            'trade_receivables_unsecured',
            'trade_receivables_unsecured_considered_good',
            'trade_receivables_unsecured_considered_doubtful',
        ],
        'by_credit_risk': [
            'trade_receivables_considered_good',
            'trade_receivables_which_have_significant_increase_in_credit_risk',
            'trade_receivables_credit_impaired',
            'trade_receivables_doubtful',
        ],
        'by_dispute_status': [
            'trade_receivables_undisputed',
            'trade_receivables_undisputed_considered_good',
            'trade_receivables_undisputed_considered_doubtful',
            'trade_receivables_disputed',
            'trade_receivables_disputed_considered_good',
            'trade_receivables_disputed_considered_doubtful',
        ],
        'by_related_party': [
            'receivables_from_related_parties',
            'receivables_from_holding_company',
            'receivables_from_subsidiaries',
            'receivables_from_fellow_subsidiaries',
            'receivables_from_associates',
            'receivables_from_joint_ventures',
            'receivables_from_key_management_personnel',
            'receivables_from_directors',
            'receivables_from_relatives_of_directors',
            'receivables_from_enterprises_over_which_kmp_have_significant_influence',
        ],
        'by_geography': [
            'domestic_receivables',
            'export_receivables',
            'receivables_from_government',
            'receivables_from_public_sector',
            'receivables_from_private_sector',
        ],
    },
    'trade_receivables_ageing': {
        'undisputed_considered_good': [
            'undisputed_good_not_due',
            'undisputed_good_less_than_6_months',
            'undisputed_good_6_months_to_1_year',
            'undisputed_good_1_to_2_years',
            'undisputed_good_2_to_3_years',
            'undisputed_good_more_than_3_years',
        ],
        'undisputed_significant_credit_risk': [
            'undisputed_credit_risk_not_due',
            'undisputed_credit_risk_less_than_6_months',
            'undisputed_credit_risk_6_months_to_1_year',
            'undisputed_credit_risk_1_to_2_years',
            'undisputed_credit_risk_2_to_3_years',
            'undisputed_credit_risk_more_than_3_years',
        ],
        'undisputed_credit_impaired': [
            'undisputed_impaired_not_due',
            'undisputed_impaired_less_than_6_months',
            'undisputed_impaired_6_months_to_1_year',
            'undisputed_impaired_1_to_2_years',
            'undisputed_impaired_2_to_3_years',
            'undisputed_impaired_more_than_3_years',
        ],
        'disputed_considered_good': [
            'disputed_good_not_due',
            'disputed_good_less_than_6_months',
            'disputed_good_6_months_to_1_year',
            'disputed_good_1_to_2_years',
            'disputed_good_2_to_3_years',
            'disputed_good_more_than_3_years',
        ],
        'disputed_significant_credit_risk': [
            'disputed_credit_risk_not_due',
            'disputed_credit_risk_less_than_6_months',
            'disputed_credit_risk_6_months_to_1_year',
            'disputed_credit_risk_1_to_2_years',
            'disputed_credit_risk_2_to_3_years',
            'disputed_credit_risk_more_than_3_years',
        ],
        'disputed_credit_impaired': [
            'disputed_impaired_not_due',
            'disputed_impaired_less_than_6_months',
            'disputed_impaired_6_months_to_1_year',
            'disputed_impaired_1_to_2_years',
            'disputed_impaired_2_to_3_years',
            'disputed_impaired_more_than_3_years',
        ],
    },
    'unbilled_and_contract_assets': [
        'unbilled_revenue',
        'unbilled_receivables',
        'accrued_income',
        'accrued_revenue',
        'revenue_recognized_but_not_billed',
        'contract_assets',
        'costs_to_obtain_contract',
        'costs_to_fulfill_contract',
        'right_to_consideration_conditional',
        'retention_receivables',
        'milestone_receivables',
    ],
    'allowance_for_credit_losses': {
        'provision_movements': [
            'provision_for_doubtful_debts_opening',
            'allowance_for_ecl_opening',
            'provision_created_during_year',
            'ecl_recognized_during_year',
            'provision_reversed_during_year',
            'ecl_reversed_during_year',
            'bad_debts_written_off',
            'amounts_recovered_during_year',
            'exchange_differences',
            'provision_for_doubtful_debts_closing',
            'allowance_for_ecl_closing',
        ],
        'ecl_measurement': [
            'expected_credit_loss',
            'lifetime_expected_credit_loss',
            '12_month_expected_credit_loss',
            'probability_of_default',
            'loss_given_default',
            'exposure_at_default',
            'credit_risk_rating',
            'simplified_approach',
            'general_approach',
            'provision_matrix',
            'historical_loss_rates',
            'forward_looking_adjustments',
        ],
    },
    'trade_receivables_disclosures': {
        'factoring_and_discounting': [
            'receivables_factored',
            'receivables_discounted',
            'receivables_assigned',
            'receivables_sold',
            'recourse_liability',
            'non_recourse_factoring',
            'with_recourse_factoring',
            'bill_discounting',
            'bills_purchased_by_bank',
            'credit_insurance',
        ],
        'credit_terms': [
            'normal_credit_period',
            'extended_credit_period',
            'credit_limit',
            'maximum_credit_exposure',
            'concentration_of_credit_risk',
            'major_customers',
            'top_10_customers',
        ],
        'security': [
            'receivables_secured_by_bank_guarantee',
            'receivables_secured_by_letter_of_credit',
            'receivables_covered_by_credit_insurance',
            'collateral_held',
            'guarantees_held',
        ],
    },
}

# =============================================================================
# SECTION 20: CASH AND BANK BALANCES NOTES
# =============================================================================

CASH_AND_BANK_BALANCES_NOTES = {
    'cash_and_cash_equivalents': {
        'cash_on_hand': [
            'cash_on_hand',
            'cash_in_hand',
            'petty_cash',
            'petty_cash_balances',
            'imprest_cash',
            'cash_floats',
            'cash_at_branches',
            'cash_at_outlets',
            'cash_at_retail_stores',
            'cash_at_collection_centers',
            'foreign_currency_on_hand',
        ],
        'cheques_and_drafts': [
            'cheques_on_hand',
            'cheques_in_hand',
            'demand_drafts_on_hand',
            'pay_orders_on_hand',
            'bankers_cheques',
            'post_dated_cheques',
            'cheques_deposited_not_cleared',
            'cheques_in_transit',
        ],
        'remittances_in_transit': [
            'remittances_in_transit',
            'cash_in_transit',
            'funds_in_transit',
            'collections_in_transit',
        ],
        'balances_with_banks': [
            'balances_with_banks',
            'balances_in_current_accounts',
            'balances_in_savings_accounts',
            'balances_in_cash_credit_accounts',
            'balances_in_overdraft_accounts',
            'balances_in_eefc_accounts',
            'balances_in_foreign_currency_accounts',
            'balances_with_scheduled_banks',
            'balances_with_non_scheduled_banks',
            'balances_with_foreign_banks',
            'balances_with_indian_banks_abroad',
        ],
        'short_term_deposits': [
            'deposits_with_original_maturity_less_than_3_months',
            'short_term_deposits_with_banks',
            'call_deposits',
            'overnight_deposits',
            'money_at_call_and_short_notice',
            'term_deposits_maturing_within_3_months',
        ],
        'highly_liquid_investments': [
            'highly_liquid_investments',
            'money_market_investments',
            'liquid_mutual_funds',
            'overnight_funds',
            'treasury_bills_less_than_3_months',
        ],
    },
    'other_bank_balances': {
        'earmarked_balances': [
            'earmarked_balances_with_banks',
            'unpaid_dividend_accounts',
            'unclaimed_dividend_accounts',
            'unpaid_matured_deposits_accounts',
            'unpaid_matured_debentures_accounts',
            'fractional_entitlement_accounts',
            'investor_education_and_protection_fund',
            'iepf_accounts',
        ],
        'margin_money_deposits': [
            'margin_money_deposits',
            'margin_money_against_bank_guarantees',
            'margin_money_against_letter_of_credit',
            'margin_money_against_other_commitments',
            'margin_money_for_forward_contracts',
            'margin_money_for_derivative_transactions',
            'margin_deposits_with_exchanges',
            'margin_with_clearing_corporations',
        ],
        'deposits_under_lien': [
            'deposits_held_as_lien',
            'deposits_pledged_with_banks',
            'deposits_pledged_with_government',
            'deposits_pledged_with_courts',
            'deposits_pledged_with_authorities',
            'deposits_pledged_for_statutory_compliance',
            'deposits_pledged_as_security_for_loans',
            'deposits_pledged_for_overdraft_facility',
            'deposits_pledged_for_credit_facilities',
        ],
        'deposits_with_maturity_more_than_3_months': [
            'fixed_deposits_with_maturity_more_than_3_months',
            'term_deposits_more_than_3_months',
            'deposits_with_maturity_3_to_12_months',
            'deposits_with_maturity_more_than_12_months',
            'deposits_maturing_after_12_months_from_reporting_date',
        ],
        'restricted_cash': [
            'restricted_cash',
            'restricted_bank_balances',
            'escrow_accounts',
            'trust_accounts',
            'client_money_accounts',
            'statutory_reserve_accounts',
            'sinking_fund_accounts',
            'debt_service_reserve_accounts',
            'dsra',
            'cash_collateral',
        ],
        'special_accounts': [
            'csr_accounts',
            'corporate_social_responsibility_accounts',
            'dividend_distribution_accounts',
            'buyback_escrow_accounts',
            'acquisition_escrow_accounts',
            'stamp_duty_accounts',
            'government_grant_accounts',
        ],
    },
    'bank_balances_disclosures': {
        'bank_reconciliation': [
            'balance_as_per_books',
            'balance_as_per_bank_statement',
            'cheques_issued_but_not_presented',
            'cheques_deposited_but_not_credited',
            'direct_credits_not_recorded',
            'direct_debits_not_recorded',
            'bank_charges_not_recorded',
            'interest_credited_not_recorded',
            'reconciling_items',
        ],
        'credit_facilities': [
            'cash_credit_limit',
            'overdraft_limit',
            'utilized_limit',
            'unutilized_limit',
            'drawing_power',
            'outstanding_balance',
            'securities_pledged',
        ],
        'foreign_currency': [
            'foreign_currency_balances',
            'usd_balances',
            'eur_balances',
            'gbp_balances',
            'jpy_balances',
            'other_currency_balances',
            'exchange_rate_used',
            'exchange_gain_loss_on_translation',
        ],
        'deposit_rates': [
            'interest_rate_on_deposits',
            'maturity_profile_of_deposits',
            'deposits_maturing_within_1_month',
            'deposits_maturing_1_to_3_months',
            'deposits_maturing_3_to_6_months',
            'deposits_maturing_6_to_12_months',
            'deposits_maturing_beyond_12_months',
        ],
    },
    'cash_flow_statement_reconciliation': [
        'cash_and_cash_equivalents_per_balance_sheet',
        'bank_overdrafts_repayable_on_demand',
        'bank_overdrafts_deducted',
        'cash_credit_deducted',
        'cash_and_cash_equivalents_per_cash_flow_statement',
        'restricted_cash_excluded',
        'cash_equivalents_included',
    ],
}

# =============================================================================
# SECTION 21: LOANS AND ADVANCES NOTES
# =============================================================================

LOANS_AND_ADVANCES_NOTES = {
    'non_current_loans': {
        'loans_to_related_parties': [
            'loans_to_subsidiaries',
            'loans_to_wholly_owned_subsidiaries',
            'loans_to_other_subsidiaries',
            'loans_to_associates',
            'loans_to_joint_ventures',
            'loans_to_holding_company',
            'loans_to_fellow_subsidiaries',
            'loans_to_enterprises_under_common_control',
            'loans_to_key_management_personnel',
            'loans_to_directors',
            'loans_to_relatives_of_directors',
            'loans_to_enterprises_in_which_directors_are_interested',
            'loans_to_enterprises_over_which_kmp_have_significant_influence',
        ],
        'loans_to_employees': [
            'loans_to_employees',
            'staff_loans',
            'housing_loans_to_employees',
            'vehicle_loans_to_employees',
            'computer_loans_to_employees',
            'personal_loans_to_employees',
            'festival_advance_to_employees',
            'salary_advance_to_employees',
            'medical_advance_to_employees',
            'education_loans_to_employees',
            'marriage_loans_to_employees',
            'loans_under_employee_welfare_schemes',
        ],
        'inter_corporate_deposits': [
            'inter_corporate_deposits_given',
            'icd_given',
            'deposits_with_companies',
            'deposits_with_nbfc',
            'deposits_with_financial_institutions',
            'deposits_with_body_corporates',
        ],
        'security_deposits': [
            'security_deposits_given',
            'rental_deposits',
            'lease_deposits',
            'utility_deposits',
            'electricity_deposits',
            'telephone_deposits',
            'gas_deposits',
            'water_deposits',
            'vendor_deposits',
            'supplier_deposits',
            'customs_deposits',
            'excise_deposits',
            'sales_tax_deposits',
            'earnest_money_deposits_given',
            'tender_deposits_given',
            'bid_security_deposits',
            'performance_security_deposits',
            'contract_deposits',
        ],
        'other_non_current_loans': [
            'other_loans_non_current',
            'loans_against_property',
            'loans_against_securities',
            'loans_against_fixed_deposits',
            'margin_funding',
            'hire_purchase_receivables',
            'finance_lease_receivables',
        ],
    },
    'current_loans': {
        'loans_to_related_parties_current': [
            'loans_to_subsidiaries_current',
            'loans_to_associates_current',
            'loans_to_joint_ventures_current',
            'loans_to_directors_current',
            'loans_to_kmp_current',
            'current_portion_of_loans_to_related_parties',
        ],
        'loans_to_employees_current': [
            'loans_to_employees_current',
            'staff_loans_current',
            'salary_advances',
            'travel_advances',
            'imprest_balances',
            'current_portion_of_employee_loans',
        ],
        'inter_corporate_deposits_current': [
            'inter_corporate_deposits_current',
            'icd_current',
            'short_term_deposits_with_companies',
            'short_term_deposits_with_nbfc',
        ],
        'security_deposits_current': [
            'security_deposits_current',
            'current_portion_of_security_deposits',
            'refundable_deposits',
        ],
    },
    'loans_classification': {
        'by_security': [
            'loans_secured',
            'loans_secured_considered_good',
            'loans_unsecured',
            'loans_unsecured_considered_good',
            'loans_unsecured_considered_doubtful',
        ],
        'by_credit_risk': [
            'loans_considered_good',
            'loans_which_have_significant_increase_in_credit_risk',
            'loans_credit_impaired',
            'loans_doubtful',
        ],
    },
    'advances': {
        'capital_advances': [
            'capital_advances',
            'advances_for_capital_goods',
            'advances_for_property_plant_equipment',
            'advances_for_intangible_assets',
            'advances_to_contractors',
            'advances_for_construction',
            'advances_for_land',
            'advances_for_buildings',
            'advances_for_plant_and_machinery',
        ],
        'advances_to_suppliers': [
            'advances_to_suppliers',
            'advances_to_vendors',
            'advances_for_goods',
            'advances_for_raw_materials',
            'advances_for_stores_and_spares',
            'advances_for_services',
            'advances_for_job_work',
            'prepayments_to_suppliers',
        ],
        'other_advances': [
            'other_advances',
            'advances_to_contractors',
            'advances_to_sub_contractors',
            'mobilization_advances',
            'running_account_advances',
            'advances_recoverable_in_cash',
            'advances_recoverable_in_kind',
            'advances_for_expenses',
        ],
    },
    'loans_disclosures': {
        'terms_and_conditions': [
            'rate_of_interest',
            'repayment_terms',
            'tenure_of_loan',
            'security_provided',
            'purpose_of_loan',
            'loan_agreement_date',
            'maturity_date',
        ],
        'impairment': [
            'provision_for_doubtful_loans',
            'allowance_for_expected_credit_losses',
            'ecl_on_loans',
            'loans_written_off',
            'loans_recovered',
            'impairment_loss_recognized',
            'impairment_loss_reversed',
        ],
        'maximum_balance': [
            'maximum_balance_outstanding_during_year',
            'maximum_amount_outstanding_at_any_time',
        ],
        'compliance': [
            'loans_in_compliance_with_section_185',
            'loans_in_compliance_with_section_186',
            'disclosure_under_section_186_4',
            'register_of_loans_maintained',
        ],
    },
}

# =============================================================================
# SECTION 22: OTHER ASSETS NOTES
# =============================================================================

OTHER_ASSETS_NOTES = {
    'other_non_current_assets': {
        'prepaid_expenses': [
            'prepaid_expenses_non_current',
            'prepaid_rent_non_current',
            'prepaid_insurance_non_current',
            'prepaid_maintenance_non_current',
            'prepaid_license_fees_non_current',
            'prepaid_software_costs_non_current',
            'prepaid_lease_payments',
            'deferred_lease_costs',
            'upfront_lease_payments',
        ],
        'deferred_costs': [
            'deferred_costs',
            'deferred_employee_costs',
            'deferred_borrowing_costs',
            'deferred_financing_costs',
            'deferred_loan_origination_costs',
            'deferred_debt_issuance_costs',
            'deferred_contract_costs',
            'costs_to_obtain_contract',
            'costs_to_fulfill_contract',
            'deferred_commission_costs',
            'deferred_sales_costs',
            'deferred_marketing_costs',
        ],
        'balances_with_government': [
            'balances_with_government_authorities_non_current',
            'gst_input_credit_non_current',
            'cenvat_credit_non_current',
            'service_tax_credit_non_current',
            'vat_credit_non_current',
            'customs_duty_refund_receivable_non_current',
            'excise_duty_refund_receivable_non_current',
            'export_incentives_receivable_non_current',
            'duty_drawback_receivable_non_current',
            'subsidies_receivable_non_current',
            'government_grants_receivable_non_current',
        ],
        'retirement_benefit_assets': [
            'gratuity_fund_asset',
            'defined_benefit_asset',
            'pension_fund_asset',
            'superannuation_fund_asset',
            'provident_fund_asset',
            'leave_encashment_fund_asset',
            'net_defined_benefit_asset',
            'fair_value_of_plan_assets_exceeding_obligation',
        ],
        'other_non_current_assets': [
            'other_non_current_assets',
            'unamortized_expenses',
            'deferred_revenue_expenditure',
            'miscellaneous_expenditure_not_written_off',
            'share_issue_expenses_not_written_off',
            'preliminary_expenses_not_written_off',
            'assets_held_for_disposal',
            'non_current_assets_held_for_sale',
        ],
    },
    'other_current_assets': {
        'prepaid_expenses_current': [
            'prepaid_expenses',
            'prepaid_rent',
            'prepaid_insurance',
            'prepaid_maintenance',
            'prepaid_subscription',
            'prepaid_annual_fees',
            'prepaid_license_fees',
            'prepaid_software_licenses',
            'prepaid_advertising',
            'prepaid_marketing',
            'prepaid_commission',
            'prepaid_interest',
            'prepaid_taxes',
            'prepaid_registration_fees',
            'prepaid_membership_fees',
        ],
        'advances_recoverable': [
            'advances_recoverable',
            'advances_to_employees',
            'salary_advances',
            'travel_advances',
            'medical_advances',
            'imprest_balances',
            'petty_cash_advances',
            'advances_to_suppliers',
            'advances_for_expenses',
            'advances_to_contractors',
            'advances_recoverable_in_cash',
            'advances_recoverable_in_kind_or_value',
        ],
        'balances_with_government_current': [
            'balances_with_government_authorities',
            'gst_input_credit',
            'cgst_input_credit',
            'sgst_input_credit',
            'igst_input_credit',
            'gst_cess_input_credit',
            'gst_tds_receivable',
            'gst_tcs_receivable',
            'gst_refund_receivable',
            'gst_electronic_credit_ledger',
            'gst_electronic_cash_ledger',
            'cenvat_credit',
            'service_tax_credit',
            'vat_input_credit',
            'cst_refund_receivable',
            'customs_duty_refund_receivable',
            'excise_duty_refund_receivable',
            'export_incentives_receivable',
            'duty_drawback_receivable',
            'meis_receivable',
            'seis_receivable',
            'rodtep_receivable',
            'rosctl_receivable',
            'focus_product_scheme_receivable',
            'focus_market_scheme_receivable',
            'advance_license_benefits_receivable',
            'epcg_benefits_receivable',
            'subsidies_receivable',
            'government_grants_receivable',
            'pli_scheme_receivable',
        ],
        'claims_receivable': [
            'claims_receivable',
            'insurance_claims_receivable',
            'claims_against_carriers',
            'claims_against_suppliers',
            'claims_against_contractors',
            'claims_against_customers',
            'claims_against_government',
            'warranty_claims_receivable',
            'liquidated_damages_receivable',
            'compensation_receivable',
            'legal_claims_receivable',
            'arbitration_claims_receivable',
        ],
        'receivables_from_employees': [
            'receivables_from_employees',
            'dues_from_employees',
            'outstanding_from_employees',
            'recoverable_from_employees',
            'notice_period_recovery',
            'training_bond_recovery',
            'excess_payment_recovery',
        ],
        'other_receivables': [
            'other_receivables',
            'sundry_receivables',
            'miscellaneous_receivables',
            'reimbursement_receivable',
            'shared_services_receivable',
            'management_fees_receivable',
            'royalty_receivable',
            'license_fees_receivable',
            'technical_fees_receivable',
            'interest_receivable',
            'dividend_receivable',
            'rent_receivable',
            'commission_receivable',
        ],
        'assets_held_for_sale': [
            'assets_held_for_sale',
            'disposal_group_held_for_sale',
            'non_current_assets_classified_as_held_for_sale',
            'assets_of_discontinued_operations',
            'property_held_for_sale',
            'investment_property_held_for_sale',
            'ppe_held_for_sale',
            'intangible_assets_held_for_sale',
            'investments_held_for_sale',
            'subsidiaries_held_for_sale',
        ],
    },
    'contract_assets_and_liabilities': {
        'contract_assets': [
            'contract_assets',
            'unbilled_revenue',
            'unbilled_receivables',
            'accrued_income',
            'accrued_revenue',
            'right_to_consideration_conditional',
            'revenue_in_excess_of_billing',
            'earned_but_not_billed',
            'milestone_receivables',
            'percentage_of_completion_receivables',
            'retention_receivables',
            'costs_incurred_plus_profit_less_billing',
        ],
        'contract_liabilities': [
            'contract_liabilities',
            'advance_from_customers',
            'unearned_revenue',
            'deferred_revenue',
            'billing_in_excess_of_revenue',
            'billed_but_not_earned',
            'customer_advances',
            'progress_billing_received',
            'mobilization_advances_received',
            'milestone_advances_received',
        ],
        'costs_to_obtain_fulfill_contracts': [
            'costs_to_obtain_contract',
            'incremental_costs_of_obtaining_contract',
            'sales_commission_capitalized',
            'contract_acquisition_costs',
            'costs_to_fulfill_contract',
            'setup_costs',
            'design_costs',
            'direct_labor_costs',
            'direct_material_costs',
            'allocated_overheads',
            'transition_costs',
            'transformation_costs',
        ],
    },
}

# =============================================================================
# SECTION 23: SHARE CAPITAL NOTES
# =============================================================================

SHARE_CAPITAL_NOTES = {
    'authorized_share_capital': {
        'equity_shares': [
            'authorized_equity_share_capital',
            'authorized_equity_shares_number',
            'authorized_equity_shares_face_value',
            'increase_in_authorized_capital',
            'decrease_in_authorized_capital',
            'reclassification_of_authorized_capital',
        ],
        'preference_shares': [
            'authorized_preference_share_capital',
            'authorized_preference_shares_number',
            'authorized_preference_shares_face_value',
            'authorized_cumulative_preference_shares',
            'authorized_non_cumulative_preference_shares',
            'authorized_redeemable_preference_shares',
            'authorized_non_redeemable_preference_shares',
            'authorized_convertible_preference_shares',
            'authorized_non_convertible_preference_shares',
        ],
        'other_securities': [
            'authorized_other_securities',
            'authorized_deferred_shares',
            'authorized_stock',
            'authorized_unclassified_shares',
        ],
    },
    'issued_subscribed_paid_up': {
        'equity_shares': [
            'issued_equity_share_capital',
            'issued_equity_shares_number',
            'subscribed_equity_share_capital',
            'subscribed_equity_shares_number',
            'subscribed_and_fully_paid_up_equity_shares',
            'subscribed_and_fully_paid_up_equity_shares_number',
            'subscribed_but_not_fully_paid_up_equity_shares',
            'subscribed_but_not_fully_paid_up_equity_shares_number',
            'calls_unpaid',
            'calls_unpaid_by_directors',
            'calls_unpaid_by_officers',
            'calls_in_arrears',
            'calls_in_advance',
            'forfeited_shares',
            'forfeited_shares_reissued',
            'amount_originally_paid_up_on_forfeited_shares',
        ],
        'preference_shares': [
            'issued_preference_share_capital',
            'issued_preference_shares_number',
            'subscribed_preference_share_capital',
            'subscribed_preference_shares_number',
            'paid_up_preference_share_capital',
            'paid_up_preference_shares_number',
        ],
    },
    'share_capital_reconciliation': {
        'equity_shares_reconciliation': [
            'equity_shares_at_beginning_of_period_number',
            'equity_shares_at_beginning_of_period_amount',
            'equity_shares_issued_during_period_number',
            'equity_shares_issued_during_period_amount',
            'shares_issued_on_exercise_of_options',
            'shares_issued_on_conversion',
            'shares_issued_under_rights_issue',
            'shares_issued_under_preferential_allotment',
            'shares_issued_under_private_placement',
            'shares_issued_under_qip',
            'shares_issued_under_ipo',
            'shares_issued_under_fpo',
            'bonus_shares_issued',
            'shares_issued_on_amalgamation',
            'shares_issued_on_merger',
            'shares_issued_on_demerger',
            'shares_issued_for_consideration_other_than_cash',
            'shares_bought_back_number',
            'shares_bought_back_amount',
            'shares_reduced_on_capital_reduction',
            'shares_cancelled_on_restructuring',
            'shares_forfeited_during_period',
            'equity_shares_at_end_of_period_number',
            'equity_shares_at_end_of_period_amount',
        ],
        'preference_shares_reconciliation': [
            'preference_shares_at_beginning_of_period_number',
            'preference_shares_at_beginning_of_period_amount',
            'preference_shares_issued_during_period_number',
            'preference_shares_issued_during_period_amount',
            'preference_shares_redeemed_during_period_number',
            'preference_shares_redeemed_during_period_amount',
            'preference_shares_converted_during_period_number',
            'preference_shares_converted_during_period_amount',
            'preference_shares_at_end_of_period_number',
            'preference_shares_at_end_of_period_amount',
        ],
    },
    'shareholding_pattern': {
        'promoter_shareholding': [
            'shares_held_by_promoters',
            'shares_held_by_promoter_group',
            'percentage_held_by_promoters',
            'percentage_held_by_promoter_group',
            'change_in_promoter_shareholding_during_year',
            'percentage_change_in_promoter_shareholding',
            'promoter_shares_pledged',
            'promoter_shares_encumbered',
            'percentage_of_promoter_shares_pledged',
        ],
        'holding_company_shareholding': [
            'shares_held_by_holding_company',
            'shares_held_by_ultimate_holding_company',
            'percentage_held_by_holding_company',
            'percentage_held_by_ultimate_holding_company',
        ],
        'subsidiary_shareholding': [
            'shares_held_by_subsidiaries',
            'shares_held_by_subsidiaries_of_holding_company',
            'percentage_held_by_subsidiaries',
        ],
        'associate_shareholding': [
            'shares_held_by_associates',
            'shares_held_by_associates_of_holding_company',
            'percentage_held_by_associates',
        ],
        'institutional_shareholding': [
            'shares_held_by_mutual_funds',
            'shares_held_by_banks_and_fis',
            'shares_held_by_insurance_companies',
            'shares_held_by_pension_funds',
            'shares_held_by_provident_funds',
            'shares_held_by_fii',
            'shares_held_by_fpi',
            'shares_held_by_qdii',
            'shares_held_by_aif',
            'shares_held_by_sovereign_wealth_funds',
        ],
        'public_shareholding': [
            'shares_held_by_public',
            'shares_held_by_bodies_corporate',
            'shares_held_by_individuals',
            'shares_held_by_huf',
            'shares_held_by_nri',
            'shares_held_by_foreign_nationals',
            'shares_held_by_trusts',
            'shares_held_by_clearing_members',
            'shares_held_by_iepf',
        ],
    },
    'shareholders_information': {
        'shareholders_holding_more_than_5_percent': [
            'name_of_shareholder',
            'number_of_shares_held',
            'percentage_of_shareholding',
            'change_in_shareholding_during_year',
        ],
        'shares_issued_for_different_purposes': [
            'shares_allotted_as_fully_paid_up_bonus_shares',
            'shares_allotted_as_fully_paid_up_pursuant_to_contracts',
            'shares_allotted_for_consideration_other_than_cash',
            'shares_bought_back_during_5_years',
            'shares_issued_under_esop_during_5_years',
            'shares_issued_under_sweat_equity_during_5_years',
        ],
    },
    'rights_and_restrictions': {
        'equity_shares_rights': [
            'voting_rights_per_equity_share',
            'dividend_rights_of_equity_shares',
            'rights_in_surplus_on_liquidation',
            'restrictions_on_distribution_of_dividends',
            'restrictions_on_repayment_of_capital',
            'differential_voting_rights',
            'differential_dividend_rights',
        ],
        'preference_shares_rights': [
            'dividend_rate_on_preference_shares',
            'voting_rights_of_preference_shares',
            'redemption_terms',
            'conversion_terms',
            'participation_rights',
            'cumulative_dividend_rights',
            'arrears_of_preference_dividend',
        ],
    },
    'capital_management': [
        'capital_management_objectives',
        'capital_management_policies',
        'debt_to_equity_ratio',
        'gearing_ratio',
        'capital_adequacy_ratio',
        'externally_imposed_capital_requirements',
        'compliance_with_capital_requirements',
        'changes_in_capital_management',
    ],
}

# =============================================================================
# SECTION 24: OTHER EQUITY / RESERVES NOTES
# =============================================================================

OTHER_EQUITY_RESERVES_NOTES = {
    'capital_reserves': {
        'capital_reserve': [
            'capital_reserve_opening_balance',
            'capital_reserve_on_consolidation',
            'capital_reserve_on_business_combination',
            'capital_reserve_on_amalgamation',
            'capital_reserve_on_merger',
            'capital_reserve_on_absorption',
            'capital_reserve_on_forfeiture_of_shares',
            'capital_reserve_on_reissue_of_forfeited_shares',
            'capital_reserve_on_extinguishment_of_liabilities',
            'capital_reserve_on_settlement_of_debt',
            'gain_on_bargain_purchase',
            'additions_to_capital_reserve',
            'utilization_of_capital_reserve',
            'transfer_from_capital_reserve',
            'capital_reserve_closing_balance',
        ],
        'capital_reserve_nature_and_purpose': [
            'nature_of_capital_reserve',
            'purpose_of_capital_reserve',
            'restrictions_on_capital_reserve',
            'capital_reserve_not_available_for_distribution',
        ],
    },
    'securities_premium': {
        'securities_premium_movements': [
            'securities_premium_opening_balance',
            'premium_on_issue_of_equity_shares',
            'premium_on_issue_of_preference_shares',
            'premium_on_exercise_of_esop',
            'premium_on_exercise_of_warrants',
            'premium_on_conversion_of_debentures',
            'premium_on_conversion_of_loans',
            'premium_on_qip',
            'premium_on_preferential_allotment',
            'premium_on_rights_issue',
            'premium_on_ipo',
            'premium_on_fpo',
            'utilization_of_securities_premium',
            'share_issue_expenses',
            'debenture_issue_expenses',
            'premium_on_buyback_of_shares',
            'premium_payable_on_redemption_of_debentures',
            'premium_payable_on_redemption_of_preference_shares',
            'writing_off_preliminary_expenses',
            'writing_off_discount_on_issue_of_shares',
            'writing_off_commission_on_issue_of_shares',
            'bonus_shares_issued_from_securities_premium',
            'securities_premium_closing_balance',
        ],
        'securities_premium_utilization_permitted': [
            'issue_of_fully_paid_bonus_shares',
            'writing_off_preliminary_expenses',
            'writing_off_expenses_of_issue_of_shares',
            'writing_off_commission_paid_on_shares',
            'writing_off_discount_on_shares',
            'providing_premium_on_redemption',
            'purchase_of_own_shares',
            'buyback_of_shares',
        ],
    },
    'general_reserve': {
        'general_reserve_movements': [
            'general_reserve_opening_balance',
            'transfer_from_retained_earnings',
            'transfer_from_surplus',
            'transfer_from_statement_of_profit_and_loss',
            'transfer_from_debenture_redemption_reserve',
            'transfer_from_other_reserves',
            'utilization_of_general_reserve',
            'transfer_to_retained_earnings',
            'bonus_issue_from_general_reserve',
            'general_reserve_closing_balance',
        ],
        'general_reserve_nature_and_purpose': [
            'nature_of_general_reserve',
            'purpose_of_general_reserve',
            'free_reserve',
            'distributable_reserve',
        ],
    },
    'retained_earnings': {
        'retained_earnings_movements': [
            'retained_earnings_opening_balance',
            'surplus_opening_balance',
            'profit_for_the_year',
            'loss_for_the_year',
            'remeasurement_of_defined_benefit_plans',
            'actuarial_gains_transferred',
            'actuarial_losses_transferred',
            'fair_value_changes_on_equity_instruments_transferred',
            'items_transferred_from_oci',
            'transfer_to_general_reserve',
            'transfer_to_capital_redemption_reserve',
            'transfer_to_debenture_redemption_reserve',
            'transfer_to_statutory_reserve',
            'transfer_to_special_reserve',
            'transfer_from_other_reserves',
            'dividend_on_equity_shares',
            'interim_dividend',
            'final_dividend',
            'dividend_on_preference_shares',
            'dividend_distribution_tax',
            'tax_on_dividend',
            'buyback_of_equity_shares',
            'premium_paid_on_buyback',
            'transaction_costs_on_equity_transactions',
            'share_based_payment_credited',
            'share_based_payment_debited',
            'adjustment_for_change_in_accounting_policy',
            'adjustment_for_prior_period_errors',
            'ind_as_transition_adjustments',
            'opening_balance_adjustments',
            'effect_of_change_in_subsidiary',
            'effect_of_business_combination',
            'retained_earnings_closing_balance',
            'surplus_closing_balance',
        ],
    },
    'statutory_and_special_reserves': {
        'capital_redemption_reserve': [
            'capital_redemption_reserve_opening',
            'transfer_on_buyback_of_shares',
            'transfer_on_redemption_of_preference_shares',
            'utilization_of_capital_redemption_reserve',
            'capital_redemption_reserve_closing',
        ],
        'debenture_redemption_reserve': [
            'debenture_redemption_reserve_opening',
            'transfer_to_drr',
            'drr_created_during_year',
            'transfer_from_drr',
            'drr_utilized_on_redemption',
            'debenture_redemption_reserve_closing',
        ],
        'special_reserve_rbi': [
            'special_reserve_under_section_45ic_of_rbi_act',
            'special_reserve_under_section_45ic_opening',
            'transfer_to_special_reserve_under_45ic',
            'special_reserve_under_section_45ic_closing',
        ],
        'special_reserve_income_tax': [
            'special_reserve_under_section_36_1_viii',
            'special_reserve_under_section_36_1_viii_opening',
            'transfer_to_special_reserve_under_36_1_viii',
            'special_reserve_under_section_36_1_viii_closing',
        ],
        'statutory_reserve': [
            'statutory_reserve_opening',
            'transfer_to_statutory_reserve',
            'statutory_reserve_closing',
        ],
        'investment_fluctuation_reserve': [
            'investment_fluctuation_reserve_opening',
            'transfer_to_investment_fluctuation_reserve',
            'transfer_from_investment_fluctuation_reserve',
            'investment_fluctuation_reserve_closing',
        ],
        'other_special_reserves': [
            'tonnage_tax_reserve',
            'shipping_business_reserve',
            'tea_development_reserve',
            'coffee_development_reserve',
            'rubber_development_reserve',
            'site_restoration_reserve',
            'amalgamation_reserve',
            'investment_allowance_reserve',
        ],
    },
    'share_based_payment_reserves': {
        'employee_stock_options': [
            'share_options_outstanding_account_opening',
            'employee_stock_option_reserve_opening',
            'esop_reserve_opening',
            'expense_recognized_during_period',
            'options_granted_during_period',
            'options_vested_during_period',
            'options_exercised_during_period',
            'transfer_to_securities_premium_on_exercise',
            'options_lapsed_during_period',
            'options_forfeited_during_period',
            'options_cancelled_during_period',
            'transfer_to_retained_earnings_on_lapse',
            'share_options_outstanding_account_closing',
            'employee_stock_option_reserve_closing',
            'esop_reserve_closing',
        ],
        'stock_appreciation_rights': [
            'sar_reserve_opening',
            'sar_expense_recognized',
            'sar_exercised',
            'sar_lapsed',
            'sar_reserve_closing',
        ],
        'restricted_stock_units': [
            'rsu_reserve_opening',
            'rsu_expense_recognized',
            'rsu_vested',
            'rsu_lapsed',
            'rsu_reserve_closing',
        ],
    },
    'oci_reserves': {
        'fvoci_equity_reserve': [
            'fvoci_equity_reserve_opening',
            'fair_value_gain_on_equity_instruments',
            'fair_value_loss_on_equity_instruments',
            'transfer_to_retained_earnings_on_disposal',
            'deferred_tax_on_fair_value_changes',
            'fvoci_equity_reserve_closing',
        ],
        'fvoci_debt_reserve': [
            'fvoci_debt_reserve_opening',
            'fair_value_gain_on_debt_instruments',
            'fair_value_loss_on_debt_instruments',
            'reclassified_to_profit_or_loss',
            'impairment_loss_recognized',
            'deferred_tax_on_fair_value_changes',
            'fvoci_debt_reserve_closing',
        ],
        'cash_flow_hedge_reserve': [
            'cash_flow_hedge_reserve_opening',
            'effective_portion_of_hedges',
            'hedging_gains_during_period',
            'hedging_losses_during_period',
            'reclassified_to_profit_or_loss',
            'reclassified_to_inventory',
            'reclassified_to_ppe',
            'deferred_tax_on_hedges',
            'cash_flow_hedge_reserve_closing',
        ],
        'cost_of_hedging_reserve': [
            'cost_of_hedging_reserve_opening',
            'changes_in_time_value_of_options',
            'changes_in_forward_element',
            'changes_in_foreign_currency_basis_spread',
            'amortization_to_profit_or_loss',
            'cost_of_hedging_reserve_closing',
        ],
        'foreign_currency_translation_reserve': [
            'fctr_opening',
            'exchange_differences_during_period',
            'exchange_differences_on_translation_of_foreign_operations',
            'reclassified_on_disposal_of_foreign_operation',
            'fctr_closing',
        ],
        'revaluation_surplus': [
            'revaluation_surplus_opening',
            'revaluation_gain_during_period',
            'revaluation_loss_during_period',
            'transfer_to_retained_earnings_on_use',
            'transfer_to_retained_earnings_on_disposal',
            'deferred_tax_on_revaluation',
            'revaluation_surplus_closing',
        ],
        'actuarial_reserve': [
            'actuarial_reserve_opening',
            'remeasurement_gains',
            'remeasurement_losses',
            'return_on_plan_assets_excluding_interest',
            'effect_of_asset_ceiling',
            'deferred_tax_on_remeasurement',
            'transfer_to_retained_earnings',
            'actuarial_reserve_closing',
        ],
    },
    'money_received_against_warrants': [
        'money_received_against_share_warrants_opening',
        'share_warrants_issued',
        'money_received_on_issue_of_warrants',
        'warrants_converted_to_shares',
        'transfer_to_share_capital',
        'transfer_to_securities_premium',
        'warrants_lapsed',
        'money_forfeited_on_lapse',
        'money_received_against_share_warrants_closing',
    ],
    'equity_component_of_compound_instruments': [
        'equity_component_opening',
        'equity_component_on_issue_of_convertible_instruments',
        'transfer_to_share_capital_on_conversion',
        'transfer_to_securities_premium_on_conversion',
        'transfer_to_retained_earnings_on_redemption',
        'equity_component_closing',
    ],
}
