
# =============================================================================
# SECTION 25: BORROWINGS NOTES
# =============================================================================

BORROWINGS_NOTES = {
    'non_current_borrowings': {
        'term_loans_from_banks': {
            'rupee_term_loans': [
                'rupee_term_loans_from_banks',
                'rupee_term_loans_secured',
                'rupee_term_loans_unsecured',
                'term_loans_from_scheduled_banks',
                'term_loans_from_public_sector_banks',
                'term_loans_from_private_sector_banks',
                'term_loans_from_foreign_banks',
                'term_loans_from_cooperative_banks',
                'term_loans_from_regional_rural_banks',
                'term_loans_from_small_finance_banks',
                'consortium_term_loans',
                'syndicated_term_loans',
                'multiple_banking_term_loans',
            ],
            'foreign_currency_term_loans': [
                'foreign_currency_term_loans_from_banks',
                'fcnr_loans',
                'foreign_currency_non_resident_loans',
                'pscfc_loans',
                'post_shipment_credit_in_foreign_currency',
                'pcfc_loans',
                'pre_shipment_credit_in_foreign_currency',
                'buyers_credit_from_banks',
                'suppliers_credit',
                'foreign_currency_loans_from_indian_banks',
                'foreign_currency_loans_from_foreign_banks',
            ],
            'external_commercial_borrowings': [
                'external_commercial_borrowings',
                'ecb',
                'ecb_from_foreign_banks',
                'ecb_from_international_banks',
                'ecb_from_multilateral_institutions',
                'ecb_from_export_credit_agencies',
                'ecb_from_foreign_equity_holders',
                'ecb_automatic_route',
                'ecb_approval_route',
                'trade_credit_ecb',
                'masala_bonds',
                'rupee_denominated_bonds_overseas',
            ],
        },
        'term_loans_from_financial_institutions': [
            'term_loans_from_financial_institutions',
            'term_loans_from_development_financial_institutions',
            'term_loans_from_sidbi',
            'term_loans_from_nabard',
            'term_loans_from_exim_bank',
            'term_loans_from_ndb',
            'term_loans_from_ifc',
            'term_loans_from_adb',
            'term_loans_from_aiib',
            'term_loans_from_housing_finance_companies',
            'term_loans_from_nbfc',
            'term_loans_from_infrastructure_finance_companies',
            'term_loans_from_aif',
        ],
        'term_loans_from_other_parties': [
            'term_loans_from_other_parties',
            'term_loans_from_body_corporates',
            'term_loans_from_trusts',
            'term_loans_from_llp',
            'term_loans_from_partnership_firms',
        ],
        'debentures': {
            'non_convertible_debentures': [
                'non_convertible_debentures',
                'ncd',
                'secured_non_convertible_debentures',
                'unsecured_non_convertible_debentures',
                'redeemable_non_convertible_debentures',
                'perpetual_non_convertible_debentures',
                'listed_non_convertible_debentures',
                'unlisted_non_convertible_debentures',
                'privately_placed_ncds',
                'publicly_issued_ncds',
                'rated_ncds',
                'unrated_ncds',
                'senior_ncds',
                'subordinated_ncds',
                'senior_secured_ncds',
                'senior_unsecured_ncds',
            ],
            'convertible_debentures': [
                'optionally_convertible_debentures',
                'ocd',
                'compulsorily_convertible_debentures',
                'ccd',
                'partially_convertible_debentures',
                'fully_convertible_debentures',
            ],
            'zero_coupon_debentures': [
                'zero_coupon_debentures',
                'deep_discount_debentures',
                'zero_coupon_convertible_debentures',
            ],
        },
        'bonds': {
            'secured_bonds': [
                'secured_bonds',
                'secured_redeemable_bonds',
                'infrastructure_bonds_secured',
                'mortgage_bonds',
                'asset_backed_bonds',
            ],
            'unsecured_bonds': [
                'unsecured_bonds',
                'unsecured_redeemable_bonds',
                'infrastructure_bonds_unsecured',
            ],
            'other_bonds': [
                'zero_coupon_bonds',
                'deep_discount_bonds',
                'perpetual_bonds',
                'at1_bonds',
                'additional_tier_1_bonds',
                'tier_2_bonds',
                'green_bonds',
                'sustainable_bonds',
                'social_bonds',
                'sustainability_linked_bonds',
                'taxable_bonds',
                'tax_free_bonds',
                'listed_bonds',
                'unlisted_bonds',
            ],
        },
        'loans_from_related_parties': [
            'loans_from_holding_company',
            'loans_from_ultimate_holding_company',
            'loans_from_subsidiaries',
            'loans_from_fellow_subsidiaries',
            'loans_from_associates',
            'loans_from_joint_ventures',
            'loans_from_enterprises_under_common_control',
            'loans_from_directors',
            'loans_from_relatives_of_directors',
            'loans_from_key_management_personnel',
            'loans_from_promoters',
            'loans_from_promoter_group',
        ],
        'inter_corporate_deposits': [
            'inter_corporate_deposits_received',
            'icd_received',
            'deposits_from_body_corporates',
            'deposits_from_companies',
        ],
        'public_deposits': [
            'public_deposits',
            'deposits_from_public',
            'deposits_from_shareholders',
            'deposits_from_members',
            'eligible_deposits',
            'exempted_deposits',
        ],
        'deferred_payment_liabilities': [
            'deferred_payment_liabilities',
            'deferred_payment_credits',
            'hire_purchase_liabilities',
            'deferred_credit_from_suppliers',
            'vendor_financing_liabilities',
        ],
        'finance_lease_obligations': [
            'finance_lease_obligations_non_current',
            'lease_liabilities_non_current',
            'obligations_under_finance_lease',
            'obligations_under_capital_lease',
            'hire_purchase_obligations',
            'right_of_use_lease_liabilities',
        ],
        'other_non_current_borrowings': [
            'other_long_term_borrowings',
            'subordinated_debt',
            'mezzanine_debt',
            'junior_debt',
            'senior_debt',
            'perpetual_debt',
            'preference_share_liability_component',
            'liability_component_of_compound_instruments',
            'optionally_convertible_preference_shares_liability',
            'vehicle_loans',
            'equipment_loans',
            'mortgage_loans',
            'project_loans',
            'bridge_loans_non_current',
        ],
    },
    'current_borrowings': {
        'loans_repayable_on_demand': {
            'cash_credit': [
                'cash_credit',
                'cash_credit_from_banks',
                'cash_credit_secured',
                'cash_credit_unsecured',
                'consortium_cash_credit',
                'multiple_banking_cash_credit',
            ],
            'overdraft': [
                'overdraft',
                'bank_overdraft',
                'overdraft_from_banks',
                'overdraft_secured',
                'overdraft_unsecured',
                'overdraft_against_fixed_deposits',
                'overdraft_against_securities',
                'book_overdraft',
            ],
            'working_capital_demand_loan': [
                'working_capital_demand_loan',
                'wcdl',
                'short_term_demand_loan',
                'demand_loan_from_banks',
            ],
        },
        'working_capital_loans': [
            'working_capital_loans',
            'working_capital_term_loan',
            'wctl',
            'funded_interest_term_loan',
            'fitl',
        ],
        'packing_credit': [
            'packing_credit',
            'pre_shipment_credit',
            'packing_credit_in_rupees',
            'packing_credit_in_foreign_currency',
            'pcfc',
            'running_account_packing_credit',
        ],
        'export_credit': [
            'export_credit',
            'post_shipment_credit',
            'post_shipment_credit_in_rupees',
            'post_shipment_credit_in_foreign_currency',
            'pscfc',
            'export_bills_purchased',
            'export_bills_discounted',
            'export_bills_negotiated',
        ],
        'bills_discounting': [
            'bills_discounted',
            'bills_purchased',
            'inland_bills_discounted',
            'foreign_bills_discounted',
            'lc_backed_bills_discounted',
            'clean_bills_discounted',
            'usance_bills_discounted',
            'demand_bills_discounted',
        ],
        'commercial_paper': [
            'commercial_paper',
            'cp',
            'commercial_paper_issued',
            'listed_commercial_paper',
            'unlisted_commercial_paper',
        ],
        'short_term_loans': [
            'short_term_loans_from_banks',
            'short_term_loans_from_financial_institutions',
            'short_term_loans_from_nbfc',
            'short_term_loans_from_related_parties',
            'short_term_loans_from_directors',
            'short_term_loans_from_body_corporates',
            'short_term_inter_corporate_deposits',
            'bridge_loans_current',
        ],
        'buyers_credit': [
            'buyers_credit',
            'buyers_credit_from_banks',
            'buyers_credit_from_overseas_suppliers',
            'suppliers_credit_short_term',
            'trade_credit',
            'usance_lc_payable',
        ],
        'current_maturities': [
            'current_maturities_of_long_term_borrowings',
            'current_maturities_of_long_term_debt',
            'current_maturities_of_term_loans',
            'current_maturities_of_debentures',
            'current_maturities_of_bonds',
            'current_maturities_of_finance_lease_obligations',
            'current_maturities_of_lease_liabilities',
            'current_portion_of_non_current_borrowings',
        ],
    },
    'borrowings_disclosures': {
        'security_details': [
            'nature_of_security',
            'assets_pledged_as_security',
            'first_charge_on_assets',
            'second_charge_on_assets',
            'pari_passu_charge',
            'exclusive_charge',
            'hypothecation_of_current_assets',
            'hypothecation_of_movable_assets',
            'mortgage_of_immovable_assets',
            'pledge_of_shares',
            'pledge_of_fixed_deposits',
            'corporate_guarantee',
            'personal_guarantee',
            'bank_guarantee',
            'letter_of_comfort',
            'negative_lien',
            'collateral_security',
        ],
        'terms_of_repayment': [
            'repayment_schedule',
            'repayment_terms',
            'installment_amount',
            'number_of_installments',
            'frequency_of_installments',
            'monthly_installments',
            'quarterly_installments',
            'half_yearly_installments',
            'annual_installments',
            'bullet_repayment',
            'balloon_payment',
            'moratorium_period',
            'grace_period',
            'prepayment_terms',
            'prepayment_penalty',
            'reset_date',
        ],
        'interest_rate': [
            'rate_of_interest',
            'fixed_interest_rate',
            'floating_interest_rate',
            'interest_rate_spread',
            'benchmark_rate',
            'mclr_linked',
            'repo_linked',
            'eblr_linked',
            'libor_linked',
            'sofr_linked',
            'effective_interest_rate',
            'interest_payment_frequency',
            'interest_reset_frequency',
        ],
        'maturity_profile': [
            'maturity_within_1_year',
            'maturity_1_to_2_years',
            'maturity_2_to_3_years',
            'maturity_3_to_5_years',
            'maturity_beyond_5_years',
            'weighted_average_maturity',
            'weighted_average_interest_rate',
        ],
        'covenants': [
            'financial_covenants',
            'debt_service_coverage_ratio',
            'dscr',
            'interest_coverage_ratio',
            'icr',
            'debt_equity_ratio',
            'current_ratio_covenant',
            'tangible_net_worth',
            'minimum_net_worth',
            'maximum_leverage',
            'asset_coverage_ratio',
            'loan_to_value_ratio',
            'non_financial_covenants',
            'negative_pledge',
            'pari_passu_clause',
            'cross_default_clause',
            'change_of_control_clause',
            'material_adverse_change_clause',
            'covenant_compliance',
            'covenant_breach',
            'waiver_of_covenant',
        ],
        'defaults': [
            'default_in_repayment_of_principal',
            'default_in_payment_of_interest',
            'period_of_default',
            'amount_of_default',
            'continuing_default',
            'default_rectified',
            'lender_wise_default_details',
        ],
        'utilization': [
            'end_use_of_borrowings',
            'purpose_of_borrowing',
            'utilization_of_borrowings',
            'borrowings_for_capital_expenditure',
            'borrowings_for_working_capital',
            'borrowings_for_acquisition',
            'borrowings_for_refinancing',
            'borrowings_for_general_corporate_purposes',
        ],
        'quarterly_returns': [
            'quarterly_returns_filed_with_banks',
            'stock_statement',
            'book_debt_statement',
            'monthly_stock_statement',
            'quarterly_information_statement',
            'discrepancy_in_returns',
            'variation_from_books',
        ],
    },
    'lease_liabilities': {
        'lease_liabilities_non_current': [
            'lease_liabilities_non_current',
            'finance_lease_liabilities_non_current',
            'right_of_use_lease_liabilities_non_current',
            'lease_liabilities_for_land',
            'lease_liabilities_for_buildings',
            'lease_liabilities_for_plant_and_machinery',
            'lease_liabilities_for_vehicles',
            'lease_liabilities_for_office_equipment',
        ],
        'lease_liabilities_current': [
            'lease_liabilities_current',
            'finance_lease_liabilities_current',
            'current_maturities_of_lease_liabilities',
            'right_of_use_lease_liabilities_current',
        ],
        'lease_liabilities_reconciliation': [
            'lease_liabilities_opening_balance',
            'additions_to_lease_liabilities',
            'new_leases_entered',
            'lease_modifications',
            'interest_expense_on_lease_liabilities',
            'lease_payments_made',
            'principal_payments',
            'interest_payments_on_leases',
            'termination_of_leases',
            'early_termination_of_leases',
            'foreign_exchange_differences',
            'lease_liabilities_closing_balance',
        ],
        'maturity_analysis': [
            'lease_payments_within_1_year',
            'lease_payments_1_to_2_years',
            'lease_payments_2_to_3_years',
            'lease_payments_3_to_4_years',
            'lease_payments_4_to_5_years',
            'lease_payments_beyond_5_years',
            'total_undiscounted_lease_payments',
            'finance_charges_future',
            'present_value_of_lease_liabilities',
        ],
    },
}

# =============================================================================
# SECTION 26: TRADE PAYABLES NOTES
# =============================================================================

TRADE_PAYABLES_NOTES = {
    'trade_payables_categories': {
        'msme_payables': [
            'trade_payables_to_micro_enterprises',
            'trade_payables_to_small_enterprises',
            'trade_payables_to_msme',
            'dues_to_micro_enterprises',
            'dues_to_small_enterprises',
            'dues_to_medium_enterprises',
            'principal_amount_due_to_msme',
            'interest_due_to_msme',
            'interest_accrued_and_unpaid_to_msme',
            'interest_paid_to_msme',
            'payment_made_beyond_appointed_day',
            'interest_due_under_msmed_act',
            'interest_accrued_under_section_16_msmed_act',
            'interest_remaining_due_under_section_23_msmed_act',
        ],
        'other_than_msme': [
            'trade_payables_other_than_msme',
            'dues_to_other_creditors',
            'trade_payables_to_large_enterprises',
        ],
        'related_party_payables': [
            'trade_payables_to_related_parties',
            'payables_to_holding_company',
            'payables_to_subsidiaries',
            'payables_to_fellow_subsidiaries',
            'payables_to_associates',
            'payables_to_joint_ventures',
            'payables_to_key_management_personnel',
            'payables_to_directors',
            'payables_to_enterprises_over_which_kmp_have_influence',
        ],
    },
    'trade_payables_by_nature': [
        'creditors_for_goods',
        'creditors_for_raw_materials',
        'creditors_for_stores_and_spares',
        'creditors_for_packing_materials',
        'creditors_for_traded_goods',
        'creditors_for_services',
        'creditors_for_expenses',
        'creditors_for_job_work',
        'creditors_for_freight',
        'creditors_for_utilities',
        'creditors_for_rent',
        'creditors_for_professional_services',
        'creditors_for_capital_goods',
        'bills_payable',
        'acceptances',
        'usance_bills_payable',
        'demand_bills_payable',
        'lc_acceptances',
    ],
    'trade_payables_ageing': {
        'msme_undisputed': [
            'msme_undisputed_not_due',
            'msme_undisputed_less_than_1_year',
            'msme_undisputed_1_to_2_years',
            'msme_undisputed_2_to_3_years',
            'msme_undisputed_more_than_3_years',
        ],
        'msme_disputed': [
            'msme_disputed_not_due',
            'msme_disputed_less_than_1_year',
            'msme_disputed_1_to_2_years',
            'msme_disputed_2_to_3_years',
            'msme_disputed_more_than_3_years',
        ],
        'others_undisputed': [
            'others_undisputed_not_due',
            'others_undisputed_less_than_1_year',
            'others_undisputed_1_to_2_years',
            'others_undisputed_2_to_3_years',
            'others_undisputed_more_than_3_years',
        ],
        'others_disputed': [
            'others_disputed_not_due',
            'others_disputed_less_than_1_year',
            'others_disputed_1_to_2_years',
            'others_disputed_2_to_3_years',
            'others_disputed_more_than_3_years',
        ],
    },
    'unbilled_and_accrued': [
        'unbilled_payables',
        'accrued_expenses',
        'accrued_liabilities',
        'goods_received_not_billed',
        'services_received_not_billed',
        'grn_pending_invoice',
        'accrued_purchases',
        'provision_for_expenses',
    ],
    'trade_payables_disclosures': {
        'msmed_act_disclosures': [
            'principal_amount_remaining_unpaid_at_year_end',
            'interest_due_remaining_unpaid_at_year_end',
            'interest_paid_under_msmed_act',
            'interest_due_and_payable_for_delayed_payments',
            'interest_accrued_and_remaining_unpaid',
            'further_interest_remaining_due',
            'amount_of_payment_made_beyond_appointed_day',
            'number_of_suppliers_under_msmed_act',
            'identification_of_msme_suppliers',
        ],
        'payment_terms': [
            'normal_credit_period',
            'extended_credit_period',
            'early_payment_discount',
            'payment_beyond_credit_period',
        ],
        'foreign_currency_payables': [
            'trade_payables_in_foreign_currency',
            'usd_payables',
            'eur_payables',
            'gbp_payables',
            'jpy_payables',
            'other_currency_payables',
            'exchange_rate_used',
            'hedged_payables',
            'unhedged_payables',
        ],
    },
}

# =============================================================================
# SECTION 27: OTHER LIABILITIES NOTES
# =============================================================================

OTHER_LIABILITIES_NOTES = {
    'other_financial_liabilities_non_current': {
        'security_deposits': [
            'security_deposits_received_non_current',
            'dealer_deposits',
            'distributor_deposits',
            'customer_deposits_non_current',
            'franchise_deposits',
            'rental_deposits_received',
            'lease_deposits_received',
            'refundable_deposits_non_current',
        ],
        'retention_money': [
            'retention_money_non_current',
            'retention_payable_to_contractors',
            'performance_guarantee_retention',
            'defect_liability_retention',
        ],
        'derivatives': [
            'derivative_liabilities_non_current',
            'interest_rate_swaps_liability',
            'cross_currency_swaps_liability',
            'forward_contracts_liability_non_current',
            'options_liability_non_current',
            'embedded_derivatives_liability',
        ],
        'deferred_consideration': [
            'deferred_consideration_payable_non_current',
            'contingent_consideration_payable_non_current',
            'earnout_liability_non_current',
            'holdback_liability',
        ],
        'other_non_current_financial_liabilities': [
            'other_non_current_financial_liabilities',
            'financial_guarantee_contracts_liability',
            'liability_for_put_option',
            'liability_for_written_put_options_over_nci',
        ],
    },
    'other_financial_liabilities_current': {
        'current_maturities': [
            'current_maturities_of_long_term_debt',
            'current_maturities_of_term_loans',
            'current_maturities_of_debentures',
            'current_maturities_of_bonds',
            'current_maturities_of_lease_liabilities',
            'current_maturities_of_other_financial_liabilities',
        ],
        'interest_accrued': [
            'interest_accrued_but_not_due',
            'interest_accrued_and_due',
            'interest_accrued_on_borrowings',
            'interest_accrued_on_debentures',
            'interest_accrued_on_bonds',
            'interest_accrued_on_deposits',
            'interest_accrued_on_lease_liabilities',
        ],
        'unclaimed_and_unpaid': [
            'unpaid_dividends',
            'unclaimed_dividends',
            'unpaid_matured_deposits',
            'unpaid_matured_debentures',
            'fractional_entitlements',
            'unpaid_share_application_money',
            'amounts_payable_to_iepf',
        ],
        'share_application_money': [
            'share_application_money_received',
            'share_application_money_pending_allotment',
            'share_application_money_refundable',
            'application_money_received_for_allotment',
            'application_money_due_for_refund',
        ],
        'security_deposits_current': [
            'security_deposits_received_current',
            'customer_deposits_current',
            'earnest_money_deposits_received',
            'bid_deposits_received',
            'tender_deposits_received',
            'caution_deposits_received',
            'refundable_deposits_current',
        ],
        'creditors_for_capital_goods': [
            'creditors_for_capital_goods',
            'payables_for_capital_expenditure',
            'payables_for_property_plant_equipment',
            'payables_for_intangible_assets',
            'retention_for_capital_projects',
        ],
        'employee_related_payables': [
            'salaries_and_wages_payable',
            'salaries_payable',
            'wages_payable',
            'bonus_payable',
            'commission_payable_to_employees',
            'incentives_payable',
            'leave_encashment_payable',
            'gratuity_payable',
            'pension_payable',
            'superannuation_payable',
            'reimbursements_payable_to_employees',
            'expenses_payable_to_employees',
        ],
        'derivatives_current': [
            'derivative_liabilities_current',
            'forward_contracts_liability_current',
            'options_liability_current',
            'futures_liability',
            'commodity_derivatives_liability',
            'currency_derivatives_liability',
            'interest_rate_derivatives_liability',
            'mark_to_market_liability',
        ],
        'payables_to_related_parties': [
            'payables_to_related_parties',
            'amount_due_to_holding_company',
            'amount_due_to_subsidiaries',
            'amount_due_to_fellow_subsidiaries',
            'amount_due_to_associates',
            'amount_due_to_joint_ventures',
            'amount_due_to_directors',
            'amount_due_to_key_management_personnel',
            'directors_remuneration_payable',
            'sitting_fees_payable',
            'commission_payable_to_directors',
        ],
        'other_current_financial_liabilities': [
            'other_current_financial_liabilities',
            'book_overdraft',
            'cheques_issued_but_not_presented',
            'deferred_consideration_payable_current',
            'contingent_consideration_payable_current',
            'earnout_liability_current',
            'liability_for_expenses',
            'accrued_expenses',
            'sundry_creditors_for_expenses',
        ],
    },
    'other_non_current_liabilities': {
        'deferred_revenue': [
            'deferred_revenue_non_current',
            'unearned_revenue_non_current',
            'income_received_in_advance_non_current',
            'deferred_license_fees',
            'deferred_franchise_fees',
            'deferred_membership_fees',
            'deferred_subscription_revenue',
            'deferred_maintenance_revenue',
            'deferred_warranty_revenue',
            'deferred_extended_warranty_revenue',
        ],
        'contract_liabilities': [
            'contract_liabilities_non_current',
            'advances_from_customers_non_current',
            'customer_advances_non_current',
            'progress_billings_non_current',
            'milestone_advances_non_current',
        ],
        'government_grants': [
            'deferred_government_grants_non_current',
            'government_grants_deferred_income',
            'capital_grants_deferred',
            'revenue_grants_deferred_non_current',
            'subsidies_deferred_non_current',
            'incentives_deferred_non_current',
        ],
        'other_non_current_liabilities': [
            'other_non_current_liabilities',
            'deferred_lease_rent',
            'straight_line_rent_liability',
            'lease_equalization_liability',
            'deferred_credits',
        ],
    },
    'other_current_liabilities': {
        'advance_from_customers': [
            'advance_from_customers',
            'advances_received',
            'customer_advances',
            'advances_for_goods',
            'advances_for_services',
            'advances_for_contracts',
            'mobilization_advances_received',
            'running_account_advances_received',
            'progress_billing_received',
            'milestone_payments_received',
            'booking_advances',
            'token_money_received',
        ],
        'contract_liabilities_current': [
            'contract_liabilities_current',
            'deferred_revenue_current',
            'unearned_revenue_current',
            'income_received_in_advance',
            'billing_in_excess_of_revenue',
            'billed_in_advance',
        ],
        'statutory_dues': {
            'gst_payables': [
                'gst_payable',
                'cgst_payable',
                'sgst_payable',
                'igst_payable',
                'utgst_payable',
                'gst_cess_payable',
                'gst_tds_payable',
                'gst_tcs_payable',
                'reverse_charge_gst_payable',
            ],
            'income_tax_payables': [
                'tds_payable',
                'tax_deducted_at_source_payable',
                'tcs_payable',
                'tax_collected_at_source_payable',
                'advance_tax_payable',
                'self_assessment_tax_payable',
                'regular_assessment_tax_payable',
            ],
            'other_statutory_dues': [
                'provident_fund_payable',
                'pf_payable',
                'employees_provident_fund_payable',
                'employers_contribution_to_pf_payable',
                'esi_payable',
                'esic_payable',
                'employees_state_insurance_payable',
                'professional_tax_payable',
                'labour_welfare_fund_payable',
                'gratuity_fund_contribution_payable',
                'superannuation_fund_contribution_payable',
                'nps_contribution_payable',
            ],
            'other_taxes': [
                'customs_duty_payable',
                'excise_duty_payable',
                'service_tax_payable',
                'vat_payable',
                'sales_tax_payable',
                'cst_payable',
                'entry_tax_payable',
                'octroi_payable',
                'local_body_tax_payable',
                'cess_payable',
                'entertainment_tax_payable',
                'luxury_tax_payable',
                'property_tax_payable',
                'stamp_duty_payable',
                'royalty_payable_to_government',
            ],
        },
        'government_grants_current': [
            'deferred_government_grants_current',
            'government_grants_deferred_income_current',
            'capital_grants_amortized_current_portion',
            'revenue_grants_deferred_current',
        ],
        'other_current_liabilities': [
            'other_current_liabilities',
            'other_payables',
            'sundry_creditors_for_others',
            'refund_liabilities',
            'liability_for_sales_returns',
            'liability_for_rebates',
            'liability_for_discounts',
            'liability_for_incentives',
            'warranty_claims_liability',
        ],
    },
}

# =============================================================================
# SECTION 28: PROVISIONS NOTES
# =============================================================================

PROVISIONS_NOTES = {
    'provisions_for_employee_benefits': {
        'gratuity': [
            'provision_for_gratuity',
            'gratuity_liability',
            'gratuity_obligation',
            'present_value_of_gratuity_obligation',
            'funded_gratuity',
            'unfunded_gratuity',
            'gratuity_fund_status',
            'fair_value_of_gratuity_plan_assets',
            'net_gratuity_liability',
            'net_gratuity_asset',
            'gratuity_provision_non_current',
            'gratuity_provision_current',
        ],
        'leave_benefits': [
            'provision_for_leave_encashment',
            'provision_for_compensated_absences',
            'provision_for_earned_leave',
            'provision_for_privilege_leave',
            'provision_for_sick_leave',
            'provision_for_casual_leave',
            'leave_liability',
            'leave_obligation',
            'leave_provision_non_current',
            'leave_provision_current',
        ],
        'pension': [
            'provision_for_pension',
            'pension_liability',
            'pension_obligation',
            'defined_benefit_pension_obligation',
            'pension_fund_status',
            'fair_value_of_pension_plan_assets',
            'net_pension_liability',
            'net_pension_asset',
        ],
        'superannuation': [
            'provision_for_superannuation',
            'superannuation_liability',
            'superannuation_obligation',
        ],
        'other_employee_benefits': [
            'provision_for_long_service_awards',
            'provision_for_other_long_term_employee_benefits',
            'provision_for_post_retirement_medical_benefits',
            'provision_for_post_employment_benefits',
            'provision_for_bonus',
            'provision_for_performance_bonus',
            'provision_for_incentives',
            'provision_for_ex_gratia',
            'provision_for_termination_benefits',
            'provision_for_voluntary_retirement_scheme',
            'vrs_provision',
            'provision_for_retrenchment_compensation',
            'provision_for_severance_pay',
        ],
    },
    'other_provisions': {
        'provision_for_warranties': [
            'provision_for_warranties',
            'warranty_provision',
            'warranty_obligation',
            'provision_for_product_warranties',
            'provision_for_service_warranties',
            'extended_warranty_provision',
            'warranty_provision_non_current',
            'warranty_provision_current',
        ],
        'provision_for_onerous_contracts': [
            'provision_for_onerous_contracts',
            'onerous_contract_provision',
            'loss_making_contracts_provision',
            'provision_for_expected_losses_on_contracts',
        ],
        'provision_for_restructuring': [
            'provision_for_restructuring',
            'restructuring_provision',
            'provision_for_reorganization',
            'provision_for_employee_severance',
            'provision_for_plant_closure',
            'provision_for_facility_closure',
            'provision_for_relocation',
        ],
        'provision_for_decommissioning': [
            'provision_for_decommissioning',
            'decommissioning_provision',
            'provision_for_site_restoration',
            'site_restoration_provision',
            'provision_for_mine_closure',
            'mine_closure_provision',
            'asset_retirement_obligation',
            'aro_provision',
            'provision_for_environmental_restoration',
            'environmental_remediation_provision',
            'provision_for_dismantling',
            'provision_for_removal',
        ],
        'provision_for_litigations': [
            'provision_for_litigations',
            'litigation_provision',
            'provision_for_legal_claims',
            'provision_for_legal_cases',
            'provision_for_disputed_matters',
            'provision_for_arbitration',
            'provision_for_regulatory_matters',
            'provision_for_penalties',
            'provision_for_fines',
        ],
        'provision_for_tax': [
            'provision_for_tax_uncertainties',
            'provision_for_uncertain_tax_positions',
            'provision_for_tax_disputes',
            'provision_for_indirect_tax_disputes',
            'provision_for_gst_disputes',
            'provision_for_customs_disputes',
            'provision_for_excise_disputes',
            'provision_for_service_tax_disputes',
            'provision_for_income_tax_disputes',
            'provision_for_transfer_pricing_disputes',
        ],
        'provision_for_expected_credit_loss': [
            'provision_for_expected_credit_loss',
            'ecl_provision',
            'provision_for_doubtful_debts',
            'provision_for_bad_debts',
            'allowance_for_credit_losses',
            'loss_allowance',
            'impairment_allowance',
        ],
        'provision_for_csr': [
            'provision_for_csr_expenditure',
            'csr_provision',
            'unspent_csr_amount',
            'ongoing_project_csr_liability',
        ],
        'other_provisions': [
            'other_provisions',
            'provision_for_contingencies',
            'contingency_provision',
            'provision_for_sales_returns',
            'provision_for_refunds',
            'provision_for_rebates',
            'provision_for_discounts',
            'provision_for_slow_moving_inventory',
            'provision_for_obsolete_inventory',
            'provision_for_diminution_in_value_of_investments',
            'provision_for_impairment',
            'other_provisions_non_current',
            'other_provisions_current',
        ],
    },
    'provisions_movement': {
        'opening_balance': [
            'provision_at_beginning_of_period',
            'provision_opening_balance',
        ],
        'additions': [
            'provision_created_during_period',
            'provision_recognized_during_year',
            'additional_provision',
            'increase_in_provision',
        ],
        'utilizations': [
            'provision_utilized_during_period',
            'amounts_used_during_period',
            'amounts_paid_against_provision',
            'provision_drawn_down',
        ],
        'reversals': [
            'provision_reversed_during_period',
            'unused_amounts_reversed',
            'excess_provision_reversed',
            'provision_no_longer_required',
            'provision_written_back',
        ],
        'unwinding': [
            'unwinding_of_discount',
            'accretion_expense',
            'interest_on_provision',
            'effect_of_change_in_discount_rate',
        ],
        'other_adjustments': [
            'change_in_estimate',
            'effect_of_change_in_assumptions',
            'foreign_exchange_differences',
            'reclassifications',
            'acquired_in_business_combination',
            'disposed_in_business_combination',
        ],
        'closing_balance': [
            'provision_at_end_of_period',
            'provision_closing_balance',
        ],
    },
    'provisions_disclosures': {
        'nature_and_timing': [
            'nature_of_obligation',
            'expected_timing_of_outflows',
            'expected_timing_of_settlement',
            'uncertainty_about_timing',
            'uncertainty_about_amount',
        ],
        'assumptions_and_estimates': [
            'key_assumptions',
            'discount_rate_used',
            'inflation_rate_used',
            'expected_settlement_period',
            'probability_of_outflow',
            'best_estimate_of_expenditure',
            'range_of_outcomes',
        ],
        'reimbursement': [
            'expected_reimbursement',
            'reimbursement_asset_recognized',
            'insurance_recovery_expected',
            'indemnification_asset',
        ],
    },
    'defined_benefit_plans_disclosures': {
        'plan_characteristics': [
            'description_of_plan',
            'type_of_plan',
            'defined_benefit_plan',
            'funded_plan',
            'unfunded_plan',
            'regulatory_framework',
            'governance_of_plan',
            'responsibility_for_governance',
            'risks_associated_with_plan',
        ],
        'amounts_in_financial_statements': [
            'present_value_of_defined_benefit_obligation',
            'dbo_at_beginning_of_period',
            'current_service_cost',
            'past_service_cost',
            'interest_cost',
            'contributions_by_plan_participants',
            'remeasurements',
            'actuarial_gains',
            'actuarial_losses',
            'experience_adjustments',
            'changes_in_demographic_assumptions',
            'changes_in_financial_assumptions',
            'benefits_paid',
            'dbo_at_end_of_period',
            'fair_value_of_plan_assets_at_beginning',
            'interest_income_on_plan_assets',
            'return_on_plan_assets_excluding_interest',
            'contributions_by_employer',
            'contributions_by_employees',
            'benefits_paid_from_fund',
            'fair_value_of_plan_assets_at_end',
            'net_defined_benefit_liability',
            'net_defined_benefit_asset',
            'effect_of_asset_ceiling',
        ],
        'actuarial_assumptions': [
            'discount_rate',
            'salary_escalation_rate',
            'attrition_rate',
            'mortality_rate',
            'disability_rate',
            'retirement_age',
            'expected_return_on_plan_assets',
            'inflation_rate',
            'pension_increase_rate',
            'medical_cost_trend_rate',
        ],
        'sensitivity_analysis': [
            'sensitivity_to_discount_rate',
            'impact_of_increase_in_discount_rate',
            'impact_of_decrease_in_discount_rate',
            'sensitivity_to_salary_escalation',
            'impact_of_increase_in_salary_escalation',
            'impact_of_decrease_in_salary_escalation',
            'sensitivity_to_attrition_rate',
            'sensitivity_to_mortality_rate',
        ],
        'plan_assets': [
            'composition_of_plan_assets',
            'investment_in_equity_instruments',
            'investment_in_debt_instruments',
            'investment_in_government_securities',
            'investment_in_insurer_managed_funds',
            'investment_in_property',
            'investment_in_cash_and_cash_equivalents',
            'quoted_plan_assets',
            'unquoted_plan_assets',
            'asset_liability_matching_strategy',
        ],
        'expected_contributions_and_payments': [
            'expected_contributions_next_year',
            'expected_benefit_payments',
            'maturity_profile_of_obligation',
            'weighted_average_duration_of_obligation',
        ],
    },
}

# =============================================================================
# SECTION 29: CONTINGENT LIABILITIES AND COMMITMENTS
# =============================================================================

CONTINGENT_LIABILITIES_AND_COMMITMENTS = {
    'contingent_liabilities': {
        'claims_against_company': {
            'legal_claims': [
                'claims_against_company_not_acknowledged_as_debt',
                'legal_cases_pending',
                'litigation_pending',
                'suits_filed_against_company',
                'civil_suits_pending',
                'criminal_cases_pending',
                'consumer_cases_pending',
                'labour_cases_pending',
                'industrial_disputes_pending',
                'arbitration_cases_pending',
                'writ_petitions_pending',
                'appeals_pending',
                'cases_pending_before_supreme_court',
                'cases_pending_before_high_court',
                'cases_pending_before_tribunal',
                'cases_pending_before_lower_courts',
                'claims_by_customers',
                'claims_by_vendors',
                'claims_by_employees',
                'claims_by_ex_employees',
                'claims_by_third_parties',
                'product_liability_claims',
                'personal_injury_claims',
                'property_damage_claims',
                'intellectual_property_claims',
                'patent_infringement_claims',
                'trademark_infringement_claims',
                'copyright_infringement_claims',
                'breach_of_contract_claims',
                'negligence_claims',
                'defamation_claims',
                'environmental_claims',
                'class_action_suits',
            ],
            'regulatory_matters': [
                'regulatory_proceedings',
                'show_cause_notices',
                'demand_notices',
                'notices_from_regulatory_authorities',
                'sebi_proceedings',
                'rbi_proceedings',
                'competition_commission_proceedings',
                'cci_proceedings',
                'nclt_proceedings',
                'nclat_proceedings',
                'rera_proceedings',
                'environmental_regulatory_matters',
                'pollution_control_board_notices',
                'labour_department_notices',
                'factory_inspector_notices',
            ],
        },
        'tax_related': {
            'income_tax': [
                'income_tax_demands_disputed',
                'income_tax_matters_pending',
                'income_tax_appeals_pending',
                'income_tax_matters_under_appeal',
                'income_tax_demands_under_dispute',
                'transfer_pricing_adjustments_disputed',
                'disallowance_of_expenses_disputed',
                'addition_to_income_disputed',
                'mat_credit_disputed',
                'tds_demands_disputed',
                'demands_for_earlier_years',
                'penalties_disputed',
                'interest_demands_disputed',
                'reassessment_proceedings',
                'revision_proceedings',
                'rectification_proceedings',
            ],
            'indirect_tax': [
                'gst_demands_disputed',
                'gst_matters_pending',
                'gst_appeals_pending',
                'cgst_demands_disputed',
                'sgst_demands_disputed',
                'igst_demands_disputed',
                'input_credit_disputed',
                'classification_disputes',
                'valuation_disputes',
                'customs_duty_demands_disputed',
                'customs_matters_pending',
                'customs_appeals_pending',
                'anti_dumping_duty_disputed',
                'safeguard_duty_disputed',
                'countervailing_duty_disputed',
                'excise_duty_demands_disputed',
                'excise_matters_pending',
                'cenvat_credit_disputed',
                'service_tax_demands_disputed',
                'service_tax_matters_pending',
                'vat_demands_disputed',
                'vat_matters_pending',
                'sales_tax_demands_disputed',
                'cst_demands_disputed',
                'entry_tax_demands_disputed',
                'octroi_demands_disputed',
            ],
            'other_tax': [
                'property_tax_disputed',
                'stamp_duty_disputed',
                'cess_disputed',
                'royalty_demands_disputed',
            ],
        },
        'guarantees_given': {
            'bank_guarantees': [
                'bank_guarantees_given',
                'performance_bank_guarantees',
                'financial_bank_guarantees',
                'bid_bond_guarantees',
                'advance_payment_guarantees',
                'retention_money_guarantees',
                'customs_guarantees',
                'excise_guarantees',
                'gst_guarantees',
                'security_deposit_guarantees',
            ],
            'corporate_guarantees': [
                'corporate_guarantees_given',
                'corporate_guarantees_to_subsidiaries',
                'corporate_guarantees_to_associates',
                'corporate_guarantees_to_joint_ventures',
                'corporate_guarantees_to_related_parties',
                'corporate_guarantees_to_third_parties',
                'guarantees_for_loans_of_subsidiaries',
                'guarantees_for_borrowings_of_others',
            ],
            'personal_guarantees': [
                'personal_guarantees_given_by_directors',
                'personal_guarantees_given_by_promoters',
            ],
            'other_guarantees': [
                'financial_guarantees',
                'letters_of_comfort',
                'letters_of_support',
                'keep_well_agreements',
                'indemnities_given',
                'counter_guarantees',
                'standby_letters_of_credit',
            ],
        },
        'bills_discounted': [
            'bills_discounted_with_banks',
            'bills_discounted_not_matured',
            'receivables_discounted',
            'receivables_factored_with_recourse',
            'export_bills_discounted',
            'inland_bills_discounted',
            'lc_backed_bills_discounted',
        ],
        'letter_of_credit': [
            'letters_of_credit_outstanding',
            'import_letters_of_credit',
            'inland_letters_of_credit',
            'usance_letters_of_credit',
            'sight_letters_of_credit',
            'deferred_payment_letters_of_credit',
            'standby_letters_of_credit',
        ],
        'other_contingent_liabilities': [
            'other_money_for_which_company_is_contingently_liable',
            'disputed_statutory_dues',
            'disputed_claims_by_government',
            'claims_by_suppliers',
            'claims_under_contracts',
            'warranty_claims_contingent',
            'insurance_claims_disputed',
            'pending_litigations',
            'environmental_liabilities_contingent',
            'obligations_under_joint_development_agreements',
            'put_options_held_by_minority',
            'derivative_contracts_contingent',
        ],
    },
    'commitments': {
        'capital_commitments': [
            'capital_commitments',
            'estimated_amount_of_contracts_remaining_to_be_executed',
            'contracts_for_capital_expenditure',
            'capital_commitments_for_property_plant_equipment',
            'capital_commitments_for_intangible_assets',
            'capital_commitments_for_investment_property',
            'capital_commitments_for_right_of_use_assets',
            'capital_commitments_net_of_advances',
            'authorized_by_board_but_not_contracted',
            'contracted_but_not_provided',
            'commitments_for_acquisition_of_subsidiaries',
            'commitments_for_acquisition_of_businesses',
            'joint_venture_capital_commitments',
        ],
        'investment_commitments': [
            'investment_commitments',
            'commitments_to_subscribe_to_shares',
            'commitments_to_invest_in_subsidiaries',
            'commitments_to_invest_in_associates',
            'commitments_to_invest_in_joint_ventures',
            'commitments_to_invest_in_funds',
            'uncalled_liability_on_partly_paid_shares',
            'uncalled_capital_commitments',
        ],
        'lease_commitments': {
            'operating_lease_commitments': [
                'operating_lease_commitments',
                'future_minimum_lease_payments_under_operating_leases',
                'operating_lease_commitments_within_one_year',
                'operating_lease_commitments_one_to_five_years',
                'operating_lease_commitments_beyond_five_years',
                'non_cancellable_operating_lease_commitments',
                'short_term_lease_commitments',
                'low_value_asset_lease_commitments',
                'variable_lease_payments_not_in_liability',
            ],
            'finance_lease_commitments': [
                'finance_lease_commitments',
                'future_minimum_lease_payments_under_finance_leases',
                'finance_lease_commitments_within_one_year',
                'finance_lease_commitments_one_to_five_years',
                'finance_lease_commitments_beyond_five_years',
            ],
        },
        'purchase_commitments': [
            'non_cancellable_purchase_commitments',
            'long_term_purchase_contracts',
            'take_or_pay_contracts',
            'power_purchase_agreements',
            'gas_supply_agreements',
            'raw_material_purchase_contracts',
            'commodity_purchase_commitments',
            'forward_contracts_for_purchases',
            'import_commitments',
            'export_obligations',
            'export_obligations_under_epcg',
            'export_obligations_under_advance_license',
        ],
        'other_commitments': [
            'other_commitments',
            'commitments_under_joint_venture_agreements',
            'commitments_under_consortium_agreements',
            'commitments_under_shareholders_agreements',
            'funding_commitments',
            'loan_commitments_given',
            'underwriting_commitments',
            'commitments_to_provide_financial_support',
            'commitments_under_csr',
            'ongoing_project_csr_commitments',
            'commitments_under_voluntary_retirement_scheme',
            'commitments_for_social_obligations',
            'environmental_commitments',
            'contractual_commitments_for_repairs_and_maintenance',
        ],
    },
    'contingent_assets': [
        'contingent_assets',
        'claims_against_others',
        'insurance_claims_pending',
        'legal_claims_against_others',
        'tax_refunds_claimed',
        'gst_refund_claims',
        'customs_duty_refund_claims',
        'income_tax_refund_claims',
        'claims_for_damages',
        'claims_for_compensation',
        'arbitration_claims',
        'warranty_claims_on_suppliers',
        'reimbursement_claims',
        'government_grants_applied_for',
        'subsidies_claimed',
        'incentives_claimed',
    ],
    'disclosure_details': {
        'nature_of_contingency': [
            'nature_of_contingent_liability',
            'description_of_contingency',
            'basis_of_contingency',
        ],
        'estimates_and_uncertainties': [
            'estimate_of_financial_effect',
            'uncertainties_relating_to_amount',
            'uncertainties_relating_to_timing',
            'indication_of_uncertainties',
            'range_of_possible_outcomes',
            'best_estimate_of_amount',
        ],
        'possibility_of_reimbursement': [
            'possibility_of_reimbursement',
            'expected_recovery',
            'insurance_coverage',
            'indemnification_arrangements',
        ],
        'remote_contingencies': [
            'remote_contingent_liabilities',
            'contingencies_not_disclosed',
            'reason_for_non_disclosure',
        ],
    },
}

# =============================================================================
# SECTION 30: RELATED PARTY DISCLOSURES
# =============================================================================

RELATED_PARTY_DISCLOSURES = {
    'related_party_categories': {
        'parent_and_ultimate_parent': [
            'holding_company',
            'parent_company',
            'immediate_parent',
            'intermediate_parent',
            'ultimate_holding_company',
            'ultimate_parent_company',
            'ultimate_controlling_party',
        ],
        'subsidiaries': [
            'subsidiaries',
            'subsidiary_companies',
            'wholly_owned_subsidiaries',
            'majority_owned_subsidiaries',
            'step_down_subsidiaries',
            'indirect_subsidiaries',
            'indian_subsidiaries',
            'foreign_subsidiaries',
            'material_subsidiaries',
        ],
        'fellow_subsidiaries': [
            'fellow_subsidiaries',
            'fellow_subsidiary_companies',
            'entities_under_common_control',
        ],
        'associates': [
            'associates',
            'associate_companies',
            'entities_with_significant_influence',
        ],
        'joint_ventures': [
            'joint_ventures',
            'joint_venture_companies',
            'jointly_controlled_entities',
            'joint_operations',
        ],
        'key_management_personnel': [
            'key_management_personnel',
            'kmp',
            'key_managerial_personnel',
            'managing_director',
            'whole_time_director',
            'chief_executive_officer',
            'ceo',
            'chief_financial_officer',
            'cfo',
            'company_secretary',
            'cs',
            'manager',
            'executive_directors',
            'non_executive_directors',
            'independent_directors',
            'nominee_directors',
        ],
        'relatives_of_kmp': [
            'relatives_of_key_management_personnel',
            'relatives_of_directors',
            'spouse_of_director',
            'children_of_director',
            'parents_of_director',
            'siblings_of_director',
            'relatives_as_per_companies_act',
        ],
        'enterprises_influenced_by_kmp': [
            'enterprises_over_which_kmp_have_significant_influence',
            'enterprises_over_which_directors_have_significant_influence',
            'enterprises_owned_by_kmp',
            'enterprises_owned_by_relatives_of_kmp',
            'enterprises_in_which_kmp_are_interested',
            'entities_controlled_by_kmp',
            'entities_jointly_controlled_by_kmp',
        ],
        'post_employment_benefit_plans': [
            'post_employment_benefit_plans',
            'employee_benefit_trusts',
            'gratuity_trust',
            'superannuation_trust',
            'provident_fund_trust',
            'esop_trust',
            'employee_welfare_trust',
        ],
        'promoters_and_promoter_group': [
            'promoters',
            'promoter_group',
            'promoter_companies',
            'persons_acting_in_concert',
        ],
    },
    'related_party_transactions': {
        'sale_transactions': [
            'sale_of_goods_to_related_parties',
            'sale_of_products_to_holding_company',
            'sale_of_products_to_subsidiaries',
            'sale_of_products_to_associates',
            'sale_of_products_to_joint_ventures',
            'sale_of_products_to_fellow_subsidiaries',
            'sale_of_products_to_entities_influenced_by_kmp',
            'sale_of_services_to_related_parties',
            'rendering_of_services_to_related_parties',
            'sale_of_fixed_assets_to_related_parties',
            'sale_of_investments_to_related_parties',
        ],
        'purchase_transactions': [
            'purchase_of_goods_from_related_parties',
            'purchase_of_products_from_holding_company',
            'purchase_of_products_from_subsidiaries',
            'purchase_of_products_from_associates',
            'purchase_of_products_from_joint_ventures',
            'purchase_of_products_from_fellow_subsidiaries',
            'purchase_of_products_from_entities_influenced_by_kmp',
            'receiving_of_services_from_related_parties',
            'purchase_of_services_from_related_parties',
            'purchase_of_fixed_assets_from_related_parties',
            'purchase_of_investments_from_related_parties',
        ],
        'finance_transactions': {
            'loans_and_advances': [
                'loans_given_to_related_parties',
                'loans_given_to_subsidiaries',
                'loans_given_to_associates',
                'loans_given_to_joint_ventures',
                'loans_given_to_directors',
                'loans_given_to_kmp',
                'inter_corporate_deposits_given',
                'advances_given_to_related_parties',
                'loans_received_from_related_parties',
                'loans_received_from_holding_company',
                'loans_received_from_subsidiaries',
                'loans_received_from_directors',
                'loans_received_from_promoters',
                'inter_corporate_deposits_received',
                'loans_repaid_to_related_parties',
                'loans_recovered_from_related_parties',
            ],
            'investments': [
                'investments_in_related_parties',
                'investment_in_equity_of_subsidiaries',
                'investment_in_equity_of_associates',
                'investment_in_equity_of_joint_ventures',
                'investment_in_preference_shares_of_related_parties',
                'investment_in_debentures_of_related_parties',
                'capital_contribution_in_related_parties',
            ],
            'guarantees_and_collaterals': [
                'guarantees_given_for_related_parties',
                'corporate_guarantees_given_for_subsidiaries',
                'corporate_guarantees_given_for_associates',
                'corporate_guarantees_given_for_joint_ventures',
                'collateral_provided_for_related_parties',
                'guarantees_received_from_related_parties',
                'personal_guarantees_received_from_directors',
                'personal_guarantees_received_from_promoters',
            ],
        },
        'income_transactions': [
            'interest_income_from_related_parties',
            'interest_received_from_subsidiaries',
            'interest_received_from_associates',
            'interest_received_from_joint_ventures',
            'dividend_income_from_related_parties',
            'dividend_received_from_subsidiaries',
            'dividend_received_from_associates',
            'dividend_received_from_joint_ventures',
            'royalty_income_from_related_parties',
            'technical_fees_received_from_related_parties',
            'management_fees_received_from_related_parties',
            'brand_usage_fees_received',
            'license_fees_received',
            'rent_received_from_related_parties',
            'commission_received_from_related_parties',
            'reimbursement_of_expenses_received',
        ],
        'expense_transactions': [
            'interest_expense_to_related_parties',
            'interest_paid_to_holding_company',
            'interest_paid_to_subsidiaries',
            'interest_paid_to_directors',
            'dividend_paid_to_related_parties',
            'royalty_paid_to_related_parties',
            'technical_fees_paid_to_related_parties',
            'management_fees_paid_to_related_parties',
            'brand_usage_fees_paid',
            'license_fees_paid',
            'rent_paid_to_related_parties',
            'commission_paid_to_related_parties',
            'reimbursement_of_expenses_paid',
            'professional_fees_paid_to_related_parties',
            'consultancy_fees_paid_to_related_parties',
        ],
        'kmp_remuneration': [
            'remuneration_to_key_management_personnel',
            'remuneration_to_managing_director',
            'remuneration_to_whole_time_directors',
            'remuneration_to_ceo',
            'remuneration_to_cfo',
            'remuneration_to_company_secretary',
            'short_term_employee_benefits_to_kmp',
            'salary_to_kmp',
            'allowances_to_kmp',
            'bonus_to_kmp',
            'commission_to_kmp',
            'perquisites_to_kmp',
            'post_employment_benefits_to_kmp',
            'gratuity_to_kmp',
            'pension_to_kmp',
            'superannuation_to_kmp',
            'other_long_term_benefits_to_kmp',
            'leave_encashment_to_kmp',
            'termination_benefits_to_kmp',
            'share_based_payments_to_kmp',
            'esop_to_kmp',
            'sitting_fees_to_directors',
            'sitting_fees_to_independent_directors',
            'commission_to_non_executive_directors',
            'directors_remuneration',
            'managerial_remuneration',
        ],
        'other_transactions': [
            'transfer_of_research_and_development',
            'transfer_of_technology',
            'transfer_of_license',
            'transfer_under_license_agreements',
            'transfer_under_finance_arrangements',
            'provision_of_guarantees_or_collateral',
            'settlement_of_liabilities_on_behalf',
            'expense_reimbursements',
            'cost_sharing_arrangements',
            'shared_services',
            'secondment_of_employees',
            'deputation_of_employees',
        ],
    },
    'outstanding_balances': {
        'receivables': [
            'receivables_from_related_parties',
            'trade_receivables_from_holding_company',
            'trade_receivables_from_subsidiaries',
            'trade_receivables_from_associates',
            'trade_receivables_from_joint_ventures',
            'trade_receivables_from_fellow_subsidiaries',
            'trade_receivables_from_kmp',
            'loans_receivable_from_related_parties',
            'loans_receivable_from_subsidiaries',
            'loans_receivable_from_associates',
            'loans_receivable_from_joint_ventures',
            'loans_receivable_from_directors',
            'interest_receivable_from_related_parties',
            'other_receivables_from_related_parties',
            'advances_to_related_parties',
        ],
        'payables': [
            'payables_to_related_parties',
            'trade_payables_to_holding_company',
            'trade_payables_to_subsidiaries',
            'trade_payables_to_associates',
            'trade_payables_to_joint_ventures',
            'trade_payables_to_fellow_subsidiaries',
            'trade_payables_to_kmp',
            'loans_payable_to_related_parties',
            'loans_payable_to_holding_company',
            'loans_payable_to_subsidiaries',
            'loans_payable_to_directors',
            'interest_payable_to_related_parties',
            'other_payables_to_related_parties',
            'advances_from_related_parties',
            'remuneration_payable_to_kmp',
            'sitting_fees_payable_to_directors',
        ],
        'investments_held': [
            'investments_in_related_parties_outstanding',
            'investment_in_subsidiaries_outstanding',
            'investment_in_associates_outstanding',
            'investment_in_joint_ventures_outstanding',
        ],
        'guarantees_outstanding': [
            'guarantees_given_for_related_parties_outstanding',
            'guarantees_received_from_related_parties_outstanding',
        ],
    },
    'disclosure_requirements': {
        'terms_and_conditions': [
            'terms_and_conditions_of_transactions',
            'pricing_policy',
            'arms_length_basis',
            'market_terms',
            'transfer_pricing_policy',
            'security_provided',
            'guarantees_provided',
        ],
        'provisions_and_write_offs': [
            'provision_for_doubtful_debts_from_related_parties',
            'bad_debts_written_off_from_related_parties',
            'provision_for_impairment_of_investment_in_related_parties',
        ],
        'approval_requirements': [
            'transactions_requiring_board_approval',
            'transactions_requiring_shareholders_approval',
            'transactions_requiring_audit_committee_approval',
            'material_related_party_transactions',
            'transactions_exceeding_threshold_limits',
        ],
    },
}

# =============================================================================
