
"""
Configuration for Ind AS (Indian Accounting Standards) specific structures and schedules.
Used by metrics_engine and validators to recognize and validate Indian filings.
"""

IND_AS_MANDATORY_SCHEDULES = {
    'balance_sheet_equity': [
        'share_capital', 'reserves_and_surplus', 'other_equity',
        'total_equity', 'equity_share_capital', 'preference_share_capital'
    ],
    'balance_sheet_liabilities': [
        'non_current_liabilities', 'current_liabilities',
        'long_term_borrowings', 'deferred_tax_liabilities_net',
        'short_term_borrowings', 'trade_payables', 'other_current_liabilities',
        'short_term_provisions', 'current_maturities_of_long_term_debt'
    ],
    'balance_sheet_assets': [
        'non_current_assets', 'current_assets',
        'property_plant_equipment', 'capital_work_in_progress',
        'goodwill', 'other_intangible_assets', 'investment_property',
        'non_current_investments', 'current_investments',
        'inventories', 'trade_receivables', 'cash_and_cash_equivalents'
    ],
    'statement_of_profit_loss': [
        'revenue_from_operations', 'other_income', 'total_revenue',
        'cost_of_materials_consumed', 'purchases_of_stock_in_trade',
        'changes_in_inventories', 'employee_benefit_expense',
        'finance_costs', 'depreciation_and_amortization',
        'other_expenses', 'total_expenses',
        'profit_before_exceptional_items', 'exceptional_items',
        'profit_before_tax', 'tax_expense', 'profit_for_the_period',
        'other_comprehensive_income', 'total_comprehensive_income'
    ],
    'cash_flow_indirect': [
        'profit_before_tax', 'adjustments_for',
        'depreciation_and_amortization', 'interest_expense',
        'interest_income', 'dividend_income', 'profit_before_working_capital_changes',
        'changes_in_working_capital', 'cash_generated_from_operations',
        'income_taxes_paid', 'net_cash_from_operating_activities',
        'net_cash_from_investing_activities', 'net_cash_from_financing_activities',
        'net_increase_decrease_in_cash', 'cash_at_beginning_of_period',
        'cash_at_end_of_period', 'effect_of_exchange_rate_changes'
    ]
}

"""
Comprehensive Ind AS / MCA Filing Configuration
Version: 2.0
Coverage: All Schedule III (Division I, II, III) line items
Applicable Standards: Ind AS 1, 2, 7, 10, 12, 16, 19, 20, 21, 23, 24, 27, 28, 32, 33, 
                      36, 37, 38, 40, 41, 102, 103, 104, 105, 106, 107, 108, 109, 
                      110, 111, 112, 113, 114, 115, 116, 117
Last Updated: 2025
"""

# =============================================================================
# SECTION 1: BALANCE SHEET - EQUITY SECTION
# =============================================================================

BALANCE_SHEET_EQUITY = {
    'share_capital': {
        'equity_share_capital': [
            'authorized_share_capital',
            'authorized_equity_shares_number',
            'authorized_equity_shares_face_value',
            'issued_share_capital',
            'issued_equity_shares_number',
            'subscribed_share_capital',
            'subscribed_equity_shares_number',
            'subscribed_and_fully_paid_up',
            'subscribed_and_fully_paid_up_shares_number',
            'subscribed_but_not_fully_paid_up',
            'subscribed_but_not_fully_paid_up_shares_number',
            'calls_unpaid',
            'forfeited_shares',
            'forfeited_shares_amount_originally_paid_up',
            'par_value_per_share',
            'shares_held_by_holding_company',
            'shares_held_by_ultimate_holding_company',
            'shares_held_by_subsidiaries_of_holding_company',
            'shares_held_by_associates_of_holding_company',
            'shares_held_by_promoters',
            'shares_held_by_promoter_group',
            'percentage_held_by_promoters',
            'change_in_promoter_shareholding_during_year',
            'shares_reserved_for_issue_under_options',
            'shares_reserved_for_issue_under_contracts',
            'buyback_of_shares',
            'bonus_shares_issued',
            'shares_issued_for_consideration_other_than_cash',
            'shares_issued_without_payment_received_in_cash',
            'rights_preferences_restrictions_on_shares',
            'shares_allotted_as_fully_paid_up_bonus',
            'shares_allotted_as_fully_paid_up_pursuant_to_contracts',
            'shares_bought_back_during_period',
            'equity_shares_with_differential_voting_rights',
            'equity_shares_with_differential_dividend_rights',
            'sweat_equity_shares',
            'shares_outstanding_at_beginning_of_period',
            'shares_issued_during_period',
            'shares_outstanding_at_end_of_period',
        ],
        'preference_share_capital': [
            'authorized_preference_share_capital',
            'authorized_preference_shares_number',
            'issued_preference_share_capital',
            'issued_preference_shares_number',
            'subscribed_preference_share_capital',
            'subscribed_preference_shares_number',
            'redeemable_preference_shares',
            'non_redeemable_preference_shares',
            'cumulative_preference_shares',
            'non_cumulative_preference_shares',
            'convertible_preference_shares',
            'non_convertible_preference_shares',
            'participating_preference_shares',
            'non_participating_preference_shares',
            'preference_shares_redemption_date',
            'preference_shares_dividend_rate',
            'preference_dividend_arrears',
            'preference_shares_with_differential_rights',
        ],
        'share_capital_reconciliation': [
            'opening_balance_shares_number',
            'opening_balance_shares_amount',
            'shares_issued_during_year_number',
            'shares_issued_during_year_amount',
            'shares_bought_back_number',
            'shares_bought_back_amount',
            'shares_converted_number',
            'shares_converted_amount',
            'closing_balance_shares_number',
            'closing_balance_shares_amount',
        ],
    },
    'other_equity': [
        # Capital Reserves
        'capital_reserve',
        'capital_reserve_on_consolidation',
        'capital_reserve_on_merger_amalgamation',
        'capital_reserve_on_forfeiture_of_shares',
        'capital_reserve_on_reissue_of_forfeited_shares',
        
        # Securities Premium
        'securities_premium',
        'securities_premium_reserve',
        'securities_premium_account',
        
        # Other Reserves
        'general_reserve',
        'retained_earnings',
        'surplus_in_statement_of_profit_and_loss',
        'debenture_redemption_reserve',
        'capital_redemption_reserve',
        'share_options_outstanding_account',
        'employee_stock_options_outstanding',
        'money_received_against_share_warrants',
        
        # Revaluation Reserves
        'revaluation_reserve',
        'revaluation_surplus',
        'equity_component_of_compound_financial_instruments',
        
        # Special Reserves
        'special_reserve_under_section_45ic_of_rbi_act',
        'special_reserve_under_section_36_1_viii_of_income_tax_act',
        'statutory_reserve',
        'investment_allowance_reserve',
        'investment_fluctuation_reserve',
        'tonnage_tax_reserve',
        'shipping_business_reserve',
        'tea_development_reserve',
        'coffee_development_reserve',
        'rubber_development_reserve',
        'amalgamation_reserve',
        'site_restoration_reserve',
        
        # Exchange Differences
        'foreign_currency_translation_reserve',
        'foreign_currency_monetary_item_translation_difference_account',
        'exchange_differences_on_translating_foreign_operations',
        
        # Hedge Reserves
        'cash_flow_hedge_reserve',
        'hedging_instruments_reserve',
        'effective_portion_of_cash_flow_hedges',
        'cost_of_hedging_reserve',
        
        # Fair Value Reserves
        'fair_value_through_oci_reserve',
        'fvoci_equity_instruments_reserve',
        'fvoci_debt_instruments_reserve',
        'fair_value_changes_of_financial_assets',
        
        # Actuarial Reserves
        'remeasurement_of_defined_benefit_plans',
        'actuarial_gains_losses_on_defined_benefit_obligations',
        
        # Other OCI Reserves
        'share_of_oci_of_associates_joint_ventures',
        'other_items_of_oci',
        
        # Equity Attributable
        'equity_attributable_to_owners_of_parent',
        'equity_attributable_to_non_controlling_interests',
        'non_controlling_interests',
        'minority_interest',
        
        # Total Equity
        'total_equity',
        'total_equity_and_liabilities',
    ],
}

# =============================================================================
# SECTION 2: BALANCE SHEET - NON-CURRENT LIABILITIES
# =============================================================================

BALANCE_SHEET_NON_CURRENT_LIABILITIES = {
    'financial_liabilities': {
        'borrowings': [
            'long_term_borrowings',
            'secured_loans',
            'unsecured_loans',
            'term_loans_from_banks',
            'term_loans_from_banks_secured',
            'term_loans_from_banks_unsecured',
            'term_loans_from_financial_institutions',
            'term_loans_from_other_parties',
            'rupee_term_loans',
            'foreign_currency_term_loans',
            'external_commercial_borrowings',
            'ecb_loans',
            'buyers_credit',
            'debentures',
            'non_convertible_debentures',
            'secured_non_convertible_debentures',
            'unsecured_non_convertible_debentures',
            'privately_placed_debentures',
            'publicly_issued_debentures',
            'redeemable_debentures',
            'irredeemable_debentures',
            'bonds',
            'secured_bonds',
            'unsecured_bonds',
            'zero_coupon_bonds',
            'infrastructure_bonds',
            'loans_from_related_parties',
            'inter_corporate_deposits',
            'loans_repayable_on_demand',
            'deposits',
            'public_deposits',
            'vehicle_loans',
            'equipment_loans',
            'working_capital_term_loans',
            'deferred_payment_liabilities',
            'finance_lease_obligations_non_current',
            'liability_component_of_compound_instruments',
            'subordinated_debt',
            'perpetual_debt',
            'non_current_maturities_of_finance_lease_obligations',
        ],
        'lease_liabilities': [
            'lease_liabilities_non_current',
            'finance_lease_liabilities_non_current',
            'operating_lease_liabilities_non_current',
            'right_of_use_asset_lease_liabilities',
        ],
        'other_financial_liabilities': [
            'other_non_current_financial_liabilities',
            'security_deposits_received',
            'retention_money',
            'derivative_financial_instruments_liability',
            'contingent_consideration_payable',
            'deferred_consideration_payable',
            'financial_guarantee_contracts_liability',
        ],
    },
    'provisions': [
        'provision_for_employee_benefits',
        'provision_for_gratuity',
        'provision_for_leave_encashment',
        'provision_for_pension',
        'provision_for_superannuation',
        'provision_for_compensated_absences',
        'provision_for_long_service_awards',
        'provision_for_other_post_employment_benefits',
        'provision_for_decommissioning_restoration',
        'asset_retirement_obligations',
        'site_restoration_provision',
        'mine_closure_provision',
        'provision_for_warranties',
        'provision_for_onerous_contracts',
        'provision_for_restructuring',
        'provision_for_litigations',
        'provision_for_tax_uncertainties',
        'other_non_current_provisions',
    ],
    'deferred_tax_liabilities': [
        'deferred_tax_liabilities_net',
        'deferred_tax_liabilities_gross',
        'deferred_tax_liability_on_ppe',
        'deferred_tax_liability_on_intangibles',
        'deferred_tax_liability_on_fair_value_changes',
        'deferred_tax_liability_on_undistributed_profits',
        'deferred_tax_liability_on_rou_assets',
        'mat_credit_entitlement_non_current',
    ],
    'other_non_current_liabilities': [
        'other_non_current_liabilities',
        'deferred_revenue_non_current',
        'contract_liabilities_non_current',
        'deferred_government_grants',
        'government_grants_deferred_income',
        'advance_from_customers_non_current',
        'income_received_in_advance_non_current',
        'deferred_lease_rent',
        'liability_for_leasehold_improvements',
    ],
    'regulatory_deferral_account_credit_balances': [
        'regulatory_deferral_account_credit_balances',
        'regulatory_liabilities',
    ],
}

# =============================================================================
# SECTION 3: BALANCE SHEET - CURRENT LIABILITIES
# =============================================================================

BALANCE_SHEET_CURRENT_LIABILITIES = {
    'financial_liabilities': {
        'borrowings': [
            'short_term_borrowings',
            'loans_repayable_on_demand',
            'cash_credit',
            'cash_credit_from_banks',
            'overdraft',
            'bank_overdraft',
            'overdraft_from_banks',
            'working_capital_loans',
            'working_capital_demand_loans',
            'packing_credit',
            'export_credit',
            'pre_shipment_credit',
            'post_shipment_credit',
            'bill_discounting',
            'bills_purchased',
            'buyers_credit_short_term',
            'commercial_paper',
            'short_term_loans_from_banks',
            'short_term_loans_from_financial_institutions',
            'short_term_loans_from_related_parties',
            'inter_corporate_borrowings',
            'loans_from_directors',
            'loans_from_promoters',
            'bridge_loans',
            'demand_loans',
            'current_maturities_of_long_term_borrowings',
            'current_maturities_of_long_term_debt',
            'current_maturities_of_debentures',
            'current_maturities_of_finance_lease_obligations',
            'current_portion_of_non_current_borrowings',
        ],
        'lease_liabilities': [
            'lease_liabilities_current',
            'finance_lease_liabilities_current',
            'current_maturities_of_lease_liabilities',
        ],
        'trade_payables': [
            'trade_payables',
            'sundry_creditors',
            'creditors_for_goods',
            'creditors_for_services',
            'creditors_for_expenses',
            'trade_payables_micro_small_enterprises',
            'trade_payables_msme',
            'trade_payables_other_than_msme',
            'trade_payables_to_related_parties',
            'bills_payable',
            'acceptances',
            'trade_payables_disputed',
            'trade_payables_disputed_msme',
            'trade_payables_disputed_others',
            'trade_payables_unbilled',
            'accrued_expenses',
            'trade_payables_outstanding_less_than_1_year',
            'trade_payables_outstanding_1_to_2_years',
            'trade_payables_outstanding_2_to_3_years',
            'trade_payables_outstanding_more_than_3_years',
        ],
        'other_financial_liabilities': [
            'other_current_financial_liabilities',
            'current_maturities_of_long_term_liabilities',
            'interest_accrued_but_not_due',
            'interest_accrued_and_due',
            'unpaid_dividends',
            'unclaimed_dividends',
            'unpaid_matured_deposits',
            'unpaid_matured_debentures',
            'application_money_received_for_allotment',
            'application_money_due_for_refund',
            'share_application_money_pending_allotment',
            'security_deposits_current',
            'earnest_money_deposits',
            'retention_money_current',
            'derivative_liabilities_current',
            'forward_contract_liability',
            'options_liability',
            'swap_liability',
            'book_overdraft',
            'creditors_for_capital_goods',
            'payable_for_capital_expenditure',
            'employee_related_payables',
            'salaries_payable',
            'wages_payable',
            'bonus_payable',
            'leave_encashment_payable',
            'gratuity_payable_current',
            'pf_payable',
            'esic_payable',
            'tds_payable',
            'professional_tax_payable',
            'liability_for_expenses',
            'payable_to_related_parties',
            'amount_due_to_subsidiaries',
            'amount_due_to_associates',
            'amount_due_to_joint_ventures',
            'amount_due_to_directors',
            'amount_due_to_key_management_personnel',
            'reimbursement_payable',
        ],
    },
    'other_current_liabilities': [
        'other_current_liabilities',
        'advance_from_customers',
        'advances_received',
        'contract_liabilities_current',
        'deferred_revenue_current',
        'unearned_revenue',
        'income_received_in_advance',
        'statutory_dues_payable',
        'gst_payable',
        'cgst_payable',
        'sgst_payable',
        'igst_payable',
        'gst_cess_payable',
        'customs_duty_payable',
        'excise_duty_payable',
        'service_tax_payable',
        'vat_payable',
        'sales_tax_payable',
        'entry_tax_payable',
        'cess_payable',
        'other_statutory_liabilities',
        'contribution_to_pf_esi',
        'deferred_government_grants_current',
        'warranty_claims_liability',
    ],
    'provisions': [
        'short_term_provisions',
        'provision_for_employee_benefits_current',
        'provision_for_gratuity_current',
        'provision_for_leave_benefits_current',
        'provision_for_bonus',
        'provision_for_warranties_current',
        'provision_for_expected_credit_losses',
        'provision_for_doubtful_debts',
        'provision_for_slow_moving_inventory',
        'provision_for_obsolete_inventory',
        'provision_for_contingencies',
        'provision_for_proposed_dividend',
        'provision_for_tax_on_proposed_dividend',
        'provision_for_corporate_dividend_tax',
        'provision_for_litigations_current',
        'provision_for_csr_expenditure',
        'other_current_provisions',
    ],
    'current_tax_liabilities': [
        'current_tax_liabilities',
        'provision_for_income_tax',
        'income_tax_payable',
        'current_tax_payable',
        'advance_tax_payable',
        'tax_payable_net_of_advance_tax',
        'mat_payable',
    ],
    'liabilities_held_for_sale': [
        'liabilities_directly_associated_with_assets_held_for_sale',
        'liabilities_of_disposal_group_held_for_sale',
    ],
}

# =============================================================================
# SECTION 4: BALANCE SHEET - NON-CURRENT ASSETS
# =============================================================================

BALANCE_SHEET_NON_CURRENT_ASSETS = {
    'property_plant_equipment': [
        'property_plant_and_equipment',
        'gross_block',
        'accumulated_depreciation',
        'net_block',
        'land_freehold',
        'land_leasehold',
        'buildings',
        'factory_buildings',
        'office_buildings',
        'residential_buildings',
        'roads',
        'bridges',
        'culverts',
        'plant_and_machinery',
        'plant_and_equipment',
        'electrical_installations',
        'electrical_equipment',
        'factory_equipment',
        'laboratory_equipment',
        'furniture_and_fixtures',
        'furniture_and_fittings',
        'office_equipment',
        'computers',
        'computer_equipment',
        'data_processing_equipment',
        'servers_and_networks',
        'vehicles',
        'motor_vehicles',
        'motor_cars',
        'trucks_and_lorries',
        'aircraft',
        'ships_and_vessels',
        'railway_sidings',
        'tools_and_implements',
        'dies_and_moulds',
        'patterns',
        'loose_tools',
        'livestock',
        'bearer_plants',
        'leasehold_improvements',
        'temporary_structures',
        'assets_under_finance_lease',
        'assets_on_operating_lease',
    ],
    'capital_work_in_progress': [
        'capital_work_in_progress',
        'cwip',
        'construction_in_progress',
        'buildings_under_construction',
        'plant_under_installation',
        'capital_goods_in_transit',
        'capital_advances',
        'pre_operative_expenses_pending_capitalization',
        'cwip_ageing_less_than_1_year',
        'cwip_ageing_1_to_2_years',
        'cwip_ageing_2_to_3_years',
        'cwip_ageing_more_than_3_years',
        'cwip_projects_in_progress',
        'cwip_projects_temporarily_suspended',
    ],
    'right_of_use_assets': [
        'right_of_use_assets',
        'rou_assets_land',
        'rou_assets_buildings',
        'rou_assets_plant_and_machinery',
        'rou_assets_vehicles',
        'rou_assets_office_equipment',
        'rou_assets_leasehold_land',
        'rou_assets_accumulated_depreciation',
    ],
    'investment_property': [
        'investment_property',
        'investment_property_under_construction',
        'investment_property_freehold_land',
        'investment_property_buildings',
        'investment_property_accumulated_depreciation',
        'investment_property_fair_value',
        'investment_property_cost_model',
    ],
    'goodwill': [
        'goodwill',
        'goodwill_on_consolidation',
        'goodwill_on_acquisition',
        'goodwill_impairment',
        'accumulated_impairment_on_goodwill',
    ],
    'other_intangible_assets': [
        'other_intangible_assets',
        'intangible_assets',
        'computer_software',
        'software_licenses',
        'software_under_development',
        'patents',
        'copyrights',
        'trademarks',
        'brand_names',
        'trade_names',
        'franchise_rights',
        'licenses_and_franchises',
        'mining_rights',
        'exploration_rights',
        'water_rights',
        'fishing_rights',
        'broadcasting_rights',
        'spectrum_license',
        'route_permits',
        'technical_knowhow',
        'product_development_costs',
        'development_expenditure',
        'customer_relationships',
        'customer_contracts',
        'customer_lists',
        'non_compete_agreements',
        'marketing_related_intangibles',
        'order_backlog',
        'film_rights',
        'music_rights',
        'publication_titles',
        'mastheads',
        'recipes_formulas_designs',
        'leasehold_rights',
        'intangible_assets_under_development',
    ],
    'intangible_assets_under_development': [
        'intangible_assets_under_development',
        'iaud',
        'software_under_development',
        'product_under_development',
        'iaud_ageing_less_than_1_year',
        'iaud_ageing_1_to_2_years',
        'iaud_ageing_2_to_3_years',
        'iaud_ageing_more_than_3_years',
    ],
    'biological_assets': [
        'biological_assets_non_current',
        'bearer_biological_assets',
        'mature_bearer_plants',
        'immature_bearer_plants',
        'livestock_non_current',
        'plantation_assets',
    ],
}

# =============================================================================
# SECTION 5: BALANCE SHEET - CURRENT ASSETS
# =============================================================================

BALANCE_SHEET_CURRENT_ASSETS = {
    'inventories': [
        'inventories',
        'raw_materials',
        'raw_materials_in_transit',
        'raw_materials_at_ports',
        'work_in_progress',
        'wip',
        'semi_finished_goods',
        'finished_goods',
        'finished_goods_in_transit',
        'stock_in_trade',
        'traded_goods',
        'goods_in_transit',
        'stores_and_spares',
        'stores_and_consumables',
        'packing_materials',
        'loose_tools',
        'scrap',
        'by_products',
        'residues',
        'fuel_and_lubricants',
        'chemicals',
        'laboratory_consumables',
        'construction_materials',
        'property_development_stock',
        'real_estate_inventory',
        'land_stock',
        'stock_of_flats_under_construction',
        'stock_of_completed_flats',
        'food_and_beverages',
        'stock_of_livestock',
        'agricultural_produce',
        'biological_assets_held_for_sale',
        'inventory_provision',
        'provision_for_obsolete_inventory',
        'provision_for_slow_moving_inventory',
        'inventory_write_down',
        'inventory_valuation_adjustment',
    ],
    'financial_assets': {
        'investments': [
            'current_investments',
            'investment_in_mutual_funds',
            'investment_in_debt_mutual_funds',
            'investment_in_equity_mutual_funds',
            'investment_in_liquid_funds',
            'investment_in_money_market_funds',
            'investment_in_fixed_maturity_plans',
            'treasury_bills',
            'commercial_paper_investments',
            'certificate_of_deposits',
            'government_securities_current',
            'quoted_investments_current',
            'unquoted_investments_current',
            'investment_in_bonds_current',
            'investment_in_debentures_current',
            'equity_instruments_fvtpl_current',
            'debt_instruments_fvtpl_current',
            'debt_instruments_fvoci_current',
            'debt_instruments_amortised_cost_current',
            'investments_designated_as_held_for_trading',
            'non_current_investments_reclassified_as_current',
            'deposits_with_banks_more_than_12_months',
            'deposits_with_banks_more_than_3_months_less_than_12_months',
            'margin_money_deposits',
            'security_deposits_current',
            'deposits_with_financial_institutions',
            'deposits_under_lien',
            'earmarked_deposits',
            'deposits_pledged_as_security',
        ],
        'trade_receivables': [
            'trade_receivables',
            'sundry_debtors',
            'debtors_for_goods',
            'debtors_for_services',
            'receivables_from_related_parties',
            'receivables_from_subsidiaries',
            'receivables_from_associates',
            'receivables_from_joint_ventures',
            'receivables_from_directors',
            'receivables_from_key_management_personnel',
            'bills_receivable',
            'trade_receivables_secured',
            'trade_receivables_unsecured',
            'trade_receivables_considered_good_secured',
            'trade_receivables_considered_good_unsecured',
            'trade_receivables_credit_impaired',
            'trade_receivables_which_have_significant_increase_in_credit_risk',
            'trade_receivables_doubtful',
            'provision_for_doubtful_debts',
            'allowance_for_expected_credit_losses',
            'provision_for_bad_debts',
            'bad_debts_written_off',
            'unbilled_revenue',
            'unbilled_receivables',
            'accrued_income',
            'accrued_revenue',
            'contract_assets',
            'trade_receivables_disputed',
            'trade_receivables_disputed_considered_good',
            'trade_receivables_disputed_considered_doubtful',
            'trade_receivables_undisputed',
            'trade_receivables_undisputed_considered_good',
            'trade_receivables_undisputed_considered_doubtful',
            'trade_receivables_outstanding_less_than_6_months',
            'trade_receivables_outstanding_6_months_to_1_year',
            'trade_receivables_outstanding_1_to_2_years',
            'trade_receivables_outstanding_2_to_3_years',
            'trade_receivables_outstanding_more_than_3_years',
            'receivables_from_government',
            'export_receivables',
            'retention_receivables',
            'claims_receivable',
            'receivables_factored',
            'receivables_discounted',
        ],
        'cash_and_cash_equivalents': [
            'cash_and_cash_equivalents',
            'cash_on_hand',
            'cash_in_hand',
            'petty_cash',
            'imprest_cash',
            'cheques_on_hand',
            'drafts_on_hand',
            'remittances_in_transit',
            'cash_at_bank',
            'balances_with_banks',
            'balances_with_banks_in_current_accounts',
            'balances_with_banks_in_savings_accounts',
            'balances_with_banks_in_cc_od_accounts',
            'balances_with_banks_in_foreign_currency_accounts',
            'deposits_with_original_maturity_less_than_3_months',
            'short_term_deposits_with_banks',
            'fixed_deposits_with_maturity_less_than_3_months',
            'highly_liquid_investments',
            'bank_deposits_with_original_maturity_upto_3_months',
            'money_market_instruments',
            'cash_equivalents',
        ],
        'bank_balances_other_than_cash_equivalents': [
            'bank_balances_other_than_cash_and_cash_equivalents',
            'other_bank_balances',
            'earmarked_balances_with_banks',
            'unpaid_dividend_accounts',
            'unclaimed_dividend_accounts',
            'unpaid_matured_deposits',
            'unpaid_matured_debentures',
            'margin_money',
            'margin_money_against_borrowings',
            'margin_money_against_guarantees',
            'margin_money_against_letter_of_credit',
            'deposits_held_as_lien',
            'deposits_with_maturity_more_than_3_months_less_than_12_months',
            'fixed_deposits_under_lien',
            'bank_deposits_held_as_security',
            'bank_deposits_pledged_with_government',
            'bank_deposits_pledged_with_banks',
            'restricted_cash',
            'escrow_accounts',
            'client_money_accounts',
            'special_accounts_for_csr',
            'dividend_distribution_account',
        ],
        'loans': [
            'loans_current',
            'loans_to_related_parties_current',
            'loans_to_employees_current',
            'staff_loans',
            'staff_advances',
            'loans_to_subsidiaries_current',
            'loans_to_associates_current',
            'loans_to_joint_ventures_current',
            'loans_to_directors_current',
            'loans_to_key_management_personnel_current',
            'inter_corporate_loans_given_current',
            'loans_considered_good_secured_current',
            'loans_considered_good_unsecured_current',
            'loans_with_significant_credit_risk_current',
            'loans_credit_impaired_current',
            'provision_for_doubtful_loans_current',
        ],
        'other_financial_assets': [
            'other_current_financial_assets',
            'interest_accrued_on_deposits',
            'interest_accrued_on_investments',
            'interest_accrued_on_loans',
            'interest_receivable',
            'dividend_receivable',
            'rent_receivable',
            'royalty_receivable',
            'commission_receivable',
            'claims_receivable',
            'insurance_claims_receivable',
            'claims_against_suppliers',
            'claims_against_carriers',
            'claims_against_government',
            'gst_input_credit_receivable',
            'gst_refund_receivable',
            'cenvat_credit_receivable',
            'service_tax_credit_receivable',
            'vat_credit_receivable',
            'export_incentives_receivable',
            'duty_drawback_receivable',
            'meis_receivable',
            'seis_receivable',
            'rodtep_receivable',
            'subsidy_receivable',
            'government_grants_receivable',
            'derivative_assets_current',
            'forward_contracts_receivable',
            'hedging_instruments_assets_current',
            'fair_value_of_derivatives_current',
            'receivable_from_sale_of_investments',
            'receivable_from_sale_of_assets',
            'receivable_from_sale_of_subsidiaries',
            'earnest_money_deposits',
            'tender_deposits',
            'security_deposits_receivable',
            'advances_to_vendors',
            'advances_to_suppliers',
            'amounts_recoverable',
            'other_receivables',
        ],
    },
    'current_tax_assets': [
        'current_tax_assets',
        'advance_income_tax',
        'advance_tax',
        'tax_paid_in_advance',
        'tds_receivable',
        'tcs_receivable',
        'self_assessment_tax_paid',
        'income_tax_refund_receivable',
        'mat_credit_entitlement_current',
        'tax_deducted_at_source',
        'tax_collected_at_source',
        'advance_fringe_benefit_tax',
    ],
    'other_current_assets': [
        'other_current_assets',
        'prepaid_expenses',
        'prepaid_insurance',
        'prepaid_rent',
        'prepaid_maintenance',
        'prepaid_subscriptions',
        'prepaid_software_licenses',
        'prepaid_commission',
        'prepaid_interest',
        'prepaid_taxes',
        'advances_to_employees',
        'advances_to_suppliers',
        'capital_advances_current',
        'advance_for_capital_goods',
        'advances_for_purchase_of_goods',
        'advances_for_services',
        'advances_to_contractors',
        'advances_for_expenses',
        'travel_advances',
        'imprest_balances',
        'balances_with_government_authorities',
        'balances_with_customs_authorities',
        'balances_with_excise_authorities',
        'gst_input_credit',
        'cgst_input_credit',
        'sgst_input_credit',
        'igst_input_credit',
        'cenvat_credit_balance',
        'input_service_tax_credit',
        'vat_input_credit',
        'cst_refund_receivable',
        'export_benefits_receivable',
        'incentives_receivable',
        'gratuity_fund_asset',
        'defined_benefit_asset',
        'prepaid_gratuity',
        'assets_held_for_sale',
        'disposal_group_held_for_sale',
        'non_current_assets_held_for_sale',
        'discontinued_operations_assets',
        'miscellaneous_current_assets',
    ],
}

# =============================================================================
# SECTION 6: STATEMENT OF PROFIT AND LOSS - REVENUE
# =============================================================================

STATEMENT_OF_PROFIT_LOSS_REVENUE = {
    'revenue_from_operations': {
        'sale_of_products': [
            'sale_of_products',
            'gross_sales',
            'domestic_sales',
            'export_sales',
            'deemed_exports',
            'sales_within_india',
            'sales_outside_india',
            'sale_of_manufactured_goods',
            'sale_of_traded_goods',
            'sale_of_finished_goods',
            'sale_of_scrap',
            'sale_of_by_products',
            'sale_of_waste',
            'sale_of_power',
            'sale_of_electricity',
            'sale_of_software_products',
            'sale_of_it_products',
            'sale_of_real_estate',
            'sale_of_constructed_properties',
            'sale_of_development_rights',
            'sale_of_plots',
            'sale_of_flats',
            'sale_of_petroleum_products',
            'sale_of_coal',
            'sale_of_minerals',
            'sale_of_agricultural_produce',
            'sale_of_telecom_products',
            'sale_of_pharmaceutical_products',
            'sale_of_fmcg_products',
            'sale_of_consumer_goods',
            'sale_of_industrial_goods',
            'sale_of_capital_goods',
            'sale_of_chemicals',
            'sale_of_textiles',
            'sale_of_cement',
            'sale_of_steel',
            'sale_of_metals',
            'sale_of_automobiles',
            'sale_of_auto_components',
            'sale_of_food_products',
            'sale_of_beverages',
            'sale_of_publishing_products',
            'inter_segment_sales',
            'intra_group_sales',
            'inter_divisional_sales',
        ],
        'sale_of_services': [
            'sale_of_services',
            'revenue_from_services',
            'income_from_services',
            'service_revenue',
            'rendering_of_services',
            'professional_services_revenue',
            'consulting_services_revenue',
            'it_services_revenue',
            'software_services_revenue',
            'software_development_services',
            'technology_services_revenue',
            'digital_services_revenue',
            'cloud_services_revenue',
            'saas_revenue',
            'paas_revenue',
            'iaas_revenue',
            'platform_services_revenue',
            'hosting_services_revenue',
            'maintenance_services_revenue',
            'support_services_revenue',
            'amc_revenue',
            'annual_maintenance_contract_revenue',
            'installation_services_revenue',
            'commissioning_services_revenue',
            'training_services_revenue',
            'outsourcing_services_revenue',
            'bpo_services_revenue',
            'kpo_services_revenue',
            'call_center_revenue',
            'back_office_services_revenue',
            'engineering_services_revenue',
            'design_services_revenue',
            'construction_services_revenue',
            'project_management_services',
            'turnkey_project_revenue',
            'epc_contract_revenue',
            'contract_revenue',
            'job_work_revenue',
            'job_work_charges',
            'processing_charges_revenue',
            'conversion_charges_revenue',
            'tolling_revenue',
            'labour_charges_revenue',
            'fabrication_charges_revenue',
            'machining_charges_revenue',
            'logistics_services_revenue',
            'transportation_services_revenue',
            'freight_revenue',
            'warehousing_services_revenue',
            'storage_charges_revenue',
            'handling_charges_revenue',
            'shipping_services_revenue',
            'chartering_revenue',
            'aviation_services_revenue',
            'telecom_services_revenue',
            'data_services_revenue',
            'internet_services_revenue',
            'voice_services_revenue',
            'messaging_services_revenue',
            'roaming_revenue',
            'interconnect_revenue',
            'broadcasting_services_revenue',
            'cable_services_revenue',
            'dth_services_revenue',
            'ott_services_revenue',
            'content_services_revenue',
            'advertising_services_revenue',
            'marketing_services_revenue',
            'media_services_revenue',
            'financial_services_revenue',
            'banking_services_revenue',
            'lending_services_revenue',
            'fee_based_income',
            'commission_income',
            'brokerage_income',
            'advisory_fees',
            'portfolio_management_fees',
            'asset_management_fees',
            'fund_management_fees',
            'custodial_services_revenue',
            'depository_services_revenue',
            'clearing_and_settlement_revenue',
            'insurance_services_revenue',
            'premium_earned',
            'reinsurance_revenue',
            'claims_handling_services',
            'healthcare_services_revenue',
            'hospital_services_revenue',
            'diagnostic_services_revenue',
            'medical_services_revenue',
            'clinical_services_revenue',
            'pharmaceutical_services_revenue',
            'cro_services_revenue',
            'cmo_services_revenue',
            'hospitality_services_revenue',
            'hotel_services_revenue',
            'room_revenue',
            'food_and_beverage_revenue',
            'restaurant_revenue',
            'catering_services_revenue',
            'banquet_services_revenue',
            'tourism_services_revenue',
            'travel_services_revenue',
            'ticketing_revenue',
            'education_services_revenue',
            'tuition_fees',
            'course_fees',
            'examination_fees',
            'certification_fees',
            'research_services_revenue',
            'testing_services_revenue',
            'certification_services_revenue',
            'inspection_services_revenue',
            'audit_services_revenue',
            'assurance_services_revenue',
            'legal_services_revenue',
            'recruitment_services_revenue',
            'staffing_services_revenue',
            'manpower_services_revenue',
            'security_services_revenue',
            'housekeeping_services_revenue',
            'facility_management_services',
            'property_management_services',
            'rental_services_revenue',
            'leasing_services_revenue',
            'equipment_rental_revenue',
            'vehicle_rental_revenue',
            'franchise_services_revenue',
            'licensing_services_revenue',
            'subscription_revenue',
            'membership_fees',
            'entertainment_services_revenue',
            'gaming_services_revenue',
            'sports_services_revenue',
            'event_management_revenue',
        ],
        'other_operating_revenue': [
            'other_operating_revenue',
            'other_operating_income',
            'scrap_sales',
            'waste_sales',
            'by_product_sales',
            'export_incentives',
            'duty_drawback',
            'meis_license_income',
            'seis_license_income',
            'rodtep_income',
            'rosctl_income',
            'focus_market_scheme',
            'focus_product_scheme',
            'advance_authorization_benefits',
            'epcg_benefits',
            'government_grants_operating',
            'production_linked_incentive',
            'pli_scheme_income',
            'subsidy_income_operating',
            'carbon_credit_income',
            'rec_income',
            'renewable_energy_certificates',
            'energy_saving_certificates',
            'service_charges_received',
            'processing_fees',
            'handling_charges',
            'delivery_charges',
            'installation_charges',
            'warranty_revenue',
            'extended_warranty_revenue',
            'spare_parts_revenue',
            'accessories_revenue',
            'after_sales_service_revenue',
        ],
    },
    'deductions_from_revenue': [
        'less_excise_duty',
        'excise_duty_on_sales',
        'less_sales_tax',
        'less_vat',
        'less_gst',
        'less_service_tax',
        'less_customs_duty',
        'trade_discounts',
        'volume_discounts',
        'cash_discounts',
        'early_payment_discounts',
        'rebates',
        'incentives_to_customers',
        'sales_returns',
        'returns_and_allowances',
        'price_adjustments',
        'retrospective_price_adjustments',
        'liquidated_damages_paid',
        'penalties_on_contracts',
    ],
    'other_income': [
        'other_income',
        # Interest Income
        'interest_income',
        'interest_on_fixed_deposits',
        'interest_on_bank_deposits',
        'interest_on_loans_given',
        'interest_on_inter_corporate_deposits',
        'interest_on_staff_loans',
        'interest_on_customer_advances',
        'interest_on_delayed_payments',
        'interest_on_income_tax_refund',
        'interest_on_bonds',
        'interest_on_debentures',
        'interest_on_government_securities',
        'interest_on_overdue_bills',
        'interest_from_banks',
        'interest_from_financial_institutions',
        'interest_from_customers',
        'interest_from_related_parties',
        'interest_income_on_financial_assets_at_amortised_cost',
        'interest_income_on_financial_assets_at_fvoci',
        'unwinding_of_discount',
        
        # Dividend Income
        'dividend_income',
        'dividend_from_subsidiaries',
        'dividend_from_associates',
        'dividend_from_joint_ventures',
        'dividend_from_investments',
        'dividend_on_equity_instruments',
        'dividend_on_mutual_funds',
        'dividend_on_preference_shares',
        
        # Rental Income
        'rental_income',
        'rent_received',
        'lease_rental_income',
        'sublease_income',
        'income_from_investment_property',
        
        # Gain on Investments and Assets
        'profit_on_sale_of_investments',
        'gain_on_sale_of_investments',
        'net_gain_on_sale_of_investments',
        'profit_on_sale_of_current_investments',
        'profit_on_sale_of_non_current_investments',
        'gain_on_fair_value_changes',
        'fair_value_gain_on_investments',
        'fair_value_gain_on_financial_instruments',
        'gain_on_derivatives',
        'gain_on_forward_contracts',
        'gain_on_foreign_currency_derivatives',
        'gain_on_commodity_derivatives',
        'mark_to_market_gain',
        'profit_on_sale_of_fixed_assets',
        'gain_on_disposal_of_ppe',
        'profit_on_sale_of_property',
        'profit_on_sale_of_investments_in_subsidiaries',
        'gain_on_disposal_of_subsidiaries',
        'gain_on_bargain_purchase',
        
        # Foreign Exchange
        'foreign_exchange_gain',
        'exchange_gain_loss_net',
        'net_foreign_exchange_fluctuation_gain',
        'realized_exchange_gain',
        'unrealized_exchange_gain',
        'exchange_difference_on_translation',
        
        # Other Gains
        'liabilities_no_longer_required_written_back',
        'provisions_no_longer_required_written_back',
        'excess_provisions_written_back',
        'bad_debts_recovered',
        'sundry_balances_written_back',
        'creditors_written_back',
        
        # Government Grants and Subsidies
        'government_grants_income',
        'capital_grants_amortized',
        'revenue_grants',
        'subsidy_income',
        'export_subsidy',
        'interest_subsidy',
        'capital_subsidy',
        'incentive_income',
        'government_incentives',
        
        # Miscellaneous Income
        'miscellaneous_income',
        'royalty_income',
        'technical_knowhow_fees_received',
        'license_fees_received',
        'franchise_fees_income',
        'management_fees_received',
        'shared_services_income',
        'reimbursement_income',
        'insurance_claims_received',
        'compensation_received',
        'liquidated_damages_received',
        'claims_received',
        'sale_of_import_licenses',
        'profit_on_sale_of_carbon_credits',
        'commission_income',
        'agency_commission',
        'sundry_receipts',
        'recoveries',
        'write_back_of_impairment',
        'reversal_of_impairment_loss',
    ],
}

# =============================================================================
# SECTION 7: STATEMENT OF PROFIT AND LOSS - EXPENSES
# =============================================================================

STATEMENT_OF_PROFIT_LOSS_EXPENSES = {
    'cost_of_materials_consumed': [
        'cost_of_materials_consumed',
        'raw_materials_consumed',
        'opening_stock_of_raw_materials',
        'add_purchases_of_raw_materials',
        'less_closing_stock_of_raw_materials',
        'consumption_of_raw_materials',
        'material_cost',
        'cost_of_components_consumed',
        'packing_materials_consumed',
        'stores_and_spares_consumed',
        'consumables_consumed',
        'fuel_consumed',
        'power_and_fuel_for_manufacturing',
        'chemicals_consumed',
        'laboratory_consumables_consumed',
        'imported_raw_materials',
        'indigenous_raw_materials',
        'cost_of_materials_including_excise',
    ],
    'purchases_of_stock_in_trade': [
        'purchases_of_stock_in_trade',
        'purchases_of_traded_goods',
        'cost_of_goods_purchased',
        'imported_purchases',
        'domestic_purchases',
        'purchase_of_finished_goods',
    ],
    'changes_in_inventories': [
        'changes_in_inventories',
        'changes_in_inventories_of_finished_goods_wip_and_stock_in_trade',
        'opening_stock_of_finished_goods',
        'closing_stock_of_finished_goods',
        'opening_stock_of_work_in_progress',
        'closing_stock_of_work_in_progress',
        'opening_stock_of_stock_in_trade',
        'closing_stock_of_stock_in_trade',
        'opening_inventory',
        'closing_inventory',
        'increase_in_inventories',
        'decrease_in_inventories',
        'changes_in_scrap_inventory',
        'changes_in_by_product_inventory',
        'excise_duty_on_inventory',
    ],
    'employee_benefit_expense': [
        'employee_benefit_expense',
        'employee_benefits_expense',
        'salaries_and_wages',
        'salaries',
        'wages',
        'gross_salaries',
        'basic_salary',
        'dearness_allowance',
        'house_rent_allowance',
        'conveyance_allowance',
        'medical_allowance',
        'special_allowance',
        'other_allowances',
        'bonus',
        'performance_bonus',
        'annual_bonus',
        'statutory_bonus',
        'ex_gratia',
        'commission_to_employees',
        'sales_incentives',
        'employee_incentives',
        'overtime_payments',
        'arrears',
        'leave_encashment',
        'leave_travel_allowance',
        'lta',
        'contribution_to_provident_fund',
        'employers_contribution_to_pf',
        'contribution_to_pension_fund',
        'contribution_to_superannuation_fund',
        'contribution_to_esi',
        'employers_contribution_to_esi',
        'contribution_to_other_funds',
        'national_pension_scheme_contribution',
        'gratuity_expense',
        'provision_for_gratuity',
        'gratuity_fund_contribution',
        'leave_benefits_expense',
        'compensated_absences_expense',
        'provision_for_leave_encashment',
        'staff_welfare_expense',
        'staff_welfare_expenses',
        'canteen_expenses',
        'medical_expenses_employees',
        'medical_insurance_premium',
        'group_insurance_premium',
        'group_life_insurance',
        'personal_accident_insurance',
        'health_insurance_premium',
        'employee_insurance',
        'staff_training_expenses',
        'training_and_development',
        'recruitment_expenses',
        'hiring_expenses',
        'relocation_expenses',
        'uniform_expenses',
        'safety_equipment_expenses',
        'employee_education_assistance',
        'scholarship_to_employees',
        'retirement_benefits',
        'post_employment_benefits',
        'other_long_term_employee_benefits',
        'long_service_awards',
        'termination_benefits',
        'voluntary_retirement_scheme',
        'vrs_expense',
        'retrenchment_compensation',
        'severance_pay',
        'notice_pay',
        'directors_remuneration',
        'directors_sitting_fees',
        'managerial_remuneration',
        'share_based_payment_expense',
        'esop_expense',
        'employee_stock_option_expense',
        'sar_expense',
        'stock_appreciation_rights_expense',
        'actuarial_loss',
        'remeasurement_of_defined_benefit_plans_expense',
        'contract_labor_expenses',
        'casual_labor_expenses',
        'temporary_staff_expenses',
        'outsourced_staff_expenses',
        'manpower_expenses',
        'staffing_expenses',
    ],
    'finance_costs': [
        'finance_costs',
        'finance_cost',
        'finance_expenses',
        'interest_expense',
        'interest_on_borrowings',
        'interest_on_term_loans',
        'interest_on_working_capital_loans',
        'interest_on_cash_credit',
        'interest_on_overdraft',
        'interest_on_debentures',
        'interest_on_bonds',
        'interest_on_commercial_paper',
        'interest_on_inter_corporate_deposits',
        'interest_on_loans_from_banks',
        'interest_on_loans_from_financial_institutions',
        'interest_on_loans_from_related_parties',
        'interest_on_loans_from_directors',
        'interest_on_public_deposits',
        'interest_on_deposits',
        'interest_on_delayed_payments',
        'interest_on_statutory_dues',
        'interest_on_income_tax',
        'interest_on_gst',
        'interest_on_tds',
        'interest_on_customs',
        'interest_on_excise',
        'penal_interest',
        'interest_on_lease_liabilities',
        'finance_cost_on_lease_liabilities',
        'interest_on_finance_lease',
        'unwinding_of_discount_on_provisions',
        'unwinding_of_discount_on_decommissioning_liability',
        'unwinding_of_discount_on_asset_retirement_obligation',
        'discount_on_bills',
        'bill_discounting_charges',
        'factoring_charges',
        'bank_charges',
        'bank_commission',
        'lc_charges',
        'letter_of_credit_charges',
        'bank_guarantee_commission',
        'loan_processing_fees',
        'loan_arrangement_fees',
        'syndication_fees',
        'commitment_fees',
        'guarantee_commission',
        'other_borrowing_costs',
        'amortisation_of_borrowing_costs',
        'amortisation_of_ancillary_borrowing_costs',
        'exchange_difference_as_borrowing_costs',
        'premium_on_redemption_of_debentures',
        'debenture_issue_expenses_amortized',
        'fair_value_loss_on_financial_instruments',
        'loss_on_derivatives',
        'loss_on_hedging_instruments',
        'net_loss_on_foreign_currency_borrowings',
    ],
    'depreciation_and_amortization': [
        'depreciation_and_amortization_expense',
        'depreciation_and_amortisation_expense',
        'depreciation_expense',
        'depreciation_on_tangible_assets',
        'depreciation_on_property_plant_equipment',
        'depreciation_on_buildings',
        'depreciation_on_plant_and_machinery',
        'depreciation_on_furniture',
        'depreciation_on_vehicles',
        'depreciation_on_computers',
        'depreciation_on_office_equipment',
        'depreciation_on_leasehold_improvements',
        'depreciation_on_right_of_use_assets',
        'depreciation_on_rou_assets',
        'depreciation_on_investment_property',
        'depreciation_on_bearer_plants',
        'depreciation_on_assets_given_on_lease',
        'amortization_expense',
        'amortisation_expense',
        'amortization_of_intangible_assets',
        'amortisation_of_intangible_assets',
        'amortization_of_goodwill',
        'amortization_of_software',
        'amortization_of_patents',
        'amortization_of_trademarks',
        'amortization_of_licenses',
        'amortization_of_customer_relationships',
        'amortization_of_technical_knowhow',
        'amortization_of_development_costs',
        'amortization_of_mining_rights',
        'amortization_of_spectrum_license',
        'impairment_loss',
        'impairment_of_goodwill',
        'impairment_of_intangible_assets',
        'impairment_of_property_plant_equipment',
        'impairment_of_investment_property',
        'impairment_of_right_of_use_assets',
        'impairment_of_investments',
        'impairment_of_financial_assets',
        'impairment_of_trade_receivables',
        'expected_credit_loss',
        'ecl_provision',
        'provision_for_expected_credit_loss',
        'loss_allowance_on_financial_assets',
    ],
    'other_expenses': [
        'other_expenses',
        # Manufacturing Expenses
        'manufacturing_expenses',
        'factory_expenses',
        'works_expenses',
        'power_and_fuel',
        'electricity_charges',
        'water_charges',
        'gas_charges',
        'steam_charges',
        'repairs_and_maintenance',
        'repairs_to_buildings',
        'repairs_to_plant_and_machinery',
        'repairs_to_vehicles',
        'repairs_to_furniture',
        'repairs_to_computers',
        'repairs_to_others',
        'maintenance_expenses',
        'annual_maintenance_contracts',
        'spares_consumed',
        'job_work_charges_paid',
        'processing_charges_paid',
        'testing_charges',
        'laboratory_charges',
        'quality_control_expenses',
        'excise_duty',
        
        # Rent and Lease Expenses
        'rent',
        'rent_expense',
        'office_rent',
        'factory_rent',
        'warehouse_rent',
        'godown_rent',
        'equipment_rent',
        'vehicle_rent',
        'lease_rent',
        'hire_charges',
        'short_term_lease_expense',
        'low_value_asset_lease_expense',
        'variable_lease_payments',
        
        # Insurance
        'insurance_expense',
        'insurance_premium',
        'fire_insurance',
        'marine_insurance',
        'transit_insurance',
        'liability_insurance',
        'property_insurance',
        'vehicle_insurance',
        'machinery_insurance',
        'stock_insurance',
        'keyman_insurance',
        'directors_and_officers_insurance',
        
        # Rates and Taxes
        'rates_and_taxes',
        'property_tax',
        'municipal_taxes',
        'cess',
        'stamp_duty',
        'registration_fees',
        'road_tax',
        'profession_tax',
        'gst_expenses',
        'gst_input_credit_written_off',
        'customs_duty_expense',
        'import_duty',
        'anti_dumping_duty',
        'safeguard_duty',
        'countervailing_duty',
        
        # Selling and Distribution
        'selling_expenses',
        'selling_and_distribution_expenses',
        'advertisement_expenses',
        'advertising_expenses',
        'publicity_expenses',
        'marketing_expenses',
        'sales_promotion_expenses',
        'discount_and_rebates',
        'commission_on_sales',
        'brokerage_expense',
        'freight_outward',
        'freight_and_forwarding',
        'carriage_outward',
        'transport_charges',
        'shipping_charges',
        'logistics_expenses',
        'clearing_and_forwarding_charges',
        'octroi',
        'packing_charges',
        'packing_expenses',
        'delivery_expenses',
        'distribution_expenses',
        'after_sales_service_expenses',
        'warranty_expenses',
        'warranty_claims',
        'sales_return_expenses',
        'exhibition_expenses',
        'trade_fair_expenses',
        'business_development_expenses',
        'customer_relationship_expenses',
        
        # Professional and Legal
        'professional_fees',
        'professional_charges',
        'legal_fees',
        'legal_charges',
        'legal_and_professional_fees',
        'consultancy_charges',
        'consultant_fees',
        'technical_consultancy',
        'management_consultancy',
        'retainership_fees',
        'accounting_fees',
        'tax_consultancy_fees',
        'secretarial_fees',
        'company_secretary_fees',
        'valuation_fees',
        'certification_fees',
        
        # Audit Fees
        'auditors_remuneration',
        'audit_fees',
        'statutory_audit_fees',
        'tax_audit_fees',
        'internal_audit_fees',
        'cost_audit_fees',
        'secretarial_audit_fees',
        'other_audit_services',
        'certification_by_auditors',
        'out_of_pocket_expenses_to_auditors',
        
        # Travel and Conveyance
        'travelling_expenses',
        'traveling_expenses',
        'travel_expenses',
        'domestic_travel',
        'foreign_travel',
        'conveyance_expenses',
        'local_conveyance',
        'vehicle_running_expenses',
        'fuel_expenses_vehicles',
        'petrol_expenses',
        'diesel_expenses',
        'cab_charges',
        'taxi_charges',
        'boarding_and_lodging',
        'hotel_expenses',
        
        # Communication
        'communication_expenses',
        'telephone_expenses',
        'mobile_expenses',
        'internet_expenses',
        'data_charges',
        'postage_and_courier',
        'postage_expenses',
        'courier_charges',
        'telegram_expenses',
        
        # Office and Administrative
        'office_expenses',
        'administrative_expenses',
        'general_expenses',
        'miscellaneous_expenses',
        'printing_and_stationery',
        'stationery_expenses',
        'photocopying_charges',
        'books_and_periodicals',
        'subscription_expenses',
        'software_expenses',
        'software_license_fees',
        'it_expenses',
        'computer_expenses',
        'data_processing_charges',
        'housekeeping_expenses',
        'security_expenses',
        'security_service_charges',
        'gardening_expenses',
        'pantry_expenses',
        'meeting_expenses',
        'conference_expenses',
        'seminar_expenses',
        'membership_and_subscription',
        'club_expenses',
        'association_fees',
        
        # Directors and KMP
        'directors_fees',
        'directors_sitting_fees',
        'directors_commission',
        'directors_travel_expenses',
        'independent_directors_fees',
        'directors_other_expenses',
        
        # Research and Development
        'research_and_development_expenses',
        'r_and_d_expenses',
        'product_development_expenses',
        'design_expenses',
        'prototype_expenses',
        'testing_and_trials',
        
        # Corporate Expenses
        'corporate_social_responsibility_expenses',
        'csr_expenses',
        'csr_expenditure',
        'donation',
        'donations_and_contributions',
        'charity',
        'contribution_to_political_parties',
        'corporate_contributions',
        
        # Losses
        'bad_debts_written_off',
        'bad_debts',
        'provision_for_doubtful_debts',
        'provision_for_bad_debts',
        'expected_credit_loss_expense',
        'loss_on_sale_of_fixed_assets',
        'loss_on_disposal_of_ppe',
        'loss_on_sale_of_investments',
        'loss_on_fair_value_changes',
        'mark_to_market_loss',
        'foreign_exchange_loss',
        'exchange_loss',
        'net_foreign_exchange_fluctuation_loss',
        'loss_on_derivatives',
        'inventory_write_offs',
        'stock_written_off',
        'obsolete_inventory_written_off',
        'assets_written_off',
        'assets_discarded',
        'balances_written_off',
        'advances_written_off',
        'deposits_written_off',
        'claims_written_off',
        'loss_on_sale_of_subsidiary',
        'loss_on_discontinuation',
        
        # Environmental and Safety
        'environment_expenses',
        'pollution_control_expenses',
        'effluent_treatment_expenses',
        'waste_disposal_expenses',
        'safety_expenses',
        'fire_safety_expenses',
        
        # Penalties and Fines
        'penalties',
        'fines',
        'liquidated_damages',
        'late_payment_charges',
        'interest_on_delayed_payment',
        'demurrage',
        'penal_charges',
        'penalty_on_statutory_dues',
        
        # Provisions
        'provision_for_contingencies',
        'provision_for_warranties',
        'provision_for_onerous_contracts',
        'provision_for_restructuring',
        'provision_for_site_restoration',
        'provision_for_litigations',
        'provision_for_diminution_in_investments',
        
        # Others
        'royalty_expenses',
        'royalty_paid',
        'technical_fees_paid',
        'brand_usage_fees',
        'franchise_fees_expense',
        'license_fees_expense',
        'management_fees_paid',
        'shared_services_expense',
        'inter_company_charges',
        'reimbursement_of_expenses',
        'prior_period_expenses',
        'prior_period_items',
    ],
}

# =============================================================================
# SECTION 8: STATEMENT OF PROFIT AND LOSS - TAX AND PROFIT ITEMS
# =============================================================================

STATEMENT_OF_PROFIT_LOSS_TAX_AND_PROFIT = {
    'profit_before_exceptional_items_and_tax': [
        'profit_before_exceptional_items_and_tax',
        'profit_before_exceptional_and_extraordinary_items',
        'operating_profit',
        'earnings_before_interest_and_tax',
        'ebit',
        'earnings_before_interest_tax_depreciation_amortization',
        'ebitda',
        'profit_from_operations',
        'operating_income',
    ],
    'exceptional_items': [
        'exceptional_items',
        'exceptional_income',
        'exceptional_expenses',
        # Exceptional Gains
        'profit_on_sale_of_undertaking',
        'profit_on_sale_of_business',
        'profit_on_sale_of_division',
        'gain_on_sale_of_subsidiary',
        'gain_on_sale_of_investment_in_subsidiary',
        'gain_on_demerger',
        'gain_on_slump_sale',
        'compensation_received_exceptional',
        'insurance_claim_exceptional',
        'settlement_received',
        'write_back_of_provision_exceptional',
        # Exceptional Losses
        'loss_on_sale_of_undertaking',
        'loss_on_sale_of_business',
        'loss_on_sale_of_division',
        'loss_on_sale_of_subsidiary',
        'impairment_of_goodwill_exceptional',
        'restructuring_costs',
        'voluntary_retirement_scheme_exceptional',
        'retrenchment_costs',
        'write_off_of_assets_exceptional',
        'write_off_of_project_costs',
        'loss_due_to_fire',
        'loss_due_to_flood',
        'loss_due_to_natural_calamity',
        'penalty_exceptional',
        'fine_exceptional',
        'settlement_paid',
        'litigation_settlement',
        'impairment_exceptional',
        'provision_for_impairment_exceptional',
    ],
    'profit_before_tax': [
        'profit_before_tax',
        'profit_loss_before_tax',
        'pbt',
        'income_before_tax',
        'earnings_before_tax',
        'net_profit_before_tax',
        'profit_before_tax_and_oci',
    ],
    'tax_expense': {
        'current_tax': [
            'current_tax',
            'current_tax_expense',
            'current_income_tax',
            'provision_for_current_tax',
            'income_tax_for_current_year',
            'tax_expense_current_year',
            'mat_current_year',
            'minimum_alternate_tax',
            'current_tax_on_exceptional_items',
            'current_tax_relating_to_prior_years',
            'tax_adjustments_for_earlier_years',
            'short_provision_for_tax',
            'excess_provision_for_tax_written_back',
            'mat_credit_recognized',
            'mat_credit_utilized',
            'mat_credit_written_off',
        ],
        'deferred_tax': [
            'deferred_tax',
            'deferred_tax_expense',
            'deferred_tax_income',
            'deferred_tax_charge',
            'deferred_tax_credit',
            'deferred_tax_asset_recognized',
            'deferred_tax_asset_written_off',
            'deferred_tax_liability_created',
            'deferred_tax_liability_reversed',
            'deferred_tax_on_temporary_differences',
            'deferred_tax_on_unabsorbed_depreciation',
            'deferred_tax_on_carried_forward_losses',
            'deferred_tax_on_oci',
            'deferred_tax_on_fair_value_changes',
            'deferred_tax_on_remeasurement_of_defined_benefit_plans',
            'deferred_tax_relating_to_prior_years',
            'deferred_tax_impact_of_tax_rate_change',
        ],
        'total_tax_expense': [
            'total_tax_expense',
            'tax_expense',
            'income_tax_expense',
            'provision_for_taxation',
        ],
    },
    'profit_after_tax': [
        'profit_for_the_period',
        'profit_for_the_year',
        'profit_after_tax',
        'pat',
        'net_profit',
        'net_profit_after_tax',
        'net_income',
        'earnings_after_tax',
        'profit_loss_for_the_period',
        'loss_for_the_period',
        'loss_for_the_year',
        'net_loss',
        'profit_from_continuing_operations',
        'profit_from_discontinued_operations',
        'loss_from_discontinued_operations',
    ],
    'profit_attributable': [
        'profit_attributable_to_owners_of_parent',
        'profit_attributable_to_equity_holders',
        'profit_attributable_to_non_controlling_interests',
        'profit_attributable_to_minority_interests',
        'share_of_profit_of_associates',
        'share_of_profit_of_joint_ventures',
    ],
}

