# =============================================================================
# SECTION 9: OTHER COMPREHENSIVE INCOME (OCI)
# =============================================================================

OTHER_COMPREHENSIVE_INCOME = {
    'items_not_to_be_reclassified_to_profit_or_loss': {
        'remeasurement_of_defined_benefit_plans': [
            'remeasurement_of_defined_benefit_plans',
            'remeasurement_of_defined_benefit_obligations',
            'remeasurement_of_post_employment_benefit_obligations',
            'actuarial_gains_on_defined_benefit_plans',
            'actuarial_losses_on_defined_benefit_plans',
            'actuarial_gains_losses_on_gratuity',
            'actuarial_gains_losses_on_pension',
            'actuarial_gains_losses_on_leave_encashment',
            'actuarial_gains_losses_on_superannuation',
            'actuarial_gains_losses_on_provident_fund',
            'return_on_plan_assets_excluding_interest_income',
            'effect_of_asset_ceiling',
            'experience_adjustments_on_plan_liabilities',
            'experience_adjustments_on_plan_assets',
            'changes_in_demographic_assumptions',
            'changes_in_financial_assumptions',
            'income_tax_on_remeasurement_of_defined_benefit_plans',
            'deferred_tax_on_remeasurement_of_defined_benefit_plans',
        ],
        'equity_instruments_through_oci': [
            'fair_value_changes_on_equity_instruments_through_oci',
            'fair_value_gain_on_equity_instruments_designated_at_fvoci',
            'fair_value_loss_on_equity_instruments_designated_at_fvoci',
            'changes_in_fair_value_of_equity_investments',
            'gain_on_equity_instruments_measured_at_fvoci',
            'loss_on_equity_instruments_measured_at_fvoci',
            'income_tax_on_fair_value_changes_on_equity_instruments',
            'deferred_tax_on_fvoci_equity_instruments',
        ],
        'revaluation_surplus': [
            'revaluation_surplus_on_ppe',
            'revaluation_surplus_on_property_plant_equipment',
            'revaluation_surplus_on_intangible_assets',
            'revaluation_gain_on_land',
            'revaluation_gain_on_buildings',
            'revaluation_loss_on_ppe',
            'income_tax_on_revaluation_surplus',
            'deferred_tax_on_revaluation_surplus',
        ],
        'share_of_oci_of_associates_jv_not_reclassified': [
            'share_of_oci_of_associates_not_to_be_reclassified',
            'share_of_oci_of_joint_ventures_not_to_be_reclassified',
            'share_of_remeasurement_of_defined_benefit_plans_of_associates',
            'share_of_remeasurement_of_defined_benefit_plans_of_jv',
            'share_of_revaluation_surplus_of_associates',
            'share_of_revaluation_surplus_of_joint_ventures',
        ],
    },
    'items_to_be_reclassified_to_profit_or_loss': {
        'exchange_differences_on_translation': [
            'exchange_differences_on_translation_of_foreign_operations',
            'exchange_differences_on_translating_foreign_subsidiaries',
            'exchange_differences_on_translating_foreign_branches',
            'exchange_differences_on_translating_foreign_associates',
            'exchange_differences_on_translating_foreign_joint_ventures',
            'foreign_currency_translation_reserve_movement',
            'exchange_differences_arising_during_the_period',
            'reclassification_adjustments_on_disposal_of_foreign_operations',
            'exchange_gain_loss_on_net_investment_in_foreign_operations',
            'income_tax_on_exchange_differences_on_translation',
            'deferred_tax_on_foreign_currency_translation',
        ],
        'debt_instruments_through_oci': [
            'fair_value_changes_on_debt_instruments_through_oci',
            'fair_value_gain_on_debt_instruments_at_fvoci',
            'fair_value_loss_on_debt_instruments_at_fvoci',
            'changes_in_fair_value_of_debt_investments',
            'gain_on_debt_instruments_measured_at_fvoci',
            'loss_on_debt_instruments_measured_at_fvoci',
            'reclassification_of_debt_instruments_to_profit_or_loss',
            'impairment_loss_on_debt_instruments_at_fvoci',
            'ecl_on_debt_instruments_at_fvoci',
            'income_tax_on_fair_value_changes_on_debt_instruments',
            'deferred_tax_on_fvoci_debt_instruments',
        ],
        'cash_flow_hedges': [
            'effective_portion_of_gains_on_cash_flow_hedges',
            'effective_portion_of_losses_on_cash_flow_hedges',
            'effective_portion_of_changes_in_fair_value_of_hedging_instruments',
            'gain_on_cash_flow_hedging_instruments',
            'loss_on_cash_flow_hedging_instruments',
            'cash_flow_hedge_reserve_movement',
            'reclassification_adjustments_on_cash_flow_hedges',
            'amount_reclassified_to_profit_or_loss_cash_flow_hedge',
            'amount_reclassified_to_initial_carrying_amount_of_hedged_item',
            'basis_adjustments_on_cash_flow_hedges',
            'hedging_gains_losses_reclassified_to_inventory',
            'hedging_gains_losses_reclassified_to_revenue',
            'hedging_gains_losses_reclassified_to_cost_of_sales',
            'hedging_gains_losses_reclassified_to_finance_costs',
            'ineffective_portion_of_cash_flow_hedges',
            'income_tax_on_cash_flow_hedges',
            'deferred_tax_on_cash_flow_hedge_reserve',
        ],
        'hedges_of_net_investment': [
            'gains_on_hedges_of_net_investment_in_foreign_operations',
            'losses_on_hedges_of_net_investment_in_foreign_operations',
            'effective_portion_of_net_investment_hedges',
            'reclassification_on_disposal_of_foreign_operation',
            'income_tax_on_net_investment_hedges',
        ],
        'cost_of_hedging': [
            'cost_of_hedging_reserve_movement',
            'changes_in_fair_value_of_time_value_of_options',
            'changes_in_fair_value_of_forward_element_of_forward_contracts',
            'changes_in_fair_value_of_foreign_currency_basis_spread',
            'amortisation_of_cost_of_hedging',
            'income_tax_on_cost_of_hedging',
        ],
        'share_of_oci_of_associates_jv_reclassified': [
            'share_of_oci_of_associates_to_be_reclassified',
            'share_of_oci_of_joint_ventures_to_be_reclassified',
            'share_of_exchange_differences_of_associates',
            'share_of_exchange_differences_of_joint_ventures',
            'share_of_cash_flow_hedge_reserve_of_associates',
            'share_of_cash_flow_hedge_reserve_of_joint_ventures',
            'share_of_fair_value_changes_of_associates',
            'share_of_fair_value_changes_of_joint_ventures',
        ],
    },
    'total_oci': [
        'other_comprehensive_income_for_the_period',
        'other_comprehensive_income_for_the_year',
        'total_other_comprehensive_income',
        'other_comprehensive_income_net_of_tax',
        'other_comprehensive_income_before_tax',
        'income_tax_relating_to_oci',
        'tax_effect_on_oci',
        'oci_attributable_to_owners_of_parent',
        'oci_attributable_to_non_controlling_interests',
    ],
    'total_comprehensive_income': [
        'total_comprehensive_income_for_the_period',
        'total_comprehensive_income_for_the_year',
        'total_comprehensive_income',
        'comprehensive_income',
        'total_comprehensive_income_attributable_to_owners_of_parent',
        'total_comprehensive_income_attributable_to_non_controlling_interests',
        'total_comprehensive_income_from_continuing_operations',
        'total_comprehensive_income_from_discontinued_operations',
    ],
}

# =============================================================================
# SECTION 10: CASH FLOW STATEMENT - OPERATING ACTIVITIES
# =============================================================================

CASH_FLOW_OPERATING_ACTIVITIES = {
    'profit_before_tax': [
        'profit_before_tax',
        'net_profit_before_tax',
        'profit_loss_before_tax',
        'profit_before_tax_from_continuing_operations',
        'profit_before_tax_from_discontinued_operations',
        'loss_before_tax',
    ],
    'adjustments_for_non_cash_items': {
        'depreciation_and_amortization': [
            'depreciation_and_amortization_expense',
            'depreciation_on_property_plant_equipment',
            'depreciation_on_right_of_use_assets',
            'depreciation_on_investment_property',
            'amortization_of_intangible_assets',
            'amortization_of_goodwill',
            'amortization_of_deferred_costs',
            'impairment_of_property_plant_equipment',
            'impairment_of_intangible_assets',
            'impairment_of_goodwill',
            'impairment_of_right_of_use_assets',
            'impairment_of_investment_property',
            'impairment_of_capital_work_in_progress',
            'write_off_of_property_plant_equipment',
            'write_off_of_intangible_assets',
            'write_off_of_capital_work_in_progress',
        ],
        'impairment_and_provisions': [
            'impairment_loss_on_financial_assets',
            'impairment_of_investments',
            'impairment_of_trade_receivables',
            'expected_credit_loss_provision',
            'provision_for_doubtful_debts',
            'provision_for_bad_debts',
            'bad_debts_written_off',
            'provision_for_doubtful_advances',
            'provision_for_diminution_in_investments',
            'provision_for_inventory_obsolescence',
            'provision_for_slow_moving_inventory',
            'inventory_write_down',
            'provision_for_warranties',
            'provision_for_onerous_contracts',
            'provision_for_restructuring',
            'provision_for_site_restoration',
            'provision_for_contingencies',
            'provision_for_litigations',
            'provisions_created',
            'provisions_reversed',
            'provisions_no_longer_required_written_back',
            'liabilities_no_longer_required_written_back',
            'excess_provisions_written_back',
        ],
        'finance_costs_and_income': [
            'finance_costs',
            'interest_expense',
            'interest_on_borrowings',
            'interest_on_lease_liabilities',
            'interest_on_debentures',
            'interest_on_bonds',
            'unwinding_of_discount_on_provisions',
            'borrowing_costs_capitalized',
            'amortization_of_borrowing_costs',
            'interest_income',
            'interest_on_fixed_deposits',
            'interest_on_loans',
            'interest_on_bonds_and_debentures',
            'interest_on_income_tax_refund',
            'dividend_income',
            'dividend_from_subsidiaries',
            'dividend_from_associates',
            'dividend_from_joint_ventures',
            'dividend_from_other_investments',
        ],
        'gains_and_losses_on_assets': [
            'profit_on_sale_of_property_plant_equipment',
            'loss_on_sale_of_property_plant_equipment',
            'profit_on_disposal_of_fixed_assets',
            'loss_on_disposal_of_fixed_assets',
            'profit_on_sale_of_investments',
            'loss_on_sale_of_investments',
            'profit_on_sale_of_current_investments',
            'loss_on_sale_of_current_investments',
            'profit_on_sale_of_non_current_investments',
            'loss_on_sale_of_non_current_investments',
            'gain_on_sale_of_subsidiary',
            'loss_on_sale_of_subsidiary',
            'gain_on_sale_of_associate',
            'loss_on_sale_of_associate',
            'gain_on_sale_of_joint_venture',
            'loss_on_sale_of_joint_venture',
            'gain_on_disposal_of_business',
            'loss_on_disposal_of_business',
            'gain_on_bargain_purchase',
        ],
        'fair_value_changes': [
            'fair_value_gain_on_investments',
            'fair_value_loss_on_investments',
            'fair_value_gain_on_financial_instruments',
            'fair_value_loss_on_financial_instruments',
            'fair_value_gain_on_derivatives',
            'fair_value_loss_on_derivatives',
            'mark_to_market_gain',
            'mark_to_market_loss',
            'unrealized_gain_on_investments',
            'unrealized_loss_on_investments',
            'gain_on_remeasurement_of_contingent_consideration',
            'loss_on_remeasurement_of_contingent_consideration',
        ],
        'foreign_exchange': [
            'unrealized_foreign_exchange_gain',
            'unrealized_foreign_exchange_loss',
            'exchange_difference_on_translation',
            'exchange_fluctuation_gain_loss',
            'foreign_currency_monetary_item_translation_difference',
        ],
        'share_based_payments': [
            'share_based_payment_expense',
            'employee_stock_option_expense',
            'esop_expense',
            'stock_appreciation_rights_expense',
            'sar_expense',
            'employee_share_based_payment_expense',
        ],
        'share_of_profit_loss_of_associates_jv': [
            'share_of_profit_of_associates',
            'share_of_loss_of_associates',
            'share_of_profit_of_joint_ventures',
            'share_of_loss_of_joint_ventures',
            'share_of_profit_loss_of_associates_and_joint_ventures',
        ],
        'other_non_cash_adjustments': [
            'government_grants_income',
            'deferred_revenue_amortization',
            'deferred_government_grants_amortization',
            'amortization_of_lease_incentives',
            'amortization_of_upfront_fees',
            'amortization_of_intangible_assets_acquired_in_business_combination',
            'actuarial_gains_losses',
            'non_cash_rent_expense',
            'straight_lining_of_lease_rent',
            'assets_written_off',
            'loans_written_off',
            'advances_written_off',
            'balances_written_off',
            'sundry_balances_written_back',
            'creditors_written_back',
            'deferred_financing_costs_amortization',
            'premium_on_redemption_of_debentures',
            'discount_on_debentures_amortization',
        ],
    },
    'operating_profit_before_working_capital_changes': [
        'operating_profit_before_working_capital_changes',
        'profit_before_working_capital_changes',
        'cash_generated_from_operations_before_working_capital_changes',
    ],
    'changes_in_working_capital': {
        'changes_in_operating_assets': [
            'decrease_increase_in_trade_receivables',
            'increase_in_trade_receivables',
            'decrease_in_trade_receivables',
            'decrease_increase_in_inventories',
            'increase_in_trade_receivables', # Duplicate in original, keeping it for now or stripping? stripped.
            'increase_in_inventories',
            'decrease_in_inventories',
            'decrease_increase_in_other_current_assets',
            'increase_in_other_current_assets',
            'decrease_in_other_current_assets',
            'decrease_increase_in_other_financial_assets',
            'increase_in_other_financial_assets',
            'decrease_in_other_financial_assets',
            'decrease_increase_in_other_non_current_assets',
            'increase_in_other_non_current_assets',
            'decrease_in_other_non_current_assets',
            'decrease_increase_in_loans',
            'increase_in_loans',
            'decrease_in_loans',
            'decrease_increase_in_contract_assets',
            'increase_in_contract_assets',
            'decrease_in_contract_assets',
            'decrease_increase_in_unbilled_revenue',
            'increase_in_unbilled_revenue',
            'decrease_in_unbilled_revenue',
            'decrease_increase_in_prepaid_expenses',
            'increase_in_prepaid_expenses',
            'decrease_in_prepaid_expenses',
            'decrease_increase_in_advances',
            'increase_in_advances',
            'decrease_in_advances',
        ],
        'changes_in_operating_liabilities': [
            'increase_decrease_in_trade_payables',
            'increase_in_trade_payables',
            'decrease_in_trade_payables',
            'increase_decrease_in_other_current_liabilities',
            'increase_in_other_current_liabilities',
            'decrease_in_other_current_liabilities',
            'increase_decrease_in_other_financial_liabilities',
            'increase_in_other_financial_liabilities',
            'decrease_in_other_financial_liabilities',
            'increase_decrease_in_other_non_current_liabilities',
            'increase_in_other_non_current_liabilities',
            'decrease_in_other_non_current_liabilities',
            'increase_decrease_in_provisions',
            'increase_in_provisions',
            'decrease_in_provisions',
            'increase_decrease_in_contract_liabilities',
            'increase_in_contract_liabilities',
            'decrease_in_contract_liabilities',
            'increase_decrease_in_deferred_revenue',
            'increase_in_deferred_revenue',
            'decrease_in_deferred_revenue',
            'increase_decrease_in_advance_from_customers',
            'increase_in_advance_from_customers',
            'decrease_in_advance_from_customers',
            'increase_decrease_in_employee_benefit_obligations',
            'increase_in_employee_benefit_obligations',
            'decrease_in_employee_benefit_obligations',
        ],
    },
    'cash_generated_from_operations': [
        'cash_generated_from_operations',
        'cash_used_in_operations',
        'net_cash_generated_from_operations',
    ],
    'operating_cash_flow_adjustments': [
        'income_taxes_paid',
        'income_tax_paid',
        'advance_tax_paid',
        'tax_deducted_at_source',
        'tds_paid',
        'income_tax_refund_received',
        'tax_refund_received',
        'gst_paid_net',
        'interest_paid_classified_as_operating',
        'interest_received_classified_as_operating',
        'dividend_received_classified_as_operating',
        'gratuity_paid',
        'employee_benefits_paid',
        'payment_of_contingent_consideration',
        'payment_of_deferred_consideration',
    ],
    'net_cash_from_operating_activities': [
        'net_cash_from_operating_activities',
        'net_cash_used_in_operating_activities',
        'net_cash_generated_from_operating_activities',
        'net_cash_flows_from_operating_activities',
        'cash_flow_from_operating_activities',
    ],
}

# =============================================================================
# SECTION 11: CASH FLOW STATEMENT - INVESTING ACTIVITIES
# =============================================================================

CASH_FLOW_INVESTING_ACTIVITIES = {
    'capital_expenditure': {
        'purchase_of_ppe': [
            'purchase_of_property_plant_equipment',
            'acquisition_of_property_plant_equipment',
            'payment_for_property_plant_equipment',
            'capital_expenditure_on_property_plant_equipment',
            'purchase_of_tangible_assets',
            'acquisition_of_tangible_assets',
            'purchase_of_land',
            'purchase_of_buildings',
            'purchase_of_plant_and_machinery',
            'purchase_of_furniture_and_fixtures',
            'purchase_of_vehicles',
            'purchase_of_office_equipment',
            'purchase_of_computers',
            'capital_work_in_progress_additions',
            'advances_for_capital_expenditure',
            'capital_advances_paid',
        ],
        'purchase_of_intangible_assets': [
            'purchase_of_intangible_assets',
            'acquisition_of_intangible_assets',
            'payment_for_intangible_assets',
            'purchase_of_software',
            'purchase_of_licenses',
            'purchase_of_patents',
            'purchase_of_trademarks',
            'purchase_of_copyrights',
            'purchase_of_technical_knowhow',
            'purchase_of_franchise_rights',
            'intangible_assets_under_development_additions',
            'development_expenditure_capitalized',
            'research_and_development_expenditure_capitalized',
        ],
        'purchase_of_investment_property': [
            'purchase_of_investment_property',
            'acquisition_of_investment_property',
            'payment_for_investment_property',
            'investment_property_under_construction_additions',
        ],
        'purchase_of_biological_assets': [
            'purchase_of_biological_assets',
            'acquisition_of_bearer_plants',
            'purchase_of_plantation_assets',
        ],
    },
    'proceeds_from_sale_of_assets': {
        'sale_of_ppe': [
            'proceeds_from_sale_of_property_plant_equipment',
            'sale_proceeds_from_property_plant_equipment',
            'disposal_of_property_plant_equipment',
            'sale_of_tangible_assets',
            'sale_of_land',
            'sale_of_buildings',
            'sale_of_plant_and_machinery',
            'sale_of_vehicles',
            'sale_of_furniture_and_fixtures',
            'sale_of_office_equipment',
            'insurance_proceeds_on_loss_of_ppe',
            'compensation_for_loss_of_ppe',
        ],
        'sale_of_intangible_assets': [
            'proceeds_from_sale_of_intangible_assets',
            'sale_of_intangible_assets',
            'disposal_of_intangible_assets',
            'sale_of_software',
            'sale_of_licenses',
            'sale_of_patents',
            'sale_of_trademarks',
        ],
        'sale_of_investment_property': [
            'proceeds_from_sale_of_investment_property',
            'sale_of_investment_property',
            'disposal_of_investment_property',
        ],
    },
    'investments': {
        'purchase_of_investments': [
            'purchase_of_investments',
            'acquisition_of_investments',
            'payment_for_investments',
            'purchase_of_non_current_investments',
            'purchase_of_current_investments',
            'investment_in_mutual_funds',
            'investment_in_debt_funds',
            'investment_in_equity_instruments',
            'investment_in_bonds',
            'investment_in_debentures',
            'investment_in_government_securities',
            'investment_in_treasury_bills',
            'investment_in_commercial_paper',
            'investment_in_certificate_of_deposits',
            'investment_in_fixed_deposits',
            'bank_deposits_placed',
            'deposits_placed',
            'margin_money_deposits_placed',
            'earmarked_deposits_placed',
            'investment_in_associates',
            'investment_in_joint_ventures',
            'investment_in_subsidiaries',
            'additional_investment_in_subsidiaries',
            'additional_investment_in_associates',
            'additional_investment_in_joint_ventures',
            'investment_in_partnership_firms',
            'investment_in_llp',
            'investment_in_aif',
            'investment_in_reits',
            'investment_in_invits',
            'investment_in_preference_shares',
        ],
        'proceeds_from_sale_of_investments': [
            'proceeds_from_sale_of_investments',
            'sale_of_investments',
            'disposal_of_investments',
            'redemption_of_investments',
            'maturity_of_investments',
            'proceeds_from_sale_of_non_current_investments',
            'proceeds_from_sale_of_current_investments',
            'redemption_of_mutual_funds',
            'sale_of_mutual_funds',
            'sale_of_bonds',
            'sale_of_debentures',
            'redemption_of_bonds',
            'redemption_of_debentures',
            'maturity_of_fixed_deposits',
            'bank_deposits_matured',
            'deposits_matured',
            'margin_money_deposits_matured',
            'sale_of_government_securities',
            'maturity_of_commercial_paper',
            'maturity_of_certificate_of_deposits',
            'sale_of_investment_in_associates',
            'sale_of_investment_in_joint_ventures',
            'sale_of_investment_in_subsidiaries',
            'proceeds_from_divestment',
            'proceeds_from_partial_divestment',
            'return_of_capital_from_investments',
        ],
    },
    'business_combinations': {
        'acquisition_of_businesses': [
            'acquisition_of_subsidiaries',
            'acquisition_of_business',
            'payment_for_acquisition_of_subsidiaries',
            'payment_for_acquisition_of_business',
            'cash_paid_for_acquisition_of_subsidiaries',
            'cash_paid_for_acquisition_of_business',
            'acquisition_of_subsidiaries_net_of_cash_acquired',
            'cash_acquired_on_acquisition_of_subsidiaries',
            'net_cash_outflow_on_acquisition_of_subsidiaries',
            'payment_of_contingent_consideration',
            'payment_of_deferred_consideration',
            'acquisition_of_controlling_interest',
            'acquisition_of_additional_stake_in_subsidiaries',
            'acquisition_of_minority_interest',
            'acquisition_of_non_controlling_interest',
        ],
        'disposal_of_businesses': [
            'disposal_of_subsidiaries',
            'sale_of_subsidiaries',
            'disposal_of_business',
            'sale_of_business',
            'sale_of_undertaking',
            'proceeds_from_disposal_of_subsidiaries',
            'proceeds_from_sale_of_subsidiaries',
            'proceeds_from_disposal_of_business',
            'cash_received_on_disposal_of_subsidiaries',
            'disposal_of_subsidiaries_net_of_cash_disposed',
            'cash_disposed_on_sale_of_subsidiaries',
            'net_cash_inflow_on_disposal_of_subsidiaries',
            'receipt_of_contingent_consideration',
            'receipt_of_deferred_consideration',
            'proceeds_from_slump_sale',
            'proceeds_from_demerger',
            'sale_of_stake_in_subsidiaries',
            'sale_of_stake_in_associates',
            'sale_of_stake_in_joint_ventures',
        ],
    },
    'loans_and_advances': {
        'loans_given': [
            'loans_given',
            'loans_advanced',
            'inter_corporate_deposits_given',
            'loans_to_related_parties',
            'loans_to_subsidiaries',
            'loans_to_associates',
            'loans_to_joint_ventures',
            'loans_to_employees',
            'loans_to_directors',
            'loans_to_kmp',
            'advances_for_investments',
            'deposits_given',
            'security_deposits_paid',
        ],
        'loans_repaid': [
            'loans_repaid',
            'repayment_of_loans_given',
            'inter_corporate_deposits_received_back',
            'loans_received_back_from_related_parties',
            'loans_received_back_from_subsidiaries',
            'loans_received_back_from_associates',
            'loans_received_back_from_joint_ventures',
            'loans_received_back_from_employees',
            'recovery_of_loans',
            'deposits_received_back',
            'security_deposits_received_back',
            'refund_of_deposits',
        ],
    },
    'interest_and_dividend': [
        'interest_received',
        'interest_income_received',
        'interest_on_fixed_deposits_received',
        'interest_on_loans_received',
        'interest_on_bonds_received',
        'interest_on_debentures_received',
        'interest_on_government_securities_received',
        'dividend_received',
        'dividend_from_subsidiaries_received',
        'dividend_from_associates_received',
        'dividend_from_joint_ventures_received',
        'dividend_from_investments_received',
        'return_on_investments_received',
    ],
    'other_investing_activities': [
        'government_grants_received_for_capital_assets',
        'capital_subsidy_received',
        'insurance_proceeds_received',
        'compensation_received_for_assets',
        'proceeds_from_settlement_of_claims',
        'exploration_and_evaluation_expenditure',
        'development_expenditure',
        'mine_development_expenditure',
        'oil_and_gas_exploration_expenditure',
    ],
    'net_cash_from_investing_activities': [
        'net_cash_from_investing_activities',
        'net_cash_used_in_investing_activities',
        'net_cash_generated_from_investing_activities',
        'net_cash_flows_from_investing_activities',
        'cash_flow_from_investing_activities',
    ],
}

# =============================================================================
# SECTION 12: CASH FLOW STATEMENT - FINANCING ACTIVITIES
# =============================================================================

CASH_FLOW_FINANCING_ACTIVITIES = {
    'proceeds_from_borrowings': {
        'long_term_borrowings': [
            'proceeds_from_long_term_borrowings',
            'proceeds_from_term_loans',
            'term_loan_availed',
            'term_loan_from_banks',
            'term_loan_from_financial_institutions',
            'term_loan_from_other_parties',
            'rupee_term_loan_availed',
            'foreign_currency_term_loan_availed',
            'external_commercial_borrowings_availed',
            'ecb_availed',
            'proceeds_from_issue_of_debentures',
            'issue_of_debentures',
            'issue_of_non_convertible_debentures',
            'issue_of_secured_debentures',
            'issue_of_unsecured_debentures',
            'proceeds_from_issue_of_bonds',
            'issue_of_bonds',
            'issue_of_secured_bonds',
            'issue_of_unsecured_bonds',
            'issue_of_infrastructure_bonds',
            'issue_of_zero_coupon_bonds',
            'public_deposits_received',
            'deposits_accepted',
            'inter_corporate_deposits_received',
            'loans_from_related_parties',
            'loans_from_directors',
            'loans_from_promoters',
            'borrowings_from_subsidiaries',
            'borrowings_from_associates',
            'borrowings_from_joint_ventures',
            'vehicle_loans_availed',
            'equipment_loans_availed',
            'proceeds_from_subordinated_debt',
            'proceeds_from_perpetual_debt',
        ],
        'short_term_borrowings': [
            'proceeds_from_short_term_borrowings',
            'short_term_loans_availed',
            'cash_credit_availed',
            'overdraft_availed',
            'bank_overdraft_availed',
            'working_capital_loans_availed',
            'working_capital_demand_loan',
            'packing_credit_availed',
            'export_credit_availed',
            'pre_shipment_credit_availed',
            'post_shipment_credit_availed',
            'bills_discounted',
            'buyers_credit_availed',
            'commercial_paper_issued',
            'short_term_loans_from_banks',
            'short_term_loans_from_financial_institutions',
            'short_term_inter_corporate_deposits',
            'bridge_loans_availed',
            'demand_loans_availed',
        ],
    },
    'repayment_of_borrowings': {
        'long_term_borrowings': [
            'repayment_of_long_term_borrowings',
            'repayment_of_term_loans',
            'term_loan_repaid',
            'repayment_of_term_loan_to_banks',
            'repayment_of_term_loan_to_financial_institutions',
            'repayment_of_ecb',
            'repayment_of_external_commercial_borrowings',
            'redemption_of_debentures',
            'repayment_of_debentures',
            'redemption_of_non_convertible_debentures',
            'redemption_of_bonds',
            'repayment_of_bonds',
            'repayment_of_public_deposits',
            'deposits_repaid',
            'inter_corporate_deposits_repaid',
            'repayment_of_loans_from_related_parties',
            'repayment_of_loans_from_directors',
            'repayment_of_vehicle_loans',
            'repayment_of_equipment_loans',
            'prepayment_of_term_loans',
            'prepayment_of_borrowings',
        ],
        'short_term_borrowings': [
            'repayment_of_short_term_borrowings',
            'short_term_loans_repaid',
            'cash_credit_repaid',
            'overdraft_repaid',
            'working_capital_loans_repaid',
            'packing_credit_repaid',
            'bills_discounting_repaid',
            'buyers_credit_repaid',
            'commercial_paper_redeemed',
            'repayment_of_commercial_paper',
            'net_increase_decrease_in_short_term_borrowings',
            'net_movement_in_working_capital_borrowings',
            'net_movement_in_short_term_borrowings',
        ],
    },
    'lease_payments': [
        'payment_of_lease_liabilities',
        'principal_payment_on_lease_liabilities',
        'repayment_of_lease_liabilities',
        'payment_of_principal_portion_of_lease_liabilities',
        'payment_of_finance_lease_liabilities',
        'capital_lease_payments',
        'hire_purchase_payments',
    ],
    'share_capital_transactions': {
        'proceeds_from_issue_of_shares': [
            'proceeds_from_issue_of_equity_shares',
            'proceeds_from_issue_of_share_capital',
            'issue_of_equity_shares',
            'proceeds_from_ipo',
            'proceeds_from_initial_public_offer',
            'proceeds_from_fpo',
            'proceeds_from_follow_on_public_offer',
            'proceeds_from_rights_issue',
            'proceeds_from_preferential_allotment',
            'proceeds_from_private_placement',
            'proceeds_from_qualified_institutional_placement',
            'proceeds_from_qip',
            'proceeds_from_exercise_of_stock_options',
            'proceeds_from_exercise_of_employee_stock_options',
            'proceeds_from_esop_exercise',
            'proceeds_from_issue_of_preference_shares',
            'issue_of_preference_shares',
            'proceeds_from_conversion_of_warrants',
            'share_application_money_received',
            'money_received_against_share_warrants',
            'share_issue_expenses_paid',
            'issue_expenses_paid',
            'proceeds_from_issue_of_shares_net_of_issue_expenses',
        ],
        'buyback_and_capital_reduction': [
            'payment_for_buyback_of_shares',
            'buyback_of_shares',
            'buyback_of_equity_shares',
            'payment_for_share_buyback',
            'buyback_expenses_paid',
            'capital_reduction_payment',
            'return_of_capital',
            'redemption_of_preference_shares',
            'payment_for_redemption_of_preference_shares',
        ],
    },
    'transactions_with_non_controlling_interests': [
        'acquisition_of_non_controlling_interests',
        'acquisition_of_additional_stake_from_nci',
        'acquisition_of_minority_interest',
        'payment_for_acquisition_of_nci',
        'proceeds_from_sale_of_stake_to_nci',
        'sale_of_stake_to_non_controlling_interests',
        'capital_contribution_from_nci',
        'capital_contribution_from_minority_shareholders',
    ],
    'dividend_payments': [
        'dividend_paid',
        'dividends_paid',
        'payment_of_dividends',
        'dividend_on_equity_shares_paid',
        'interim_dividend_paid',
        'final_dividend_paid',
        'special_dividend_paid',
        'dividend_on_preference_shares_paid',
        'preference_dividend_paid',
        'dividend_distribution_tax_paid',
        'tax_on_dividend_paid',
        'dividend_paid_to_non_controlling_interests',
        'dividend_paid_to_minority_shareholders',
    ],
    'interest_payments': [
        'interest_paid',
        'finance_costs_paid',
        'interest_on_borrowings_paid',
        'interest_on_term_loans_paid',
        'interest_on_debentures_paid',
        'interest_on_bonds_paid',
        'interest_on_lease_liabilities_paid',
        'interest_paid_on_lease_liabilities',
        'other_finance_costs_paid',
        'bank_charges_paid',
        'loan_processing_fees_paid',
    ],
    'other_financing_activities': [
        'contribution_to_share_based_payment_trust',
        'payment_to_esop_trust',
        'proceeds_from_government_grants_for_financing',
        'capital_subsidy_received',
        'receipt_of_government_grants',
        'security_deposits_received',
        'security_deposits_refunded',
        'margin_money_received',
        'margin_money_refunded',
    ],
    'net_cash_from_financing_activities': [
        'net_cash_from_financing_activities',
        'net_cash_used_in_financing_activities',
        'net_cash_generated_from_financing_activities',
        'net_cash_flows_from_financing_activities',
        'cash_flow_from_financing_activities',
    ],
}

# =============================================================================
# CASH FLOW STATEMENT - RECONCILIATION AND TOTALS
# =============================================================================

CASH_FLOW_RECONCILIATION = {
    'net_change_in_cash': [
        'net_increase_in_cash_and_cash_equivalents',
        'net_decrease_in_cash_and_cash_equivalents',
        'net_increase_decrease_in_cash_and_cash_equivalents',
        'net_change_in_cash_and_cash_equivalents',
        'net_cash_flow',
    ],
    'opening_cash_and_cash_equivalents': [
        'cash_and_cash_equivalents_at_beginning_of_period',
        'cash_and_cash_equivalents_at_beginning_of_year',
        'opening_cash_and_cash_equivalents',
        'opening_balance_of_cash_and_cash_equivalents',
        'cash_at_beginning_of_period',
        'cash_at_beginning_of_year',
    ],
    'closing_cash_and_cash_equivalents': [
        'cash_and_cash_equivalents_at_end_of_period',
        'cash_and_cash_equivalents_at_end_of_year',
        'closing_cash_and_cash_equivalents',
        'closing_balance_of_cash_and_cash_equivalents',
        'cash_at_end_of_period',
        'cash_at_end_of_year',
    ],
    'effect_of_exchange_rate_changes': [
        'effect_of_exchange_rate_changes_on_cash_and_cash_equivalents',
        'effect_of_foreign_exchange_rate_changes',
        'exchange_difference_on_cash_and_cash_equivalents',
        'exchange_rate_effect_on_cash_and_cash_equivalents',
        'translation_adjustment_on_cash_and_cash_equivalents',
        'effect_of_exchange_rate_fluctuations',
    ],
    'cash_and_cash_equivalents_of_discontinued_operations': [
        'cash_flows_from_discontinued_operations',
        'net_cash_from_discontinued_operations',
        'cash_and_cash_equivalents_of_disposal_group',
        'cash_and_cash_equivalents_included_in_held_for_sale',
    ],
    'cash_flow_components': [
        'cash_on_hand_at_end_of_period',
        'balances_with_banks_at_end_of_period',
        'balances_in_current_accounts',
        'balances_in_deposit_accounts',
        'short_term_deposits',
        'highly_liquid_investments_at_end_of_period',
        'bank_overdraft_deducted',
        'cash_credit_deducted',
        'restricted_cash',
        'unrestricted_cash',
    ],
}

# =============================================================================
# SECTION 13: STATEMENT OF CHANGES IN EQUITY
# =============================================================================

STATEMENT_OF_CHANGES_IN_EQUITY = {
    'equity_share_capital_changes': {
        'opening_balance': [
            'balance_at_beginning_of_period',
            'balance_at_beginning_of_year',
            'opening_balance_of_equity_share_capital',
            'equity_share_capital_at_beginning_of_period',
            'equity_share_capital_at_beginning_of_year',
            'shares_outstanding_at_beginning_of_period',
            'number_of_shares_at_beginning_of_period',
        ],
        'changes_during_period': [
            'changes_in_equity_share_capital_during_period',
            'changes_in_equity_share_capital_during_year',
            'shares_issued_during_period',
            'fresh_issue_of_shares',
            'issue_of_equity_shares',
            'shares_issued_on_exercise_of_options',
            'shares_issued_under_esop',
            'shares_issued_on_conversion_of_debentures',
            'shares_issued_on_conversion_of_warrants',
            'shares_issued_on_conversion_of_preference_shares',
            'shares_issued_on_conversion_of_bonds',
            'shares_issued_under_rights_issue',
            'shares_issued_under_preferential_allotment',
            'shares_issued_under_private_placement',
            'shares_issued_under_qip',
            'bonus_shares_issued',
            'shares_issued_on_amalgamation',
            'shares_issued_on_merger',
            'shares_issued_on_demerger',
            'shares_issued_for_consideration_other_than_cash',
            'shares_issued_pursuant_to_scheme_of_arrangement',
            'shares_bought_back',
            'buyback_of_equity_shares',
            'reduction_of_share_capital',
            'shares_cancelled',
            'shares_forfeited',
            'shares_extinguished',
        ],
        'closing_balance': [
            'balance_at_end_of_period',
            'balance_at_end_of_year',
            'closing_balance_of_equity_share_capital',
            'equity_share_capital_at_end_of_period',
            'equity_share_capital_at_end_of_year',
            'shares_outstanding_at_end_of_period',
            'number_of_shares_at_end_of_period',
        ],
    },
    'other_equity_changes': {
        'reserves_and_surplus': {
            'capital_reserve': [
                'capital_reserve_opening_balance',
                'additions_to_capital_reserve',
                'transfer_to_capital_reserve',
                'capital_reserve_on_consolidation',
                'capital_reserve_on_amalgamation',
                'capital_reserve_on_forfeiture',
                'capital_reserve_on_cancellation_of_shares',
                'utilization_of_capital_reserve',
                'transfer_from_capital_reserve',
                'capital_reserve_closing_balance',
            ],
            'securities_premium': [
                'securities_premium_opening_balance',
                'premium_on_issue_of_shares',
                'premium_on_exercise_of_esop',
                'premium_on_conversion_of_debentures',
                'premium_on_conversion_of_warrants',
                'premium_on_qip_issue',
                'premium_on_preferential_allotment',
                'utilization_of_securities_premium',
                'share_issue_expenses_adjusted',
                'premium_on_buyback_of_shares',
                'premium_payable_on_redemption_of_debentures',
                'securities_premium_closing_balance',
            ],
            'general_reserve': [
                'general_reserve_opening_balance',
                'transfer_to_general_reserve',
                'transfer_from_retained_earnings_to_general_reserve',
                'transfer_from_general_reserve',
                'utilization_of_general_reserve',
                'general_reserve_closing_balance',
            ],
            'retained_earnings': [
                'retained_earnings_opening_balance',
                'surplus_opening_balance',
                'profit_for_the_period',
                'profit_for_the_year',
                'loss_for_the_period',
                'loss_for_the_year',
                'transfer_to_reserves',
                'transfer_to_general_reserve',
                'transfer_to_capital_redemption_reserve',
                'transfer_to_debenture_redemption_reserve',
                'transfer_to_special_reserve',
                'transfer_to_statutory_reserve',
                'transfer_from_reserves',
                'transfer_from_debenture_redemption_reserve',
                'dividend_paid',
                'interim_dividend_paid',
                'final_dividend_paid',
                'dividend_distribution_tax',
                'tax_on_dividend',
                'buyback_of_shares',
                'premium_on_buyback',
                'transaction_costs_on_buyback',
                'share_based_payment_expense_recognized',
                'exercise_of_stock_options',
                'lapse_of_stock_options',
                'remeasurement_of_defined_benefit_plans',
                'actuarial_gains_losses_transferred',
                'adjustment_on_account_of_change_in_accounting_policy',
                'adjustment_on_account_of_prior_period_errors',
                'effect_of_change_in_accounting_estimate',
                'ind_as_transition_adjustments',
                'opening_balance_adjustments',
                'retained_earnings_closing_balance',
                'surplus_closing_balance',
            ],
            'capital_redemption_reserve': [
                'capital_redemption_reserve_opening_balance',
                'transfer_to_capital_redemption_reserve',
                'transfer_on_buyback_of_shares',
                'transfer_on_redemption_of_preference_shares',
                'utilization_of_capital_redemption_reserve',
                'capital_redemption_reserve_closing_balance',
            ],
            'debenture_redemption_reserve': [
                'debenture_redemption_reserve_opening_balance',
                'transfer_to_debenture_redemption_reserve',
                'transfer_for_drr',
                'utilization_of_debenture_redemption_reserve',
                'transfer_from_drr_on_redemption',
                'debenture_redemption_reserve_closing_balance',
            ],
            'share_options_outstanding': [
                'share_options_outstanding_opening_balance',
                'employee_stock_option_reserve_opening',
                'esop_reserve_opening_balance',
                'share_based_payment_expense',
                'options_granted_during_period',
                'options_exercised_during_period',
                'transfer_to_securities_premium_on_exercise',
                'options_lapsed_during_period',
                'options_forfeited_during_period',
                'options_cancelled_during_period',
                'share_options_outstanding_closing_balance',
                'employee_stock_option_reserve_closing',
                'esop_reserve_closing_balance',
            ],
            'other_reserves': [
                'special_reserve_opening_balance',
                'statutory_reserve_opening_balance',
                'tonnage_tax_reserve_opening_balance',
                'investment_allowance_reserve_opening_balance',
                'transfer_to_special_reserve',
                'transfer_to_statutory_reserve',
                'utilization_of_special_reserve',
                'special_reserve_closing_balance',
                'statutory_reserve_closing_balance',
            ],
        },
        'other_comprehensive_income_reserves': {
            'fvoci_equity_instruments_reserve': [
                'fvoci_equity_reserve_opening_balance',
                'fair_value_changes_on_equity_instruments',
                'gain_on_equity_instruments_at_fvoci',
                'loss_on_equity_instruments_at_fvoci',
                'transfer_to_retained_earnings_on_disposal',
                'deferred_tax_on_fvoci_equity_instruments',
                'fvoci_equity_reserve_closing_balance',
            ],
            'fvoci_debt_instruments_reserve': [
                'fvoci_debt_reserve_opening_balance',
                'fair_value_changes_on_debt_instruments',
                'gain_on_debt_instruments_at_fvoci',
                'loss_on_debt_instruments_at_fvoci',
                'reclassified_to_profit_or_loss_on_sale',
                'reclassified_to_profit_or_loss_on_impairment',
                'deferred_tax_on_fvoci_debt_instruments',
                'fvoci_debt_reserve_closing_balance',
            ],
            'cash_flow_hedge_reserve': [
                'cash_flow_hedge_reserve_opening_balance',
                'effective_portion_of_cash_flow_hedges',
                'gain_on_cash_flow_hedging_instruments',
                'loss_on_cash_flow_hedging_instruments',
                'reclassified_to_profit_or_loss',
                'reclassified_to_carrying_amount_of_hedged_item',
                'basis_adjustments',
                'deferred_tax_on_cash_flow_hedges',
                'cash_flow_hedge_reserve_closing_balance',
            ],
            'cost_of_hedging_reserve': [
                'cost_of_hedging_reserve_opening_balance',
                'changes_in_cost_of_hedging',
                'forward_element_of_forward_contracts',
                'time_value_of_options',
                'foreign_currency_basis_spread',
                'amortisation_to_profit_or_loss',
                'cost_of_hedging_reserve_closing_balance',
            ],
            'revaluation_surplus': [
                'revaluation_surplus_opening_balance',
                'revaluation_gain_during_period',
                'revaluation_loss_during_period',
                'transfer_to_retained_earnings_on_disposal',
                'transfer_to_retained_earnings_on_depreciation',
                'deferred_tax_on_revaluation',
                'revaluation_surplus_closing_balance',
            ],
            'foreign_currency_translation_reserve': [
                'fctr_opening_balance',
                'foreign_currency_translation_reserve_opening',
                'exchange_differences_on_translation',
                'exchange_differences_arising_during_period',
                'reclassified_to_profit_or_loss_on_disposal',
                'fctr_closing_balance',
                'foreign_currency_translation_reserve_closing',
            ],
            'actuarial_gains_losses_reserve': [
                'actuarial_reserve_opening_balance',
                'remeasurement_of_defined_benefit_plans',
                'actuarial_gains_during_period',
                'actuarial_losses_during_period',
                'return_on_plan_assets_excluding_interest',
                'deferred_tax_on_actuarial_gains_losses',
                'transfer_to_retained_earnings',
                'actuarial_reserve_closing_balance',
            ],
        },
        'share_of_oci_of_associates_jv': [
            'share_of_oci_of_associates_opening',
            'share_of_oci_of_joint_ventures_opening',
            'share_of_oci_during_period',
            'reclassified_on_disposal',
            'share_of_oci_of_associates_closing',
            'share_of_oci_of_joint_ventures_closing',
        ],
    },
    'equity_attributable_to_owners': [
        'total_equity_attributable_to_owners_of_parent',
        'equity_attributable_to_equity_holders_of_parent',
        'total_equity_of_parent',
    ],
    'non_controlling_interests': {
        'nci_changes': [
            'non_controlling_interests_opening_balance',
            'minority_interest_opening_balance',
            'profit_attributable_to_nci',
            'loss_attributable_to_nci',
            'oci_attributable_to_nci',
            'total_comprehensive_income_attributable_to_nci',
            'dividend_paid_to_nci',
            'acquisition_of_nci',
            'disposal_of_nci',
            'capital_contribution_by_nci',
            'capital_withdrawal_by_nci',
            'nci_arising_on_business_combination',
            'nci_on_acquisition_of_subsidiary',
            'nci_disposed_on_sale_of_subsidiary',
            'change_in_ownership_without_loss_of_control',
            'non_controlling_interests_closing_balance',
            'minority_interest_closing_balance',
        ],
    },
    'total_equity': [
        'total_equity_opening_balance',
        'total_comprehensive_income_for_period',
        'transactions_with_owners',
        'issue_of_share_capital',
        'buyback_of_shares',
        'dividends_to_equity_holders',
        'share_based_payments',
        'changes_in_ownership_interests_in_subsidiaries',
        'total_equity_closing_balance',
    ],
}

# =============================================================================
# SECTION 14: PROPERTY, PLANT AND EQUIPMENT (PPE) NOTES
# =============================================================================

PPE_NOTES = {
    'ppe_categories': [
        'land_freehold',
        'land_leasehold',
        'buildings',
        'factory_buildings',
        'office_buildings',
        'residential_buildings',
        'buildings_on_leasehold_land',
        'plant_and_machinery',
        'plant_and_equipment',
        'electrical_installations',
        'electrical_equipment',
        'furniture_and_fixtures',
        'furniture_and_fittings',
        'office_equipment',
        'computers',
        'computer_equipment',
        'servers_and_networks',
        'data_processing_equipment',
        'vehicles',
        'motor_vehicles',
        'motor_cars',
        'trucks_and_lorries',
        'two_wheelers',
        'aircraft',
        'ships_and_vessels',
        'boats',
        'railway_sidings',
        'railway_wagons',
        'tools_and_implements',
        'dies_and_moulds',
        'patterns',
        'jigs_and_fixtures',
        'laboratory_equipment',
        'scientific_instruments',
        'medical_equipment',
        'hospital_equipment',
        'research_equipment',
        'telecommunication_equipment',
        'broadcasting_equipment',
        'studio_equipment',
        'mining_equipment',
        'drilling_equipment',
        'oil_and_gas_equipment',
        'pipelines',
        'storage_tanks',
        'silos',
        'cold_storage',
        'refrigeration_equipment',
        'air_conditioning_equipment',
        'hvac_equipment',
        'fire_fighting_equipment',
        'security_equipment',
        'pollution_control_equipment',
        'effluent_treatment_plant',
        'water_treatment_plant',
        'power_generation_equipment',
        'generators',
        'transformers',
        'solar_panels',
        'wind_turbines',
        'cranes',
        'hoists',
        'forklifts',
        'material_handling_equipment',
        'conveyor_systems',
        'packaging_equipment',
        'printing_equipment',
        'textile_machinery',
        'food_processing_equipment',
        'agricultural_equipment',
        'tractors',
        'harvesters',
        'irrigation_equipment',
        'livestock_equipment',
        'poultry_equipment',
        'dairy_equipment',
        'roads_and_bridges',
        'culverts',
        'runways',
        'jetties',
        'wharves',
        'docks',
        'temporary_structures',
        'sheds',
        'canteens',
        'guest_houses',
        'clubs',
        'schools',
        'hospitals',
        'leasehold_improvements',
        'bearer_plants',
        'assets_under_finance_lease',
        'assets_given_on_operating_lease',
    ],
    'gross_block_movements': {
        'opening_gross_block': [
            'gross_block_at_beginning_of_period',
            'gross_carrying_amount_opening',
            'cost_at_beginning_of_year',
            'deemed_cost_at_beginning_of_year',
            'opening_balance_gross_block',
        ],
        'additions': [
            'additions_during_period',
            'additions_during_year',
            'acquisitions',
            'purchases',
            'assets_purchased',
            'assets_constructed',
            'self_constructed_assets',
            'assets_capitalized',
            'transfer_from_cwip',
            'borrowing_costs_capitalized',
            'assets_acquired_through_business_combination',
            'assets_acquired_on_amalgamation',
            'assets_acquired_on_merger',
        ],
        'disposals': [
            'disposals_during_period',
            'disposals_during_year',
            'assets_sold',
            'assets_disposed',
            'assets_discarded',
            'assets_written_off',
            'assets_scrapped',
            'assets_demolished',
            'assets_lost',
            'assets_stolen',
            'assets_destroyed',
            'assets_transferred',
            'assets_reclassified_to_held_for_sale',
            'disposal_of_subsidiary',
        ],
        'other_adjustments': [
            'revaluation_increase',
            'revaluation_decrease',
            'reversal_of_impairment',
            'exchange_differences',
            'foreign_currency_translation',
            'reclassifications',
            'transfers_between_categories',
            'adjustments_on_transition',
            'prior_period_adjustments',
            'other_adjustments',
        ],
        'closing_gross_block': [
            'gross_block_at_end_of_period',
            'gross_carrying_amount_closing',
            'cost_at_end_of_year',
            'closing_balance_gross_block',
        ],
    },
    'accumulated_depreciation_movements': {
        'opening_accumulated_depreciation': [
            'accumulated_depreciation_at_beginning',
            'accumulated_depreciation_opening',
            'depreciation_at_beginning_of_year',
            'opening_balance_accumulated_depreciation',
        ],
        'depreciation_for_period': [
            'depreciation_for_the_period',
            'depreciation_for_the_year',
            'depreciation_charge',
            'depreciation_expense',
            'charge_for_the_year',
        ],
        'impairment': [
            'impairment_loss_recognized',
            'impairment_for_the_period',
            'reversal_of_impairment_loss',
            'impairment_reversal',
        ],
        'disposals': [
            'depreciation_on_disposals',
            'depreciation_eliminated_on_disposal',
            'accumulated_depreciation_on_assets_sold',
            'accumulated_depreciation_on_assets_discarded',
            'accumulated_depreciation_on_assets_written_off',
        ],
        'other_adjustments': [
            'exchange_differences_on_depreciation',
            'foreign_currency_translation_on_depreciation',
            'reclassifications_of_depreciation',
            'adjustments_on_revaluation',
            'other_adjustments_to_depreciation',
        ],
        'closing_accumulated_depreciation': [
            'accumulated_depreciation_at_end',
            'accumulated_depreciation_closing',
            'depreciation_at_end_of_year',
            'closing_balance_accumulated_depreciation',
        ],
    },
    'net_block': [
        'net_block',
        'net_carrying_amount',
        'net_carrying_value',
        'net_book_value',
        'written_down_value',
        'wdv',
        'carrying_amount_at_beginning',
        'carrying_amount_at_end',
    ],
    'capital_work_in_progress': {
        'cwip_movements': [
            'cwip_at_beginning_of_period',
            'cwip_opening_balance',
            'additions_to_cwip',
            'expenditure_during_construction',
            'borrowing_costs_capitalized_to_cwip',
            'preoperative_expenses_capitalized',
            'trial_run_expenses',
            'capitalized_during_period',
            'transfer_to_fixed_assets',
            'impairment_of_cwip',
            'write_off_of_cwip',
            'cwip_at_end_of_period',
            'cwip_closing_balance',
        ],
        'cwip_ageing': [
            'cwip_less_than_1_year',
            'cwip_1_to_2_years',
            'cwip_2_to_3_years',
            'cwip_more_than_3_years',
            'projects_in_progress',
            'projects_temporarily_suspended',
        ],
        'cwip_completion_schedule': [
            'expected_completion_date',
            'estimated_cost_to_complete',
            'cost_incurred_till_date',
            'cost_overrun',
            'time_overrun',
        ],
    },
    'ppe_disclosures': {
        'measurement_basis': [
            'cost_model',
            'revaluation_model',
            'deemed_cost_on_transition',
            'fair_value_as_deemed_cost',
        ],
        'depreciation_methods': [
            'straight_line_method',
            'slm',
            'written_down_value_method',
            'wdv_method',
            'units_of_production_method',
            'depletion_method',
            'sum_of_years_digits_method',
            'double_declining_balance_method',
        ],
        'useful_lives': [
            'useful_life_of_buildings',
            'useful_life_of_plant_and_machinery',
            'useful_life_of_furniture',
            'useful_life_of_vehicles',
            'useful_life_of_computers',
            'useful_life_of_office_equipment',
            'residual_value',
            'estimated_useful_life',
            'remaining_useful_life',
            'review_of_useful_life',
            'change_in_useful_life',
        ],
        'restrictions_and_pledges': [
            'assets_pledged_as_security',
            'assets_under_hypothecation',
            'assets_under_mortgage',
            'assets_under_lien',
            'restrictions_on_title',
            'restrictions_on_disposal',
            'contractual_commitments_for_acquisition',
            'capital_commitments',
        ],
        'revaluation': [
            'date_of_revaluation',
            'name_of_valuer',
            'revaluation_surplus',
            'revaluation_deficit',
            'carrying_amount_under_cost_model',
        ],
        'impairment': [
            'impairment_indicators',
            'recoverable_amount',
            'value_in_use',
            'fair_value_less_costs_to_sell',
            'discount_rate_for_value_in_use',
            'impairment_loss_recognized_in_pl',
            'impairment_loss_recognized_in_oci',
            'reversal_of_impairment_loss',
            'cash_generating_unit',
        ],
        'borrowing_costs': [
            'borrowing_costs_capitalized_during_period',
            'capitalization_rate_used',
            'qualifying_assets',
        ],
    },
}

# =============================================================================
# SECTION 15: INTANGIBLE ASSETS NOTES
# =============================================================================

INTANGIBLE_ASSETS_NOTES = {
    'intangible_asset_categories': [
        'goodwill',
        'computer_software',
        'software_licenses',
        'erp_software',
        'application_software',
        'operating_system_software',
        'internally_developed_software',
        'purchased_software',
        'software_under_development',
        'patents',
        'copyrights',
        'trademarks',
        'trade_names',
        'brand_names',
        'brand_value',
        'logos',
        'domain_names',
        'internet_domains',
        'franchise_rights',
        'licenses',
        'license_to_operate',
        'mining_rights',
        'mining_licenses',
        'exploration_rights',
        'extraction_rights',
        'oil_and_gas_rights',
        'water_rights',
        'fishing_rights',
        'spectrum_license',
        'telecom_licenses',
        'broadcasting_rights',
        'broadcasting_licenses',
        'route_permits',
        'operating_permits',
        'environmental_permits',
        'import_licenses',
        'export_licenses',
        'technical_knowhow',
        'technology',
        'proprietary_technology',
        'process_technology',
        'product_technology',
        'manufacturing_technology',
        'recipes_formulas',
        'formulations',
        'designs',
        'drawings',
        'blueprints',
        'prototypes',
        'customer_relationships',
        'customer_contracts',
        'customer_lists',
        'customer_database',
        'order_backlog',
        'contract_based_intangibles',
        'non_compete_agreements',
        'non_compete_covenants',
        'employment_contracts',
        'favorable_contracts',
        'marketing_related_intangibles',
        'advertising_campaigns',
        'newspaper_mastheads',
        'publication_titles',
        'magazine_titles',
        'artistic_related_intangibles',
        'music_rights',
        'music_copyrights',
        'film_rights',
        'film_copyrights',
        'video_rights',
        'television_programs',
        'literary_works',
        'manuscripts',
        'pictures',
        'photographs',
        'motion_pictures',
        'audiovisual_material',
        'contract_rights',
        'leasehold_rights',
        'use_rights',
        'servicing_rights',
        'mortgage_servicing_rights',
        'favorable_lease_agreements',
        'airport_slots',
        'distribution_rights',
        'agency_rights',
        'development_costs',
        'product_development_costs',
        'website_development_costs',
        'internally_generated_intangibles',
        'research_costs',
        'development_expenditure',
    ],
    'gross_block_movements': {
        'opening_gross_block': [
            'intangible_assets_gross_block_opening',
            'cost_at_beginning_of_year',
            'gross_carrying_amount_opening',
            'opening_balance_intangible_assets',
        ],
        'additions': [
            'additions_during_period',
            'additions_during_year',
            'acquisitions_of_intangible_assets',
            'internally_generated_additions',
            'externally_acquired_additions',
            'assets_acquired_through_business_combination',
            'assets_acquired_on_amalgamation',
            'transfer_from_intangible_assets_under_development',
            'development_costs_capitalized',
            'borrowing_costs_capitalized',
        ],
        'disposals': [
            'disposals_during_period',
            'disposals_during_year',
            'assets_sold',
            'assets_written_off',
            'assets_expired',
            'assets_abandoned',
            'assets_reclassified',
        ],
        'other_adjustments': [
            'exchange_differences',
            'foreign_currency_translation',
            'revaluation_increase',
            'revaluation_decrease',
            'reclassifications',
            'other_adjustments',
        ],
        'closing_gross_block': [
            'intangible_assets_gross_block_closing',
            'cost_at_end_of_year',
            'gross_carrying_amount_closing',
            'closing_balance_intangible_assets',
        ],
    },
    'accumulated_amortization_movements': {
        'opening_accumulated_amortization': [
            'accumulated_amortization_at_beginning',
            'accumulated_amortization_opening',
            'amortization_at_beginning_of_year',
            'opening_balance_accumulated_amortization',
        ],
        'amortization_for_period': [
            'amortization_for_the_period',
            'amortization_for_the_year',
            'amortization_charge',
            'amortization_expense',
            'charge_for_the_year',
        ],
        'impairment': [
            'impairment_loss_recognized',
            'impairment_for_the_period',
            'reversal_of_impairment_loss',
        ],
        'disposals': [
            'amortization_on_disposals',
            'amortization_eliminated_on_disposal',
            'accumulated_amortization_on_assets_sold',
            'accumulated_amortization_on_assets_written_off',
        ],
        'other_adjustments': [
            'exchange_differences_on_amortization',
            'reclassifications_of_amortization',
            'other_adjustments_to_amortization',
        ],
        'closing_accumulated_amortization': [
            'accumulated_amortization_at_end',
            'accumulated_amortization_closing',
            'amortization_at_end_of_year',
            'closing_balance_accumulated_amortization',
        ],
    },
    'net_block': [
        'intangible_assets_net_block',
        'net_carrying_amount',
        'net_carrying_value',
        'net_book_value',
        'carrying_amount_at_beginning',
        'carrying_amount_at_end',
    ],
    'goodwill': {
        'goodwill_movements': [
            'goodwill_at_beginning_of_period',
            'goodwill_opening_balance',
            'goodwill_recognized_on_acquisition',
            'goodwill_arising_on_business_combination',
            'goodwill_on_consolidation',
            'adjustments_to_goodwill',
            'measurement_period_adjustments',
            'goodwill_disposed_on_sale_of_subsidiary',
            'goodwill_written_off',
            'impairment_of_goodwill',
            'exchange_differences_on_goodwill',
            'goodwill_at_end_of_period',
            'goodwill_closing_balance',
        ],
        'goodwill_allocation': [
            'goodwill_allocated_to_cgu',
            'goodwill_by_cash_generating_unit',
            'goodwill_by_segment',
            'goodwill_by_subsidiary',
        ],
        'goodwill_impairment_testing': [
            'recoverable_amount_of_cgu',
            'value_in_use_of_cgu',
            'fair_value_less_costs_of_disposal',
            'key_assumptions_for_value_in_use',
            'discount_rate_used',
            'growth_rate_used',
            'terminal_growth_rate',
            'cash_flow_projection_period',
            'sensitivity_analysis',
            'headroom',
        ],
    },
    'intangible_assets_under_development': {
        'iaud_movements': [
            'iaud_at_beginning_of_period',
            'iaud_opening_balance',
            'additions_to_iaud',
            'development_expenditure_incurred',
            'borrowing_costs_capitalized',
            'capitalized_during_period',
            'transfer_to_intangible_assets',
            'impairment_of_iaud',
            'write_off_of_iaud',
            'iaud_at_end_of_period',
            'iaud_closing_balance',
        ],
        'iaud_ageing': [
            'iaud_less_than_1_year',
            'iaud_1_to_2_years',
            'iaud_2_to_3_years',
            'iaud_more_than_3_years',
            'projects_in_progress',
            'projects_temporarily_suspended',
        ],
    },
    'intangible_assets_disclosures': {
        'measurement_basis': [
            'cost_model',
            'revaluation_model',
            'fair_value_model',
        ],
        'amortization': [
            'amortization_method',
            'straight_line_method',
            'units_of_production_method',
            'revenue_based_method',
            'useful_life',
            'finite_useful_life',
            'indefinite_useful_life',
            'estimated_useful_life',
            'remaining_useful_life',
            'residual_value',
            'review_of_useful_life',
            'change_in_useful_life',
            'change_in_amortization_method',
        ],
        'restrictions_and_pledges': [
            'intangible_assets_pledged_as_security',
            'restrictions_on_title',
            'restrictions_on_use',
            'contractual_commitments_for_acquisition',
        ],
        'research_and_development': [
            'research_expenditure',
            'development_expenditure_recognized',
            'development_expenditure_expensed',
            'criteria_for_capitalization',
            'technical_feasibility',
            'intention_to_complete',
            'ability_to_use_or_sell',
            'probable_future_economic_benefits',
            'availability_of_resources',
            'ability_to_measure_expenditure',
        ],
    },
}

# =============================================================================
# SECTION 16: INVESTMENT PROPERTY NOTES
# =============================================================================

INVESTMENT_PROPERTY_NOTES = {
    'investment_property_categories': [
        'investment_property_land',
        'investment_property_buildings',
        'investment_property_land_and_buildings',
        'investment_property_under_construction',
        'leasehold_investment_property',
        'freehold_investment_property',
        'commercial_property',
        'office_buildings_investment',
        'retail_property',
        'shopping_centers',
        'malls',
        'warehouses_investment',
        'industrial_property',
        'residential_property_investment',
        'mixed_use_property',
        'hotels_investment',
        'undeveloped_land',
        'land_held_for_capital_appreciation',
        'property_held_for_rental',
    ],
    'gross_block_movements': {
        'opening_gross_block': [
            'investment_property_gross_block_opening',
            'cost_at_beginning_of_year',
            'fair_value_at_beginning_of_year',
            'opening_balance_investment_property',
        ],
        'additions': [
            'additions_during_period',
            'acquisitions_of_investment_property',
            'subsequent_expenditure_capitalized',
            'assets_acquired_through_business_combination',
            'transfer_from_owner_occupied_property',
            'transfer_from_inventories',
            'investment_property_under_construction_capitalized',
        ],
        'disposals': [
            'disposals_during_period',
            'investment_property_sold',
            'investment_property_disposed',
        ],
        'transfers': [
            'transfer_to_owner_occupied_property',
            'transfer_to_inventories',
            'transfer_to_held_for_sale',
            'transfer_from_ppe',
            'transfer_to_ppe',
        ],
        'fair_value_changes': [
            'fair_value_gain',
            'fair_value_loss',
            'net_fair_value_gain_loss',
            'fair_value_adjustment',
        ],
        'other_adjustments': [
            'exchange_differences',
            'foreign_currency_translation',
            'other_adjustments',
        ],
        'closing_gross_block': [
            'investment_property_gross_block_closing',
            'cost_at_end_of_year',
            'fair_value_at_end_of_year',
            'closing_balance_investment_property',
        ],
    },
    'accumulated_depreciation_movements': {
        'opening_accumulated_depreciation': [
            'accumulated_depreciation_at_beginning',
            'accumulated_depreciation_opening',
            'opening_balance_accumulated_depreciation',
        ],
        'depreciation_for_period': [
            'depreciation_for_the_period',
            'depreciation_for_the_year',
            'depreciation_charge',
        ],
        'impairment': [
            'impairment_loss_recognized',
            'reversal_of_impairment_loss',
        ],
        'disposals': [
            'depreciation_on_disposals',
            'accumulated_depreciation_on_assets_sold',
        ],
        'closing_accumulated_depreciation': [
            'accumulated_depreciation_at_end',
            'accumulated_depreciation_closing',
            'closing_balance_accumulated_depreciation',
        ],
    },
    'net_block': [
        'investment_property_net_block',
        'net_carrying_amount',
        'carrying_amount_at_beginning',
        'carrying_amount_at_end',
    ],
    'investment_property_income_expenses': [
        'rental_income_from_investment_property',
        'direct_operating_expenses_from_property_generating_rental',
        'direct_operating_expenses_from_property_not_generating_rental',
        'repairs_and_maintenance',
        'insurance',
        'property_taxes',
        'management_fees',
        'net_rental_income',
    ],
    'investment_property_disclosures': {
        'measurement_model': [
            'cost_model',
            'fair_value_model',
            'cost_less_accumulated_depreciation',
            'fair_value_at_each_reporting_date',
        ],
        'fair_value_measurement': [
            'fair_value_of_investment_property',
            'fair_value_hierarchy_level',
            'level_1_fair_value',
            'level_2_fair_value',
            'level_3_fair_value',
            'valuation_technique',
            'significant_inputs',
            'unobservable_inputs',
            'market_comparable_approach',
            'income_approach',
            'discounted_cash_flow_approach',
            'capitalization_rate',
            'discount_rate',
            'expected_market_rental',
            'occupancy_rate',
            'sensitivity_to_changes_in_inputs',
        ],
        'valuer_information': [
            'name_of_valuer',
            'qualification_of_valuer',
            'date_of_valuation',
            'independent_valuer',
            'internal_valuation',
        ],
        'restrictions_and_obligations': [
            'restrictions_on_realizability',
            'restrictions_on_remittance',
            'contractual_obligations_for_purchase',
            'contractual_obligations_for_construction',
            'contractual_obligations_for_development',
            'contractual_obligations_for_repairs',
            'contractual_obligations_for_maintenance',
        ],
        'leasing_arrangements': [
            'minimum_lease_payments_receivable',
            'future_minimum_lease_payments',
            'within_one_year',
            'between_one_and_five_years',
            'beyond_five_years',
            'contingent_rents_recognized',
            'lease_term',
            'escalation_clauses',
            'renewal_options',
        ],
    }
}
