
# =============================================================================
# SECTION 37: REVENUE FROM CONTRACTS (IND AS 115)
# =============================================================================

REVENUE_FROM_CONTRACTS_IND_AS_115 = {
    'revenue_recognition': {
        'five_step_model': {
            'step_1_identify_contract': [
                'contract_identification',
                'contract_approval',
                'commercial_substance',
                'identification_of_rights',
                'identification_of_payment_terms',
                'collectibility_probable',
                'contract_combination',
                'combined_contracts',
                'single_contract',
            ],
            'step_2_identify_performance_obligations': [
                'performance_obligations',
                'distinct_goods_or_services',
                'separately_identifiable',
                'capable_of_being_distinct',
                'distinct_within_context_of_contract',
                'series_of_distinct_goods_or_services',
                'bundle_of_goods_or_services',
                'integration_services',
                'significant_modification_or_customization',
                'highly_interdependent_or_interrelated',
            ],
            'step_3_determine_transaction_price': [
                'transaction_price',
                'fixed_consideration',
                'variable_consideration',
                'constraint_on_variable_consideration',
                'significant_financing_component',
                'non_cash_consideration',
                'consideration_payable_to_customer',
                'expected_value_method',
                'most_likely_amount_method',
                'discount_rate_for_financing',
                'stand_alone_selling_price',
            ],
            'step_4_allocate_transaction_price': [
                'allocation_of_transaction_price',
                'stand_alone_selling_price',
                'relative_stand_alone_selling_price_method',
                'adjusted_market_assessment_approach',
                'expected_cost_plus_margin_approach',
                'residual_approach',
                'discount_allocation',
                'variable_consideration_allocation',
            ],
            'step_5_recognize_revenue': [
                'revenue_recognition_timing',
                'point_in_time_recognition',
                'over_time_recognition',
                'control_transfer',
                'output_methods',
                'input_methods',
                'progress_towards_completion',
                'percentage_of_completion',
                'cost_to_cost_method',
                'efforts_expended_method',
                'time_elapsed_method',
                'units_delivered_method',
                'milestones_achieved',
            ],
        },
        'performance_obligations_satisfied_over_time': [
            'customer_simultaneously_receives_and_consumes',
            'customer_controls_asset_as_created',
            'no_alternative_use_to_entity',
            'enforceable_right_to_payment',
            'continuous_transfer_of_control',
        ],
        'performance_obligations_satisfied_at_point_in_time': [
            'present_right_to_payment',
            'legal_title_transferred',
            'physical_possession_transferred',
            'significant_risks_and_rewards_transferred',
            'customer_acceptance',
        ],
    },
    'contract_modifications': [
        'contract_modifications',
        'change_orders',
        'variations',
        'amendments',
        'claims',
        'separate_contract_for_modification',
        'prospective_accounting',
        'cumulative_catch_up_adjustment',
        'blend_and_extend_modifications',
    ],
    'contract_costs': {
        'costs_to_obtain_contract': [
            'incremental_costs_of_obtaining_contract',
            'sales_commissions',
            'legal_fees_for_contract_negotiation',
            'success_fees',
            'costs_that_would_not_have_been_incurred',
            'practical_expedient_for_costs_to_obtain',
            'amortization_period_less_than_one_year',
        ],
        'costs_to_fulfill_contract': [
            'costs_to_fulfill_contract',
            'direct_labor',
            'direct_materials',
            'allocation_of_overheads',
            'costs_that_relate_directly_to_contract',
            'costs_that_generate_or_enhance_resources',
            'costs_expected_to_be_recovered',
            'setup_costs',
            'mobilization_costs',
            'design_costs',
            'pre_production_costs',
        ],
        'amortization_and_impairment': [
            'amortization_of_contract_costs',
            'systematic_basis_consistent_with_transfer',
            'impairment_of_contract_costs',
            'impairment_assessment',
            'reversal_of_impairment',
        ],
    },
    'contract_balances': {
        'contract_assets': [
            'contract_assets',
            'unbilled_revenue',
            'unbilled_receivables',
            'work_in_progress_unbilled',
            'right_to_consideration_conditional',
            'revenue_recognized_exceeding_billing',
            'performance_completed_not_invoiced',
            'milestone_receivables_contingent',
            'retention_receivables',
        ],
        'trade_receivables': [
            'trade_receivables_from_contracts',
            'unconditional_right_to_consideration',
            'invoiced_amounts',
            'billed_receivables',
        ],
        'contract_liabilities': [
            'contract_liabilities',
            'deferred_revenue',
            'unearned_revenue',
            'advances_from_customers',
            'customer_deposits',
            'progress_billings',
            'billing_exceeding_revenue_recognized',
            'prepaid_revenue',
            'gift_cards_outstanding',
            'loyalty_points_outstanding',
            'volume_discounts_accrued',
        ],
        'significant_changes_in_balances': [
            'revenue_recognized_from_opening_contract_liability',
            'revenue_recognized_from_performance_obligations_satisfied_in_prior_periods',
            'contract_assets_reclassified_to_receivables',
            'impairment_of_contract_assets',
            'business_combinations_impact',
        ],
    },
    'revenue_disaggregation': [
        'revenue_by_type_of_goods_or_services',
        'revenue_by_geography',
        'revenue_by_contract_type',
        'revenue_by_contract_duration',
        'revenue_by_timing_of_transfer',
        'revenue_by_sales_channel',
        'revenue_by_customer_type',
        'revenue_from_government_contracts',
        'revenue_from_private_sector',
    ],
    'performance_obligations_disclosures': {
        'remaining_performance_obligations': [
            'aggregate_amount_of_transaction_price_allocated',
            'remaining_performance_obligations',
            'expected_timing_of_satisfaction',
            'within_one_year',
            'more_than_one_year',
            'practical_expedients_used',
        ],
        'warranties': [
            'assurance_type_warranties',
            'service_type_warranties',
            'warranty_as_separate_performance_obligation',
            'warranty_provision',
        ],
        'principal_vs_agent': [
            'principal_agent_considerations',
            'control_before_transfer_to_customer',
            'inventory_risk',
            'pricing_discretion',
            'gross_vs_net_presentation',
        ],
        'bill_and_hold_arrangements': [
            'bill_and_hold_sales',
            'substantive_reason_for_arrangement',
            'product_identified_separately',
            'product_ready_for_transfer',
            'entity_cannot_use_product',
        ],
        'consignment_arrangements': [
            'consignment_sales',
            'control_not_transferred',
            'revenue_when_sold_by_dealer',
        ],
    },
    'significant_judgments': [
        'determining_timing_of_satisfaction',
        'determining_transaction_price',
        'allocating_transaction_price',
        'estimating_variable_consideration',
        'constraining_variable_consideration',
        'determining_stand_alone_selling_prices',
        'determining_whether_principal_or_agent',
        'determining_warranty_obligations',
        'determining_distinct_performance_obligations',
    ],
    'practical_expedients': [
        'significant_financing_component_less_than_one_year',
        'costs_to_obtain_contract_less_than_one_year',
        'shipping_and_handling_as_fulfillment_costs',
        'sales_tax_presentation',
        'portfolio_approach',
        'right_to_invoice_practical_expedient',
    ],
}

# =============================================================================
# SECTION 38: EMPLOYEE BENEFITS (IND AS 19)
# =============================================================================

EMPLOYEE_BENEFITS_IND_AS_19 = {
    'short_term_employee_benefits': {
        'components': [
            'wages_and_salaries',
            'social_security_contributions',
            'paid_annual_leave',
            'paid_sick_leave',
            'profit_sharing_and_bonuses',
            'non_monetary_benefits',
            'medical_care',
            'housing',
            'cars',
            'free_or_subsidized_goods_or_services',
        ],
        'recognition_and_measurement': [
            'undiscounted_amount',
            'expected_to_be_settled_within_12_months',
            'expense_when_employee_renders_service',
            'liability_for_unpaid_amounts',
        ],
        'compensated_absences': [
            'accumulating_compensated_absences',
            'non_accumulating_compensated_absences',
            'vesting_compensated_absences',
            'non_vesting_compensated_absences',
            'expected_cost_of_short_term_compensated_absences',
        ],
        'profit_sharing_and_bonus_plans': [
            'present_legal_or_constructive_obligation',
            'reliable_estimate_of_obligation',
            'expected_cost_of_profit_sharing',
            'expected_cost_of_bonus_payments',
        ],
    },
    'post_employment_benefits': {
        'defined_contribution_plans': {
            'types': [
                'provident_fund',
                'employees_provident_fund',
                'regional_provident_fund',
                'exempted_provident_fund',
                'recognized_provident_fund',
                'superannuation_fund',
                'national_pension_scheme',
                'nps',
                'employees_state_insurance',
                'esi',
            ],
            'accounting': [
                'contribution_payable',
                'expense_when_employee_renders_service',
                'prepaid_contributions_as_asset',
                'unpaid_contributions_as_liability',
                'no_actuarial_risk',
                'no_investment_risk',
            ],
        },
        'defined_benefit_plans': {
            'types': [
                'gratuity',
                'funded_gratuity',
                'unfunded_gratuity',
                'pension_plans',
                'post_retirement_medical_benefits',
                'leave_encashment',
                'earned_leave',
                'privilege_leave',
                'sick_leave',
                'compensated_absences',
                'long_service_awards',
                'jubilee_awards',
            ],
            'defined_benefit_obligation': {
                'measurement': [
                    'present_value_of_defined_benefit_obligation',
                    'projected_unit_credit_method',
                    'actuarial_valuation',
                    'current_service_cost',
                    'past_service_cost',
                    'interest_cost',
                    'remeasurements',
                    'benefits_paid',
                ],
                'actuarial_assumptions': [
                    'demographic_assumptions',
                    'financial_assumptions',
                    'discount_rate',
                    'salary_growth_rate',
                    'salary_escalation_rate',
                    'attrition_rate',
                    'mortality_rate',
                    'disability_rate',
                    'retirement_age',
                    'medical_cost_trend_rate',
                ],
                'remeasurements': [
                    'actuarial_gains_and_losses',
                    'experience_adjustments',
                    'changes_in_demographic_assumptions',
                    'changes_in_financial_assumptions',
                ],
            },
            'plan_assets': {
                'fair_value': [
                    'fair_value_of_plan_assets',
                    'opening_fair_value',
                    'interest_income',
                    'return_on_plan_assets_excluding_interest',
                    'contributions_by_employer',
                    'contributions_by_plan_participants',
                    'benefits_paid_from_fund',
                    'closing_fair_value',
                ],
                'composition': [
                    'equity_instruments',
                    'debt_instruments',
                    'government_securities',
                    'corporate_bonds',
                    'insurance_policies',
                    'property',
                    'cash_and_cash_equivalents',
                    'insurer_managed_funds',
                ],
                'restrictions': [
                    'qualifying_insurance_policies',
                    'reimbursement_rights',
                    'return_of_surplus',
                ],
            },
            'net_defined_benefit_liability_asset': [
                'present_value_of_obligation_minus_fair_value_of_plan_assets',
                'deficit_or_surplus',
                'asset_ceiling',
                'effect_of_asset_ceiling',
                'net_defined_benefit_liability',
                'net_defined_benefit_asset',
            ],
            'components_in_profit_or_loss': [
                'service_cost',
                'current_service_cost',
                'past_service_cost',
                'gain_loss_on_settlement',
                'net_interest',
                'interest_cost_on_dbo',
                'interest_income_on_plan_assets',
                'interest_on_effect_of_asset_ceiling',
            ],
            'components_in_oci': [
                'remeasurements',
                'actuarial_gains_losses',
                'return_on_plan_assets_excluding_interest',
                'change_in_effect_of_asset_ceiling',
                'not_reclassified_to_profit_or_loss',
            ],
            'sensitivity_analysis': [
                'sensitivity_to_key_assumptions',
                'impact_of_1_percent_increase_in_discount_rate',
                'impact_of_1_percent_decrease_in_discount_rate',
                'impact_of_1_percent_increase_in_salary_escalation',
                'impact_of_1_percent_decrease_in_salary_escalation',
                'impact_of_1_percent_change_in_attrition',
                'impact_of_change_in_mortality',
                'impact_of_change_in_medical_cost_trend',
            ],
            'maturity_profile': [
                'expected_benefit_payments',
                'weighted_average_duration',
                'expected_contributions_next_year',
                'funding_policy',
                'expected_return_on_plan_assets',
            ],
        },
        'multi_employer_plans': [
            'defined_benefit_multi_employer_plans',
            'defined_contribution_multi_employer_plans',
            'insufficient_information_for_defined_benefit_accounting',
            'proportionate_share_of_obligation',
            'withdrawal_liability',
        ],
    },
    'other_long_term_employee_benefits': {
        'types': [
            'long_term_compensated_absences',
            'sabbatical_leave',
            'long_service_leave',
            'long_term_disability_benefits',
            'deferred_compensation',
            'long_term_profit_sharing',
            'long_term_bonuses',
        ],
        'accounting': [
            'service_cost',
            'net_interest',
            'remeasurements_recognized_in_profit_or_loss',
            'actuarial_gains_losses_in_profit_or_loss',
        ],
    },
    'termination_benefits': {
        'types': [
            'voluntary_termination_benefits',
            'involuntary_termination_benefits',
            'voluntary_retirement_scheme',
            'vrs',
            'retrenchment_benefits',
            'severance_pay',
            'redundancy_payments',
            'golden_handshake',
        ],
        'recognition': [
            'earlier_of_when_offer_cannot_be_withdrawn',
            'when_restructuring_provision_recognized',
            'present_value_if_settled_beyond_12_months',
        ],
    },
    'share_based_payment_employee_benefits': {
        'equity_settled': [
            'employee_stock_option_plans',
            'esop',
            'employee_stock_purchase_plans',
            'espp',
            'restricted_stock_units',
            'rsu',
            'performance_shares',
            'share_appreciation_rights_equity_settled',
        ],
        'cash_settled': [
            'share_appreciation_rights_cash_settled',
            'sar',
            'phantom_stock_plans',
            'cash_bonus_based_on_share_price',
            'deferred_share_units',
        ],
        'measurement': [
            'fair_value_at_grant_date',
            'fair_value_at_each_reporting_date',
            'black_scholes_model',
            'binomial_model',
            'monte_carlo_simulation',
            'vesting_period',
            'vesting_conditions',
            'service_conditions',
            'performance_conditions',
            'market_conditions',
        ],
    },
    'disclosures': {
        'general_description': [
            'description_of_plans',
            'characteristics_of_plans',
            'risks_associated_with_plans',
        ],
        'reconciliations': [
            'reconciliation_of_opening_and_closing_balances',
            'reconciliation_of_defined_benefit_obligation',
            'reconciliation_of_plan_assets',
            'reconciliation_of_net_liability',
            'reconciliation_of_reimbursement_rights',
        ],
        'amounts_recognized': [
            'amounts_recognized_in_balance_sheet',
            'amounts_recognized_in_profit_or_loss',
            'amounts_recognized_in_oci',
            'actual_return_on_plan_assets',
        ],
        'significant_actuarial_assumptions': [
            'principal_actuarial_assumptions',
            'basis_for_determining_assumptions',
            'process_for_determining_assumptions',
        ],
        'funding': [
            'funding_arrangements',
            'funding_policy',
            'expected_contributions',
            'expected_benefit_payments',
        ],
    },
}

# =============================================================================
# SECTION 39: DEFERRED TAX ASSETS AND LIABILITIES
# =============================================================================

DEFERRED_TAX_ASSETS_AND_LIABILITIES = {
    'temporary_differences': {
        'taxable_temporary_differences': [
            'accelerated_depreciation_for_tax',
            'difference_in_depreciation_rates',
            'difference_in_depreciation_methods',
            'difference_in_useful_lives',
            'fair_value_gains_not_taxable_currently',
            'undistributed_profits_of_subsidiaries',
            'undistributed_profits_of_associates',
            'undistributed_profits_of_joint_ventures',
            'interest_income_accrued_but_not_received',
            'revenue_recognized_but_not_taxable',
            'capitalized_development_costs',
            'revaluation_of_assets_to_fair_value',
            'assets_acquired_in_business_combination',
        ],
        'deductible_temporary_differences': [
            'unabsorbed_depreciation',
            'carried_forward_losses',
            'business_losses',
            'capital_losses',
            'unabsorbed_capital_allowances',
            'provisions_not_deductible_until_paid',
            'provision_for_doubtful_debts',
            'provision_for_employee_benefits',
            'provision_for_warranties',
            'provision_for_expected_credit_loss',
            'expenses_accrued_but_not_paid',
            'fair_value_losses_not_deductible_currently',
            'impairment_losses',
            'unrealized_losses',
            'minimum_alternate_tax_credit',
            'mat_credit_entitlement',
            'section_43b_disallowances',
            'preliminary_expenses',
            'amalgamation_expenses',
        ],
    },
    'deferred_tax_assets': {
        'recognition_criteria': [
            'probable_future_taxable_profit',
            'tax_planning_opportunities',
            'reversal_of_taxable_temporary_differences',
            'probability_of_utilization',
        ],
        'components': [
            'deferred_tax_asset_on_losses',
            'deferred_tax_asset_on_unabsorbed_depreciation',
            'deferred_tax_asset_on_provisions',
            'deferred_tax_asset_on_employee_benefits',
            'deferred_tax_asset_on_financial_instruments',
            'deferred_tax_asset_on_lease_liabilities',
            'deferred_tax_asset_on_other_items',
            'mat_credit_entitlement',
            'advance_tax_recoverable',
        ],
        'unrecognized_deferred_tax_assets': [
            'unrecognized_deferred_tax_assets',
            'unrecognized_tax_losses',
            'unrecognized_tax_credits',
            'unrecognized_deductible_temporary_differences',
            'expiry_dates_of_unrecognized_items',
        ],
    },
    'deferred_tax_liabilities': {
        'recognition': [
            'all_taxable_temporary_differences',
            'exceptions_for_initial_recognition',
            'exceptions_for_goodwill',
            'exceptions_for_investments_in_subsidiaries',
        ],
        'components': [
            'deferred_tax_liability_on_property_plant_equipment',
            'deferred_tax_liability_on_intangible_assets',
            'deferred_tax_liability_on_fair_value_adjustments',
            'deferred_tax_liability_on_financial_instruments',
            'deferred_tax_liability_on_right_of_use_assets',
            'deferred_tax_liability_on_undistributed_profits',
            'deferred_tax_liability_on_other_items',
        ],
        'unrecognized_deferred_tax_liabilities': [
            'unrecognized_deferred_tax_liabilities',
            'investments_in_subsidiaries',
            'investments_in_associates',
            'investments_in_joint_ventures',
            'aggregate_amount_of_temporary_differences',
        ],
    },
    'measurement': {
        'tax_rates': [
            'enacted_tax_rate',
            'substantively_enacted_tax_rate',
            'expected_tax_rate',
            'tax_rate_applicable_to_reversal',
            'change_in_tax_rate',
            'impact_of_tax_rate_change',
        ],
        'manner_of_recovery': [
            'recovery_through_use',
            'recovery_through_sale',
            'presumption_for_investment_property',
            'dual_tax_rates',
        ],
        'discounting': [
            'deferred_tax_not_discounted',
            'undiscounted_amount',
        ],
    },
    'movements': {
        'deferred_tax_asset_movement': [
            'opening_balance_deferred_tax_asset',
            'recognized_in_profit_or_loss',
            'recognized_in_oci',
            'recognized_directly_in_equity',
            'acquisitions_through_business_combinations',
            'disposals',
            'exchange_differences',
            'reclassifications',
            'closing_balance_deferred_tax_asset',
        ],
        'deferred_tax_liability_movement': [
            'opening_balance_deferred_tax_liability',
            'charge_to_profit_or_loss',
            'charge_to_oci',
            'charge_to_equity',
            'acquisitions_through_business_combinations',
            'disposals',
            'exchange_differences',
            'reclassifications',
            'closing_balance_deferred_tax_liability',
        ],
        'net_movement': [
            'net_deferred_tax_asset',
            'net_deferred_tax_liability',
            'gross_deferred_tax_assets',
            'gross_deferred_tax_liabilities',
            'offsetting_of_deferred_tax',
        ],
    },
    'analysis_by_type': {
        'major_components': [
            'property_plant_and_equipment',
            'intangible_assets',
            'financial_instruments',
            'inventories',
            'trade_receivables',
            'provisions',
            'employee_benefit_obligations',
            'tax_losses',
            'tax_credits',
            'lease_assets_and_liabilities',
            'other_items',
        ],
        'reconciliation': [
            'reconciliation_by_type_of_temporary_difference',
            'reconciliation_by_type_of_asset_or_liability',
        ],
    },
    'disclosures': {
        'offsetting': [
            'offsetting_criteria',
            'legally_enforceable_right_to_offset',
            'same_taxation_authority',
            'same_taxable_entity_or_group',
            'intention_to_settle_on_net_basis',
        ],
        'expiry_profile': [
            'expiry_of_unused_tax_losses',
            'expiry_of_unused_tax_credits',
            'expiry_within_1_year',
            'expiry_1_to_5_years',
            'expiry_5_to_10_years',
            'expiry_beyond_10_years',
            'no_expiry_date',
        ],
        'tax_planning_strategies': [
            'tax_planning_opportunities',
            'strategies_for_utilizing_deferred_tax_assets',
            'evidence_supporting_recognition',
        ],
    },
}

# =============================================================================
# SECTION 40: INCOME TAX RECONCILIATION
# =============================================================================

INCOME_TAX_RECONCILIATION = {
    'effective_tax_rate_reconciliation': {
        'starting_point': [
            'profit_before_tax',
            'accounting_profit_before_tax',
            'profit_before_income_tax',
            'earnings_before_tax',
        ],
        'applicable_tax_rate': [
            'statutory_tax_rate',
            'enacted_tax_rate',
            'domestic_tax_rate',
            'corporate_tax_rate',
            'basic_tax_rate',
            'surcharge_rate',
            'education_cess_rate',
            'effective_statutory_rate',
        ],
        'tax_at_applicable_rate': [
            'expected_tax_expense',
            'tax_at_statutory_rate',
            'profit_before_tax_multiplied_by_tax_rate',
        ],
        'permanent_differences': {
            'non_deductible_expenses': [
                'non_deductible_expenses',
                'entertainment_expenses',
                'personal_expenses',
                'penalties_and_fines',
                'political_contributions',
                'csr_expenses',
                'goodwill_impairment',
                'non_deductible_depreciation',
                'non_deductible_provisions',
                'section_14a_disallowance',
                'section_40a_disallowances',
                'section_37_disallowances',
                'thin_capitalization',
            ],
            'non_taxable_income': [
                'non_taxable_income',
                'exempt_income',
                'agricultural_income',
                'dividend_income_exempt',
                'long_term_capital_gains_exempt',
                'income_exempt_under_section_10',
                'tax_holiday_income',
            ],
            'tax_incentives': [
                'tax_incentives_and_allowances',
                'investment_allowance',
                'additional_depreciation',
                'weighted_deduction_for_r_and_d',
                'section_80_deductions',
                'section_80c_deductions',
                'section_80d_deductions',
                'section_80g_deductions',
                'section_80ia_deductions',
                'section_80ib_deductions',
                'export_incentives',
                'special_economic_zone_deductions',
            ],
            'different_tax_rates': [
                'income_taxed_at_different_rates',
                'capital_gains_tax_rate',
                'dividend_distribution_tax',
                'mat_rate_difference',
                'foreign_tax_rate_differential',
                'state_tax_rate_differential',
            ],
        },
        'temporary_difference_adjustments': [
            'deferred_tax_adjustments',
            'origination_of_temporary_differences',
            'reversal_of_temporary_differences',
            'unrecognized_deferred_tax_assets',
            'recognition_of_previously_unrecognized_assets',
            'write_down_of_deferred_tax_assets',
        ],
        'prior_year_adjustments': [
            'adjustments_for_prior_years',
            'under_provision_in_earlier_years',
            'over_provision_in_earlier_years',
            'assessment_orders_for_earlier_years',
            'true_up_adjustments',
        ],
        'tax_rate_changes': [
            'effect_of_tax_rate_changes',
            'change_in_enacted_tax_rates',
            'change_in_applicable_tax_rates',
            'impact_on_deferred_tax',
        ],
        'other_items': [
            'share_of_profit_of_associates',
            'share_of_profit_of_joint_ventures',
            'foreign_tax_credits',
            'withholding_taxes',
            'uncertain_tax_positions',
            'tax_on_distributed_profits',
            'tax_on_undistributed_profits',
            'consolidation_adjustments',
            'others',
        ],
        'actual_tax_expense': [
            'total_income_tax_expense',
            'current_tax_expense',
            'deferred_tax_expense',
            'tax_expense_reported',
        ],
        'effective_tax_rate': [
            'effective_tax_rate',
            'effective_rate_percentage',
            'tax_expense_divided_by_profit_before_tax',
        ],
    },
    'current_tax_reconciliation': {
        'taxable_income_computation': [
            'profit_as_per_books',
            'add_inadmissible_expenses',
            'add_taxable_income_not_in_books',
            'less_admissible_expenses_not_in_books',
            'less_exempt_income',
            'total_income',
            'gross_total_income',
            'deductions_under_chapter_vi_a',
            'taxable_income',
            'tax_on_taxable_income',
            'surcharge',
            'education_cess',
            'total_tax_liability',
        ],
        'book_to_tax_adjustments': [
            'permanent_adjustments',
            'timing_differences',
            'depreciation_adjustment',
            'provision_adjustments',
            'accrual_to_cash_adjustments',
            'consolidation_eliminations',
        ],
        'minimum_alternate_tax': [
            'book_profit_computation',
            'profit_as_per_profit_and_loss',
            'add_back_items',
            'reduce_items',
            'book_profit',
            'mat_on_book_profit',
            'mat_credit_entitlement',
            'mat_credit_utilization',
            'mat_credit_balance',
        ],
    },
    'tax_assets_and_liabilities_reconciliation': {
        'current_tax_position': [
            'advance_tax_paid',
            'tds_receivable',
            'tcs_receivable',
            'self_assessment_tax_paid',
            'current_tax_liability',
            'provision_for_tax',
            'net_current_tax_asset',
            'net_current_tax_liability',
        ],
        'movements': [
            'opening_balance',
            'current_year_provision',
            'advance_tax_paid_during_year',
            'tds_and_tcs_for_year',
            'tax_refund_received',
            'tax_paid_for_earlier_years',
            'adjustment_for_earlier_years',
            'closing_balance',
        ],
    },
    'uncertain_tax_positions': {
        'identification': [
            'uncertain_tax_positions',
            'tax_positions_under_dispute',
            'tax_positions_under_litigation',
            'aggressive_tax_positions',
        ],
        'measurement': [
            'most_likely_amount',
            'expected_value',
            'probability_weighted_amount',
            'range_of_possible_outcomes',
        ],
        'disclosure': [
            'nature_of_uncertainty',
            'amount_of_uncertainty',
            'interest_and_penalties',
            'expected_resolution_period',
        ],
    },
    'other_tax_disclosures': {
        'tax_holidays': [
            'tax_holiday_period',
            'tax_holiday_units',
            'tax_saved_due_to_tax_holiday',
            'expiry_of_tax_holiday',
        ],
        'transfer_pricing': [
            'transfer_pricing_adjustments',
            'arms_length_price',
            'transfer_pricing_study',
            'advance_pricing_agreements',
            'safe_harbor_rules',
        ],
        'international_tax': [
            'controlled_foreign_corporation_rules',
            'thin_capitalization_rules',
            'beps_impact',
            'pillar_one_impact',
            'pillar_two_impact',
            'global_minimum_tax',
        ],
        'tax_litigation': [
            'pending_tax_cases',
            'tax_demands_disputed',
            'appellate_authorities',
            'tax_deposits_made',
            'stay_orders_obtained',
        ],
    },
}

# =============================================================================
# SECTION 41: BUSINESS COMBINATIONS AND GOODWILL
# =============================================================================

BUSINESS_COMBINATIONS_AND_GOODWILL = {
    'acquisition_method': {
        'identifying_acquirer': [
            'acquirer_identification',
            'entity_obtaining_control',
            'control_assessment',
            'power_over_investee',
            'exposure_to_variable_returns',
            'ability_to_use_power',
            'reverse_acquisition',
            'identifying_acquirer_in_reverse_acquisition',
        ],
        'determining_acquisition_date': [
            'acquisition_date',
            'date_of_obtaining_control',
            'closing_date',
            'effective_date_of_acquisition',
            'legal_completion_date',
        ],
        'recognizing_identifiable_assets_and_liabilities': {
            'identifiable_assets_acquired': [
                'identifiable_assets_acquired',
                'tangible_assets_acquired',
                'property_plant_equipment_acquired',
                'land_acquired',
                'buildings_acquired',
                'plant_and_machinery_acquired',
                'intangible_assets_acquired',
                'customer_relationships_acquired',
                'technology_acquired',
                'brand_names_acquired',
                'patents_acquired',
                'licenses_acquired',
                'software_acquired',
                'non_compete_agreements_acquired',
                'order_backlog_acquired',
                'financial_assets_acquired',
                'trade_receivables_acquired',
                'inventories_acquired',
                'contract_assets_acquired',
                'prepaid_expenses_acquired',
                'right_of_use_assets_acquired',
                'investment_property_acquired',
                'biological_assets_acquired',
                'deferred_tax_assets_acquired',
            ],
            'liabilities_assumed': [
                'liabilities_assumed',
                'borrowings_assumed',
                'trade_payables_assumed',
                'provisions_assumed',
                'employee_benefit_obligations_assumed',
                'deferred_revenue_assumed',
                'contract_liabilities_assumed',
                'lease_liabilities_assumed',
                'deferred_tax_liabilities_assumed',
                'contingent_liabilities_assumed',
                'warranty_obligations_assumed',
                'restructuring_provisions_assumed',
                'environmental_liabilities_assumed',
                'legal_claims_assumed',
            ],
            'recognition_criteria': [
                'recognition_criteria_for_assets',
                'recognition_criteria_for_liabilities',
                'probability_of_future_economic_benefits',
                'reliable_measurement',
                'separate_from_goodwill',
                'identifiable_intangible_assets',
                'contractual_legal_criterion',
                'separability_criterion',
            ],
        },
    },
    'fair_value_measurement': {
        'measurement_principles': [
            'fair_value_at_acquisition_date',
            'acquisition_date_fair_value',
            'exit_price',
            'market_participant_assumptions',
            'highest_and_best_use',
        ],
        'valuation_techniques': [
            'market_approach',
            'income_approach',
            'cost_approach',
            'relief_from_royalty_method',
            'multi_period_excess_earnings_method',
            'with_and_without_method',
            'replacement_cost_method',
            'discounted_cash_flow_method',
            'comparable_transactions_method',
            'guideline_public_company_method',
        ],
        'specific_items': {
            'intangible_assets_valuation': [
                'customer_relationship_valuation',
                'technology_valuation',
                'brand_valuation',
                'patent_valuation',
                'license_valuation',
                'non_compete_valuation',
                'in_process_r_and_d_valuation',
            ],
            'contingent_liabilities_valuation': [
                'fair_value_of_contingent_liabilities',
                'probability_weighted_outcomes',
                'present_value_of_expected_cash_flows',
            ],
            'indemnification_assets': [
                'indemnification_asset_recognition',
                'measurement_consistent_with_indemnified_item',
            ],
        },
    },
    'consideration_transferred': {
        'components_of_consideration': [
            'consideration_transferred',
            'purchase_consideration',
            'cash_paid',
            'equity_instruments_issued',
            'debt_instruments_issued',
            'assets_transferred',
            'liabilities_incurred',
            'fair_value_of_consideration',
        ],
        'contingent_consideration': [
            'contingent_consideration',
            'earnout_arrangements',
            'performance_based_consideration',
            'milestone_payments',
            'escrow_arrangements',
            'holdback_arrangements',
            'classification_as_equity_or_liability',
            'fair_value_of_contingent_consideration',
            'subsequent_remeasurement',
            'changes_in_fair_value_of_contingent_consideration',
        ],
        'share_based_payment_awards': [
            'replacement_awards',
            'acquiree_awards_exchanged',
            'vested_awards',
            'unvested_awards',
            'allocation_to_consideration_vs_service',
        ],
    },
    'goodwill_and_bargain_purchase': {
        'goodwill': {
            'calculation': [
                'goodwill_calculation',
                'consideration_transferred',
                'plus_non_controlling_interests',
                'plus_previously_held_equity_interest',
                'less_fair_value_of_net_identifiable_assets',
                'equals_goodwill',
            ],
            'recognition': [
                'goodwill_recognized',
                'goodwill_on_acquisition',
                'goodwill_arising_on_business_combination',
                'initial_recognition_of_goodwill',
            ],
            'composition': [
                'expected_synergies',
                'assembled_workforce',
                'expected_future_benefits',
                'premium_paid_for_control',
            ],
        },
        'bargain_purchase': [
            'bargain_purchase',
            'negative_goodwill',
            'gain_on_bargain_purchase',
            'reassessment_before_recognizing_gain',
            'recognition_in_profit_or_loss',
            'reasons_for_bargain_purchase',
        ],
    },
    'non_controlling_interests': {
        'measurement_options': [
            'nci_at_fair_value',
            'full_goodwill_method',
            'nci_at_proportionate_share_of_net_assets',
            'partial_goodwill_method',
            'election_on_transaction_by_transaction_basis',
        ],
        'subsequent_changes': [
            'changes_in_nci_without_loss_of_control',
            'equity_transactions',
            'no_gain_or_loss_in_profit_or_loss',
            'adjustment_to_equity',
        ],
    },
    'step_acquisitions': {
        'achieving_control_in_stages': [
            'step_acquisition',
            'business_combination_achieved_in_stages',
            'previously_held_equity_interest',
            'remeasurement_to_fair_value',
            'gain_or_loss_on_remeasurement',
            'amounts_previously_recognized_in_oci',
            'reclassification_of_oci_amounts',
        ],
    },
    'measurement_period': {
        'measurement_period_adjustments': [
            'measurement_period',
            'maximum_one_year_period',
            'provisional_amounts',
            'adjustments_to_provisional_amounts',
            'additional_information_obtained',
            'retrospective_adjustment',
            'adjustment_to_goodwill',
            'effect_on_comparative_information',
        ],
    },
    'acquisition_related_costs': [
        'acquisition_related_costs',
        'finder_fees',
        'advisory_fees',
        'legal_fees',
        'accounting_fees',
        'valuation_fees',
        'due_diligence_costs',
        'stamp_duty',
        'registration_fees',
        'internal_acquisition_costs',
        'debt_issuance_costs',
        'equity_issuance_costs',
        'expense_in_period_incurred',
    ],
    'goodwill_subsequent_measurement': {
        'impairment_testing': [
            'annual_impairment_test',
            'impairment_test_when_indicators_exist',
            'allocation_to_cash_generating_units',
            'recoverable_amount_of_cgu',
            'value_in_use',
            'fair_value_less_costs_of_disposal',
            'impairment_loss_recognition',
            'allocation_of_impairment_loss',
        ],
        'impairment_disclosures': [
            'carrying_amount_of_goodwill',
            'allocation_of_goodwill_to_cgus',
            'basis_for_recoverable_amount',
            'key_assumptions',
            'discount_rate',
            'growth_rate',
            'terminal_growth_rate',
            'sensitivity_analysis',
            'reasonably_possible_changes',
        ],
    },
    'business_combination_disclosures': {
        'for_each_acquisition': [
            'name_of_acquiree',
            'acquisition_date',
            'percentage_of_voting_equity_acquired',
            'primary_reasons_for_combination',
            'description_of_factors_making_up_goodwill',
            'fair_value_of_consideration_transferred',
            'fair_value_of_each_class_of_consideration',
            'contingent_consideration_arrangements',
            'fair_value_of_assets_acquired_and_liabilities_assumed',
            'fair_value_of_receivables_acquired',
            'gross_contractual_amounts_receivable',
            'best_estimate_of_amounts_not_collectible',
            'contingent_liabilities_recognized',
            'goodwill_recognized',
            'goodwill_expected_to_be_deductible',
            'bargain_purchase_gain',
            'amount_of_nci',
            'measurement_basis_for_nci',
            'fair_value_of_previously_held_interest',
            'gain_or_loss_on_previously_held_interest',
        ],
        'aggregate_disclosures': [
            'aggregate_disclosures_for_individually_immaterial_acquisitions',
            'number_of_acquisitions',
            'aggregate_consideration',
            'aggregate_goodwill',
            'aggregate_gain_on_bargain_purchases',
        ],
        'post_acquisition_information': [
            'revenue_of_acquiree_since_acquisition_date',
            'profit_or_loss_of_acquiree_since_acquisition_date',
            'combined_revenue_if_acquisition_at_beginning_of_period',
            'combined_profit_if_acquisition_at_beginning_of_period',
        ],
    },
    'common_control_transactions': [
        'business_combination_under_common_control',
        'pooling_of_interests_method',
        'predecessor_values_method',
        'acquisition_method',
        'accounting_policy_choice',
        'no_fresh_fair_value_measurement',
        'carrying_amounts_of_assets_and_liabilities',
        'difference_recognized_in_equity',
        'capital_reserve_on_common_control_transaction',
    ],
}

# =============================================================================
# SECTION 42: CONSOLIDATED FINANCIAL STATEMENTS
# =============================================================================

CONSOLIDATED_FINANCIAL_STATEMENTS = {
    'scope_of_consolidation': {
        'entities_to_consolidate': [
            'subsidiaries',
            'control_assessment',
            'power_over_investee',
            'exposure_to_variable_returns',
            'ability_to_affect_returns',
            'de_facto_control',
            'potential_voting_rights',
            'structured_entities',
            'special_purpose_entities',
        ],
        'exemptions_from_consolidation': [
            'investment_entities_exception',
            'intermediate_parent_exemption',
            'parent_is_wholly_owned_subsidiary',
            'parent_is_partially_owned_subsidiary',
            'no_objection_from_minority',
            'ultimate_parent_prepares_consolidated_financials',
            'debt_or_equity_not_traded',
        ],
        'loss_of_control': [
            'loss_of_control_assessment',
            'disposal_of_subsidiary',
            'dilution_of_interest',
            'change_in_contractual_arrangement',
            'gain_or_loss_on_loss_of_control',
            'retained_investment_at_fair_value',
            'reclassification_of_oci',
        ],
    },
    'consolidation_procedures': {
        'combining_financial_statements': [
            'line_by_line_consolidation',
            'aggregation_of_assets',
            'aggregation_of_liabilities',
            'aggregation_of_equity',
            'aggregation_of_income',
            'aggregation_of_expenses',
            'aggregation_of_cash_flows',
        ],
        'elimination_entries': {
            'inter_company_balances': [
                'elimination_of_inter_company_balances',
                'inter_company_receivables',
                'inter_company_payables',
                'inter_company_loans',
                'inter_company_investments',
                'investment_in_subsidiaries_elimination',
            ],
            'inter_company_transactions': [
                'elimination_of_inter_company_transactions',
                'inter_company_sales',
                'inter_company_purchases',
                'inter_company_services',
                'inter_company_interest',
                'inter_company_dividends',
                'inter_company_management_fees',
                'inter_company_royalties',
            ],
            'unrealized_profits': [
                'elimination_of_unrealized_profits',
                'unrealized_profit_in_inventory',
                'unrealized_profit_in_fixed_assets',
                'downstream_transactions',
                'upstream_transactions',
                'deferred_tax_on_unrealized_profits',
            ],
        },
        'uniform_accounting_policies': [
            'uniform_accounting_policies',
            'adjustments_for_different_policies',
            'harmonization_of_policies',
        ],
        'reporting_dates': [
            'same_reporting_date',
            'different_reporting_dates',
            'maximum_three_month_difference',
            'adjustments_for_significant_transactions',
        ],
    },
    'non_controlling_interests': {
        'presentation': [
            'nci_presented_within_equity',
            'nci_presented_separately_from_parent_equity',
            'profit_or_loss_attributed_to_nci',
            'total_comprehensive_income_attributed_to_nci',
        ],
        'measurement': [
            'nci_at_acquisition',
            'nci_share_of_changes_in_equity',
            'nci_share_of_profits_or_losses',
            'nci_share_of_oci',
            'dividends_paid_to_nci',
            'additional_investments_from_nci',
        ],
        'accumulated_losses': [
            'nci_share_of_accumulated_losses',
            'deficit_balance_of_nci',
            'losses_attributed_to_nci',
        ],
        'changes_in_ownership': [
            'changes_without_loss_of_control',
            'acquisition_of_nci',
            'disposal_of_interest_to_nci',
            'equity_transaction',
            'difference_recognized_in_equity',
            'no_change_in_goodwill',
        ],
    },
    'investment_in_associates': {
        'equity_method': [
            'equity_method_of_accounting',
            'significant_influence',
            'initial_recognition_at_cost',
            'share_of_profit_or_loss',
            'share_of_oci',
            'dividends_received_reduce_carrying_amount',
            'adjustments_for_inter_company_profits',
            'goodwill_included_in_carrying_amount',
        ],
        'impairment': [
            'impairment_of_investment_in_associates',
            'impairment_indicators',
            'recoverable_amount_assessment',
            'impairment_loss_recognition',
            'reversal_of_impairment',
        ],
        'discontinuation': [
            'discontinuation_of_equity_method',
            'loss_of_significant_influence',
            'associate_becomes_subsidiary',
            'associate_becomes_joint_venture',
            'classification_as_held_for_sale',
        ],
        'disclosures': [
            'name_of_associate',
            'principal_place_of_business',
            'proportion_of_ownership',
            'proportion_of_voting_power',
            'nature_of_relationship',
            'summarized_financial_information',
            'fair_value_if_quoted',
            'unrecognized_share_of_losses',
            'contingent_liabilities',
            'restrictions_on_dividends',
        ],
    },
    'investment_in_joint_ventures': {
        'equity_method': [
            'equity_method_for_joint_ventures',
            'joint_control',
            'contractual_arrangement',
            'unanimous_consent',
            'same_principles_as_associates',
        ],
        'joint_operations': [
            'joint_operations_accounting',
            'proportionate_consolidation_of_assets',
            'proportionate_consolidation_of_liabilities',
            'proportionate_revenue',
            'proportionate_expenses',
        ],
        'disclosures': [
            'name_of_joint_venture',
            'nature_of_interest',
            'proportion_of_ownership',
            'summarized_financial_information',
            'commitments_relating_to_joint_ventures',
            'contingent_liabilities',
        ],
    },
    'consolidated_statement_disclosures': {
        'composition_of_group': [
            'list_of_subsidiaries',
            'name_of_subsidiary',
            'country_of_incorporation',
            'proportion_of_ownership',
            'proportion_of_voting_power',
            'principal_activities',
            'reporting_date_if_different',
        ],
        'significant_restrictions': [
            'restrictions_on_transfer_of_funds',
            'restrictions_on_dividends',
            'restrictions_on_repayment_of_loans',
            'statutory_restrictions',
            'contractual_restrictions',
            'regulatory_restrictions',
            'assets_not_available_for_general_use',
        ],
        'changes_in_ownership': [
            'effect_of_changes_in_ownership',
            'schedule_of_effects_on_parent_equity',
            'changes_without_loss_of_control',
            'changes_resulting_in_loss_of_control',
        ],
        'structured_entities': [
            'consolidated_structured_entities',
            'nature_and_purpose',
            'nature_of_risks',
            'sponsorship_without_ownership',
        ],
        'investment_entities': [
            'investment_entity_status',
            'subsidiaries_measured_at_fair_value',
            'unconsolidated_subsidiaries',
            'significant_judgments',
        ],
    },
}

# =============================================================================
# SECTION 43: SHARE-BASED PAYMENTS (IND AS 102)
# =============================================================================

SHARE_BASED_PAYMENTS_IND_AS_102 = {
    'equity_settled_share_based_payments': {
        'employee_stock_option_plans': {
            'plan_terms': [
                'esop_plan',
                'employee_stock_option_plan',
                'stock_option_scheme',
                'grant_date',
                'vesting_period',
                'vesting_schedule',
                'graded_vesting',
                'cliff_vesting',
                'exercise_period',
                'exercise_price',
                'expiry_date',
                'lapse_conditions',
            ],
            'eligibility': [
                'eligible_employees',
                'permanent_employees',
                'directors',
                'whole_time_directors',
                'officers',
                'employees_of_subsidiaries',
                'employees_of_holding_company',
                'minimum_service_requirement',
            ],
            'vesting_conditions': [
                'service_conditions',
                'performance_conditions',
                'market_conditions',
                'non_market_conditions',
                'revenue_targets',
                'profit_targets',
                'ebitda_targets',
                'eps_targets',
                'share_price_targets',
                'total_shareholder_return_targets',
                'relative_tsr',
                'absolute_tsr',
            ],
        },
        'restricted_stock_units': [
            'restricted_stock_units',
            'rsu',
            'restricted_shares',
            'restricted_share_units',
            'vesting_of_rsu',
            'settlement_in_shares',
            'no_exercise_price',
        ],
        'performance_shares': [
            'performance_shares',
            'performance_share_plan',
            'performance_share_units',
            'psu',
            'performance_linked_shares',
        ],
        'employee_stock_purchase_plans': [
            'employee_stock_purchase_plan',
            'espp',
            'discounted_purchase_price',
            'look_back_feature',
            'contribution_period',
            'purchase_date',
        ],
    },
    'cash_settled_share_based_payments': {
        'share_appreciation_rights': [
            'share_appreciation_rights',
            'sar',
            'stock_appreciation_rights',
            'cash_settled_sar',
            'phantom_stock',
            'phantom_shares',
            'shadow_stock',
            'tandem_awards',
        ],
        'cash_bonus_plans': [
            'cash_bonus_linked_to_share_price',
            'deferred_cash_bonus',
            'long_term_incentive_plan',
            'ltip',
        ],
    },
    'measurement': {
        'fair_value_measurement': [
            'fair_value_at_grant_date',
            'fair_value_of_equity_instruments_granted',
            'fair_value_at_measurement_date',
            'fair_value_at_each_reporting_date',
            'changes_in_fair_value',
        ],
        'valuation_models': [
            'black_scholes_merton_model',
            'binomial_model',
            'lattice_model',
            'monte_carlo_simulation',
            'expected_term',
            'expected_volatility',
            'historical_volatility',
            'implied_volatility',
            'risk_free_interest_rate',
            'expected_dividends',
            'exercise_price',
            'share_price_at_grant_date',
            'fair_value_per_option',
        ],
        'modifications': [
            'modification_of_terms',
            'increase_in_fair_value',
            'decrease_in_fair_value',
            'repricing',
            'change_in_vesting_conditions',
            'change_in_exercise_price',
            'change_in_number_of_options',
            'acceleration_of_vesting',
        ],
        'cancellations_and_settlements': [
            'cancellation_of_awards',
            'forfeiture_of_awards',
            'settlement_of_awards',
            'acceleration_on_cancellation',
            'cash_settlement',
            'net_share_settlement',
        ],
    },
    'recognition_and_expense': {
        'expense_recognition': [
            'share_based_payment_expense',
            'employee_stock_option_expense',
            'esop_cost',
            'expense_over_vesting_period',
            'graded_vesting_expense',
            'front_loaded_expense',
            'cumulative_true_up',
        ],
        'estimate_revisions': [
            'revision_of_estimated_forfeitures',
            'change_in_estimate',
            'true_up_for_actual_forfeitures',
            'revision_of_performance_conditions',
        ],
        'accounting_entries': [
            'employee_benefit_expense_debit',
            'share_options_outstanding_credit',
            'share_based_payment_reserve',
            'transfer_on_exercise',
            'transfer_to_securities_premium',
            'transfer_on_lapse',
            'transfer_to_retained_earnings',
        ],
    },
    'transactions_with_cash_alternative': [
        'choice_of_settlement',
        'entity_has_choice',
        'counterparty_has_choice',
        'compound_instrument_treatment',
        'equity_component',
        'liability_component',
    ],
    'group_share_based_payments': [
        'parent_grants_rights_to_subsidiary_employees',
        'subsidiary_grants_rights_on_parent_shares',
        'recharge_arrangements',
        'equity_settled_at_subsidiary',
        'cash_settled_at_subsidiary',
        'contribution_from_parent',
    ],
    'disclosures': {
        'nature_and_extent': [
            'description_of_share_based_payment_arrangements',
            'general_terms_and_conditions',
            'vesting_requirements',
            'maximum_term_of_options_granted',
            'method_of_settlement',
        ],
        'option_activity': [
            'number_of_options_outstanding_at_beginning',
            'options_granted_during_period',
            'options_forfeited_during_period',
            'options_exercised_during_period',
            'options_expired_during_period',
            'options_cancelled_during_period',
            'number_of_options_outstanding_at_end',
            'options_exercisable_at_end',
            'weighted_average_exercise_price',
            'weighted_average_remaining_contractual_life',
            'range_of_exercise_prices',
            'weighted_average_share_price_at_exercise',
        ],
        'fair_value_determination': [
            'fair_value_of_options_granted',
            'valuation_model_used',
            'inputs_to_valuation_model',
            'expected_volatility',
            'expected_option_life',
            'expected_dividends',
            'risk_free_rate',
            'method_for_determining_volatility',
        ],
        'effect_on_financial_statements': [
            'total_expense_recognized',
            'expense_for_equity_settled',
            'expense_for_cash_settled',
            'carrying_amount_of_liability_for_cash_settled',
            'intrinsic_value_of_liability',
        ],
    },
}

# =============================================================================
# SECTION 44: GOVERNMENT GRANTS
# =============================================================================

GOVERNMENT_GRANTS = {
    'types_of_government_grants': {
        'grants_related_to_assets': [
            'grants_related_to_assets',
            'capital_grants',
            'grants_for_property_plant_equipment',
            'grants_for_intangible_assets',
            'grants_for_construction',
            'grants_for_capital_expenditure',
            'grants_for_investment_in_assets',
            'technology_upgradation_grants',
            'modernization_grants',
            'infrastructure_grants',
        ],
        'grants_related_to_income': [
            'grants_related_to_income',
            'revenue_grants',
            'operating_grants',
            'grants_for_operating_expenses',
            'grants_for_employment',
            'grants_for_training',
            'grants_for_research_and_development',
            'export_promotion_grants',
            'interest_subsidies',
            'freight_subsidies',
            'production_linked_incentives',
            'electricity_duty_exemption',
            'stamp_duty_exemption',
        ],
        'forgivable_loans': [
            'forgivable_loans',
            'soft_loans',
            'concessional_loans',
            'loans_with_below_market_interest',
            'benefit_of_below_market_rate',
            'government_loan_at_below_market_rate',
        ],
        'non_monetary_grants': [
            'non_monetary_government_grants',
            'land_at_concessional_rates',
            'free_land',
            'buildings_at_concessional_rates',
            'equipment_at_concessional_rates',
            'other_resources',
        ],
    },
    'recognition': {
        'recognition_criteria': [
            'reasonable_assurance_of_receipt',
            'reasonable_assurance_of_compliance_with_conditions',
            'entity_will_comply_with_conditions',
            'grant_will_be_received',
            'receipt_of_grant',
            'meeting_eligibility_criteria',
        ],
        'timing_of_recognition': [
            'recognition_when_conditions_met',
            'recognition_on_receipt',
            'recognition_over_period',
            'systematic_basis_consistent_with_costs',
        ],
    },
    'measurement': {
        'monetary_grants': [
            'amount_received',
            'amount_receivable',
            'fair_value_of_grant',
        ],
        'non_monetary_grants': [
            'fair_value_of_asset_received',
            'nominal_amount',
            'accounting_policy_choice',
        ],
        'forgivable_loans': [
            'present_value_of_loan',
            'market_rate_of_interest',
            'benefit_as_government_grant',
            'subsequent_measurement_of_loan',
        ],
    },
    'presentation': {
        'grants_related_to_assets': {
            'deferred_income_approach': [
                'deferred_income',
                'deferred_government_grant',
                'presented_as_liability',
                'recognized_in_profit_or_loss_over_useful_life',
                'amortization_of_deferred_grant',
            ],
            'deduction_from_asset_approach': [
                'deducted_from_carrying_amount_of_asset',
                'reduced_depreciation_expense',
                'net_amount_of_asset',
            ],
        },
        'grants_related_to_income': [
            'presented_as_other_income',
            'presented_as_separate_line_item',
            'deducted_from_related_expense',
            'gross_presentation',
            'net_presentation',
        ],
    },
    'specific_grants': {
        'export_incentives': [
            'duty_drawback',
            'meis',
            'merchandise_exports_from_india_scheme',
            'seis',
            'service_exports_from_india_scheme',
            'rodtep',
            'remission_of_duties_and_taxes_on_exported_products',
            'rosctl',
            'rebate_of_state_and_central_taxes_and_levies',
            'focus_product_scheme',
            'focus_market_scheme',
            'advance_authorization_scheme',
            'epcg_scheme',
        ],
        'production_linked_incentives': [
            'pli_scheme',
            'production_linked_incentive_scheme',
            'pli_for_manufacturing',
            'pli_for_electronics',
            'pli_for_pharmaceuticals',
            'pli_for_automobiles',
            'pli_for_textiles',
            'pli_for_solar',
            'recognition_of_pli_income',
            'conditions_for_pli',
        ],
        'special_economic_zones': [
            'sez_benefits',
            'income_tax_holiday',
            'duty_free_imports',
            'service_tax_exemption',
            'gst_exemption',
        ],
        'startup_incentives': [
            'startup_india_benefits',
            'angel_tax_exemption',
            'tax_holiday_for_startups',
            'section_80_iac',
        ],
        'industry_specific_grants': [
            'textile_upgradation_fund',
            'tuf_scheme',
            'technology_and_quality_upgradation_scheme',
            'interest_subvention_scheme',
            'capital_subsidy_scheme',
            'credit_linked_capital_subsidy',
            'clcss',
            'msme_subsidies',
        ],
    },
    'repayment_of_grants': [
        'repayment_of_government_grants',
        'change_in_estimate',
        'prospective_application',
        'reversal_of_deferred_income',
        'increase_in_carrying_amount_of_asset',
        'immediate_recognition_of_expense',
        'circumstances_requiring_repayment',
    ],
    'disclosures': {
        'accounting_policy': [
            'accounting_policy_for_government_grants',
            'presentation_method',
            'methods_of_presentation_in_financial_statements',
        ],
        'nature_and_extent': [
            'nature_of_grants',
            'extent_of_grants_recognized',
            'unfulfilled_conditions',
            'contingencies_attached',
            'other_forms_of_government_assistance',
        ],
        'grant_details': [
            'grants_received_during_period',
            'grants_recognized_in_profit_or_loss',
            'grants_recognized_in_balance_sheet',
            'deferred_income_balance',
            'grants_receivable',
            'conditions_to_be_fulfilled',
            'estimated_period_of_recognition',
        ],
    },
}
