
# =============================================================================
# SECTION 53: XBRL TAXONOMY IDENTIFIERS
# =============================================================================

XBRL_TAXONOMY_IDENTIFIERS = {
    'mca_taxonomy_elements': {
        'company_information': [
            'CINOfCompany',
            'NameOfCompany',
            'DateOfIncorporation',
            'CategoryOfCompany',
            'SubCategoryOfCompany',
            'ClassOfCompany',
            'AddressOfRegisteredOffice',
            'CityOfRegisteredOffice',
            'StateOfRegisteredOffice',
            'PINCodeOfRegisteredOffice',
            'CountryOfIncorporation',
            'EmailAddressOfCompany',
            'TelephoneNumberOfCompany',
            'WebsiteOfCompany',
            'DescriptionOfPrincipalBusinessActivity',
            'NICCodeOfProduct',
            'PercentageOfTurnoverOfProduct',
            'WhetherCompanyIsListedCompany',
            'NameOfStockExchange',
            'ScripCode',
            'ISINCode',
            'WhetherSharesAreDematerialised',
            'WhetherAnnualGeneralMeetingHeld',
            'DateOfAGM',
            'WhetherResultsAreProvisonalOrAudited',
            'NatureOfReportStandaloneConsolidated',
            'ContentOfReport',
            'ReportingQuarter',
            'DateOfStartOfReportingPeriod',
            'DateOfEndOfReportingPeriod',
            'DateOfBoardMeeting',
            'DateOfAuthorisation',
        ],
        'balance_sheet_assets': [
            'NonCurrentAssets',
            'PropertyPlantAndEquipment',
            'PropertyPlantAndEquipmentGross',
            'AccumulatedDepreciationPropertyPlantAndEquipment',
            'CapitalWorkInProgress',
            'InvestmentProperty',
            'GoodwillOnConsolidation',
            'OtherIntangibleAssets',
            'IntangibleAssetsUnderDevelopment',
            'BiologicalAssetsOtherThanBearerPlants',
            'RightOfUseAssets',
            'InvestmentsInSubsidiaries',
            'InvestmentsInAssociates',
            'InvestmentsInJointVentures',
            'NonCurrentFinancialAssetsInvestments',
            'NonCurrentFinancialAssetsTrade receivables',
            'NonCurrentFinancialAssetsLoans',
            'NonCurrentFinancialAssetsOthers',
            'DeferredTaxAssetsNet',
            'OtherNonCurrentAssets',
            'CurrentAssets',
            'Inventories',
            'CurrentFinancialAssetsInvestments',
            'CurrentFinancialAssetsTradeReceivables',
            'CurrentFinancialAssetsCashAndCashEquivalents',
            'CurrentFinancialAssetsBankBalancesOtherThanCashAndCashEquivalents',
            'CurrentFinancialAssetsLoans',
            'CurrentFinancialAssetsOthers',
            'CurrentTaxAssetsNet',
            'OtherCurrentAssets',
            'AssetsClassifiedAsHeldForSale',
            'TotalAssets',
        ],
        'balance_sheet_equity_liabilities': [
            'Equity',
            'EquityShareCapital',
            'OtherEquity',
            'EquityAttributableToOwnersOfParent',
            'NonControllingInterests',
            'TotalEquity',
            'NonCurrentLiabilities',
            'NonCurrentFinancialLiabilitiesBorrowings',
            'NonCurrentFinancialLiabilitiesTradePayables',
            'NonCurrentFinancialLiabilitiesLeases',
            'NonCurrentFinancialLiabilitiesOthers',
            'NonCurrentProvisions',
            'DeferredTaxLiabilitiesNet',
            'DeferredGovernmentGrantsAndOthers',
            'OtherNonCurrentLiabilities',
            'CurrentLiabilities',
            'CurrentFinancialLiabilitiesBorrowings',
            'CurrentFinancialLiabilitiesTradePayables',
            'CurrentFinancialLiabilitiesLeases',
            'CurrentFinancialLiabilitiesOthers',
            'OtherCurrentLiabilities',
            'CurrentProvisions',
            'CurrentTaxLiabilitiesNet',
            'LiabilitiesDirectlyAssociatedWithAssetsHeldForSale',
            'TotalEquityAndLiabilities',
        ],
        'profit_loss_statement': [
            'RevenueFromOperations',
            'OtherIncome',
            'TotalIncome',
            'CostOfMaterialsConsumed',
            'PurchasesOfStockInTrade',
            'ChangesInInventoriesOfFinishedGoodsWorkInProgressAndStockInTrade',
            'EmployeeBenefitExpense',
            'FinanceCosts',
            'DepreciationAndAmortisationExpense',
            'OtherExpenses',
            'TotalExpenses',
            'ProfitBeforeExceptionalItemsAndTax',
            'ExceptionalItems',
            'ProfitBeforeTax',
            'CurrentTax',
            'DeferredTax',
            'TaxExpense',
            'ProfitLossForPeriodFromContinuingOperations',
            'ProfitLossFromDiscontinuedOperations',
            'ProfitLossForPeriod',
            'OtherComprehensiveIncomeNetOfTaxes',
            'TotalComprehensiveIncomeForPeriod',
            'ProfitLossAttributableToOwnersOfParent',
            'ProfitLossAttributableToNonControllingInterests',
            'TotalComprehensiveIncomeAttributableToOwnersOfParent',
            'TotalComprehensiveIncomeAttributableToNonControllingInterests',
            'EarningsPerEquityShareBasic',
            'EarningsPerEquityShareDiluted',
        ],
        'cash_flow_statement': [
            'CashFlowsFromOperatingActivities',
            'ProfitBeforeTaxCashFlow',
            'AdjustmentsForReconcileProfitLoss',
            'AdjustmentsForDepreciationAndAmortisationExpense',
            'AdjustmentsForFinanceCosts',
            'AdjustmentsForInterestIncome',
            'AdjustmentsForDividendIncome',
            'AdjustmentsForGainLossOnDisposalOfAssets',
            'AdjustmentsForProvisions',
            'AdjustmentsForUnrealisedForeignExchangeGainsLosses',
            'OperatingProfitBeforeWorkingCapitalChanges',
            'ChangesInWorkingCapital',
            'ChangesInTradeReceivables',
            'ChangesInInventories',
            'ChangesInTradePayables',
            'ChangesInOtherCurrentAssets',
            'ChangesInOtherCurrentLiabilities',
            'CashGeneratedFromOperations',
            'IncomeTaxesPaid',
            'NetCashFromOperatingActivities',
            'CashFlowsFromInvestingActivities',
            'PaymentsForPropertyPlantAndEquipment',
            'ProceedsFromDisposalOfPropertyPlantAndEquipment',
            'PaymentsForIntangibleAssets',
            'ProceedsFromDisposalOfIntangibleAssets',
            'PaymentsForPurchaseOfInvestments',
            'ProceedsFromSaleOfInvestments',
            'InterestReceived',
            'DividendReceived',
            'NetCashFromInvestingActivities',
            'CashFlowsFromFinancingActivities',
            'ProceedsFromIssuanceOfEquity',
            'PaymentsForRepurchaseOfEquity',
            'ProceedsFromBorrowings',
            'RepaymentsOfBorrowings',
            'PaymentsOfLeaseLiabilities',
            'InterestPaid',
            'DividendsPaid',
            'NetCashFromFinancingActivities',
            'NetIncreaseDecreaseInCashAndCashEquivalents',
            'CashAndCashEquivalentsAtBeginningOfPeriod',
            'EffectOfExchangeRateChangesOnCashAndCashEquivalents',
            'CashAndCashEquivalentsAtEndOfPeriod',
        ],
        'statement_of_changes_in_equity': [
            'EquityShareCapitalChanges',
            'ChangesInEquityShareCapitalDuringPeriod',
            'OtherEquityChanges',
            'BalanceAtBeginningOfPeriod',
            'ChangesInAccountingPolicy',
            'RestatedBalanceAtBeginningOfPeriod',
            'ProfitForPeriod',
            'OtherComprehensiveIncome',
            'TotalComprehensiveIncome',
            'TransferToReserves',
            'DividendsRecognisedAsDistributions',
            'TransactionsWithOwners',
            'IssueOfEquityShares',
            'ShareBasedPayments',
            'BuybackOfShares',
            'BalanceAtEndOfPeriod',
        ],
    },
    'disclosure_elements': {
        'notes_to_accounts': [
            'SignificantAccountingPolicies',
            'PropertyPlantEquipmentDisclosure',
            'CapitalWorkInProgressAgeing',
            'IntangibleAssetsDisclosure',
            'IntangibleAssetsUnderDevelopmentAgeing',
            'InvestmentPropertyDisclosure',
            'InvestmentsDisclosure',
            'LoansDisclosure',
            'TradeReceivablesAgeing',
            'TradePayablesAgeing',
            'BorrowingsDisclosure',
            'ProvisionsDisclosure',
            'InventoriesDisclosure',
            'CashAndCashEquivalentsDisclosure',
            'OtherEquityDisclosure',
            'ContingentLiabilitiesDisclosure',
            'CommitmentsDisclosure',
            'RelatedPartyTransactionsDisclosure',
            'SegmentReportingDisclosure',
            'FinancialInstrumentsDisclosure',
            'FairValueMeasurementDisclosure',
            'LeasesDisclosure',
            'RevenueFromContractsDisclosure',
            'EmployeeBenefitsDisclosure',
            'ShareBasedPaymentsDisclosure',
            'IncomeTaxDisclosure',
            'DeferredTaxDisclosure',
            'EarningsPerShareDisclosure',
            'EventsAfterReportingPeriodDisclosure',
            'GoingConcernDisclosure',
        ],
        'ratios_and_metrics': [
            'CurrentRatio',
            'DebtEquityRatio',
            'DebtServiceCoverageRatio',
            'ReturnOnEquity',
            'InventoryTurnoverRatio',
            'TradeReceivablesTurnoverRatio',
            'TradePayablesTurnoverRatio',
            'NetCapitalTurnoverRatio',
            'NetProfitRatio',
            'ReturnOnCapitalEmployed',
            'ReturnOnInvestment',
        ],
        'additional_disclosures': [
            'CSRExpenditureDisclosure',
            'DetailsOfBenami',
            'WilfulDefaulter',
            'RelationshipWithStruckOffCompanies',
            'RegistrationOfCharges',
            'ComplianceWithApprovedSchemeOfArrangements',
            'DiscrepancyInUtilizationOfBorrowings',
            'UndisclosedIncome',
            'CryptoAssets',
            'SchemesOfArrangements',
        ],
    },
    'dimensional_elements': {
        'segment_dimension': [
            'SegmentAxis',
            'OperatingSegmentsMember',
            'GeographicalAreasMember',
            'MajorCustomersMember',
            'AllOtherSegmentsMember',
            'EliminationsMember',
            'UnallocatedMember',
        ],
        'related_party_dimension': [
            'RelatedPartyAxis',
            'ParentMember',
            'SubsidiariesMember',
            'AssociatesMember',
            'JointVenturesMember',
            'KeyManagementPersonnelMember',
            'OtherRelatedPartiesMember',
        ],
        'financial_instruments_dimension': [
            'FinancialInstrumentsAxis',
            'AtAmortisedCostMember',
            'AtFVTPLMember',
            'AtFVOCIMember',
            'HedgingInstrumentsMember',
        ],
        'fair_value_dimension': [
            'FairValueHierarchyAxis',
            'Level1Member',
            'Level2Member',
            'Level3Member',
        ],
        'maturity_dimension': [
            'MaturityAxis',
            'NotLaterThanOneYearMember',
            'LaterThanOneYearNotLaterThanFiveYearsMember',
            'LaterThanFiveYearsMember',
        ],
        'currency_dimension': [
            'CurrencyAxis',
            'INRMember',
            'USDMember',
            'EURMember',
            'GBPMember',
            'OtherCurrenciesMember',
        ],
        'ageing_dimension': [
            'AgeingAxis',
            'OutstandingForFollowingPeriodsFromDueDateMember',
            'LessThanSixMonthsMember',
            'SixMonthsToOneYearMember',
            'OneToTwoYearsMember',
            'TwoToThreeYearsMember',
            'MoreThanThreeYearsMember',
            'DisputedMember',
            'UndisputedMember',
        ],
    },
    'technical_elements': {
        'context_elements': [
            'EntityIdentifier',
            'EntityScheme',
            'PeriodType',
            'InstantDate',
            'StartDate',
            'EndDate',
            'Scenario',
            'Segment',
        ],
        'unit_elements': [
            'UnitID',
            'Measure',
            'INR',
            'Shares',
            'PerShare',
            'Percentage',
            'Pure',
            'Days',
            'Years',
        ],
        'filing_elements': [
            'DocumentType',
            'DocumentPeriod',
            'FilingDate',
            'AuditedOrUnaudited',
            'ConsolidatedOrStandalone',
            'FormType',
            'AOC4',
            'AOC4XBRL',
            'AOC4CFS',
            'AOC4CFSXBRL',
        ],
    },
}

# =============================================================================
# SECTION 54: KEY FINANCIAL RATIOS (SCHEDULE III DIV II)
# =============================================================================

KEY_FINANCIAL_RATIOS = {
    'liquidity_ratios': {
        'current_ratio': {
            'formula': [
                'current_ratio',
                'current_assets_divided_by_current_liabilities',
                'current_assets',
                'current_liabilities',
                'working_capital_ratio',
            ],
            'components': [
                'total_current_assets',
                'inventories',
                'trade_receivables',
                'cash_and_cash_equivalents',
                'other_current_assets',
                'total_current_liabilities',
                'short_term_borrowings',
                'trade_payables',
                'other_current_liabilities',
                'current_provisions',
            ],
            'interpretation': [
                'ability_to_pay_short_term_obligations',
                'short_term_liquidity',
                'working_capital_adequacy',
                'ideal_ratio_above_1',
            ],
        },
        'quick_ratio': {
            'formula': [
                'quick_ratio',
                'acid_test_ratio',
                'current_assets_minus_inventories_divided_by_current_liabilities',
                'quick_assets',
                'liquid_assets',
            ],
            'components': [
                'current_assets',
                'less_inventories',
                'less_prepaid_expenses',
                'current_liabilities',
            ],
            'interpretation': [
                'immediate_liquidity',
                'ability_to_meet_obligations_without_selling_inventory',
                'more_stringent_than_current_ratio',
            ],
        },
        'cash_ratio': {
            'formula': [
                'cash_ratio',
                'cash_and_cash_equivalents_divided_by_current_liabilities',
                'absolute_liquidity_ratio',
            ],
            'components': [
                'cash_and_cash_equivalents',
                'marketable_securities',
                'current_liabilities',
            ],
            'interpretation': [
                'ability_to_pay_with_cash_and_near_cash',
                'most_conservative_liquidity_ratio',
            ],
        },
    },
    'solvency_ratios': {
        'debt_equity_ratio': {
            'formula': [
                'debt_equity_ratio',
                'total_debt_divided_by_shareholders_equity',
                'debt_to_equity',
                'leverage_ratio',
                'gearing_ratio',
            ],
            'components': {
                'numerator': [
                    'total_debt',
                    'long_term_borrowings',
                    'short_term_borrowings',
                    'current_maturities_of_long_term_debt',
                    'lease_liabilities',
                    'deferred_payment_liabilities',
                ],
                'denominator': [
                    'shareholders_equity',
                    'share_capital',
                    'reserves_and_surplus',
                    'other_equity',
                    'total_equity',
                ],
            },
            'interpretation': [
                'financial_leverage',
                'capital_structure',
                'risk_from_debt',
                'lower_ratio_indicates_lower_risk',
            ],
        },
        'debt_service_coverage_ratio': {
            'formula': [
                'debt_service_coverage_ratio',
                'dscr',
                'earnings_available_for_debt_service_divided_by_debt_service',
                'net_operating_income_divided_by_total_debt_service',
            ],
            'components': {
                'numerator': [
                    'earnings_available_for_debt_service',
                    'profit_after_tax',
                    'add_depreciation',
                    'add_interest_on_term_loans',
                    'add_lease_payments',
                    'add_other_non_cash_expenses',
                    'net_profit_before_interest_and_depreciation',
                ],
                'denominator': [
                    'debt_service',
                    'interest_on_term_loans',
                    'principal_repayment_of_term_loans',
                    'lease_payments',
                    'total_debt_service_obligations',
                ],
            },
            'interpretation': [
                'ability_to_service_debt',
                'debt_repayment_capacity',
                'ratio_above_1_indicates_sufficient_earnings',
                'higher_ratio_indicates_better_coverage',
            ],
        },
        'interest_coverage_ratio': {
            'formula': [
                'interest_coverage_ratio',
                'interest_service_coverage_ratio',
                'times_interest_earned',
                'ebit_divided_by_interest_expense',
            ],
            'components': {
                'numerator': [
                    'ebit',
                    'earnings_before_interest_and_tax',
                    'profit_before_interest_and_tax',
                    'operating_profit',
                ],
                'denominator': [
                    'interest_expense',
                    'finance_costs',
                    'interest_on_borrowings',
                ],
            },
            'interpretation': [
                'ability_to_pay_interest',
                'interest_payment_capacity',
                'higher_ratio_indicates_better_coverage',
            ],
        },
    },
    'profitability_ratios': {
        'return_on_equity': {
            'formula': [
                'return_on_equity',
                'roe',
                'net_profit_divided_by_average_shareholders_equity',
                'return_on_net_worth',
                'ronw',
            ],
            'components': {
                'numerator': [
                    'net_profit_after_tax',
                    'profit_attributable_to_owners',
                    'profit_for_the_year',
                ],
                'denominator': [
                    'average_shareholders_equity',
                    'opening_equity_plus_closing_equity_divided_by_2',
                    'average_net_worth',
                ],
            },
            'interpretation': [
                'return_generated_on_shareholders_investment',
                'profitability_for_shareholders',
                'efficiency_of_equity_utilization',
            ],
        },
        'return_on_capital_employed': {
            'formula': [
                'return_on_capital_employed',
                'roce',
                'ebit_divided_by_capital_employed',
                'return_on_invested_capital',
            ],
            'components': {
                'numerator': [
                    'ebit',
                    'earnings_before_interest_and_tax',
                    'profit_before_interest_and_tax',
                ],
                'denominator': [
                    'capital_employed',
                    'total_assets_minus_current_liabilities',
                    'equity_plus_long_term_debt',
                    'net_worth_plus_long_term_borrowings',
                    'average_capital_employed',
                ],
            },
            'interpretation': [
                'efficiency_of_capital_utilization',
                'return_on_total_capital',
                'operating_efficiency',
            ],
        },
        'return_on_investment': {
            'formula': [
                'return_on_investment',
                'roi',
                'return_on_assets',
                'roa',
                'net_profit_divided_by_average_total_assets',
            ],
            'components': {
                'numerator': [
                    'net_profit_after_tax',
                    'profit_for_the_year',
                ],
                'denominator': [
                    'average_total_assets',
                    'opening_assets_plus_closing_assets_divided_by_2',
                ],
            },
            'interpretation': [
                'efficiency_of_asset_utilization',
                'overall_profitability',
                'return_generated_on_assets',
            ],
        },
        'net_profit_ratio': {
            'formula': [
                'net_profit_ratio',
                'net_profit_margin',
                'net_profit_divided_by_revenue',
                'profit_margin',
            ],
            'components': {
                'numerator': [
                    'net_profit_after_tax',
                    'profit_for_the_year',
                ],
                'denominator': [
                    'revenue_from_operations',
                    'net_sales',
                    'total_revenue',
                ],
            },
            'interpretation': [
                'profitability_on_sales',
                'profit_earned_per_rupee_of_sales',
                'overall_efficiency',
            ],
        },
        'operating_profit_margin': {
            'formula': [
                'operating_profit_margin',
                'operating_margin',
                'ebit_margin',
                'operating_profit_divided_by_revenue',
            ],
            'components': {
                'numerator': [
                    'operating_profit',
                    'ebit',
                    'profit_before_interest_and_tax',
                ],
                'denominator': [
                    'revenue_from_operations',
                    'net_sales',
                ],
            },
            'interpretation': [
                'operating_efficiency',
                'core_business_profitability',
            ],
        },
        'ebitda_margin': {
            'formula': [
                'ebitda_margin',
                'ebitda_divided_by_revenue',
                'operating_cash_margin',
            ],
            'components': {
                'numerator': [
                    'ebitda',
                    'earnings_before_interest_tax_depreciation_amortization',
                    'operating_profit_plus_depreciation',
                ],
                'denominator': [
                    'revenue_from_operations',
                    'net_sales',
                ],
            },
            'interpretation': [
                'cash_generating_efficiency',
                'operating_performance_before_non_cash_items',
            ],
        },
    },
    'efficiency_ratios': {
        'inventory_turnover_ratio': {
            'formula': [
                'inventory_turnover_ratio',
                'stock_turnover_ratio',
                'cost_of_goods_sold_divided_by_average_inventory',
            ],
            'components': {
                'numerator': [
                    'cost_of_goods_sold',
                    'cost_of_materials_consumed',
                    'purchases',
                    'manufacturing_expenses',
                ],
                'denominator': [
                    'average_inventory',
                    'opening_inventory_plus_closing_inventory_divided_by_2',
                ],
            },
            'interpretation': [
                'efficiency_of_inventory_management',
                'times_inventory_sold_and_replaced',
                'higher_ratio_indicates_better_efficiency',
            ],
            'related_metrics': [
                'inventory_days',
                'days_inventory_outstanding',
                '365_divided_by_inventory_turnover',
            ],
        },
        'trade_receivables_turnover_ratio': {
            'formula': [
                'trade_receivables_turnover_ratio',
                'debtors_turnover_ratio',
                'net_credit_sales_divided_by_average_trade_receivables',
            ],
            'components': {
                'numerator': [
                    'net_credit_sales',
                    'revenue_from_operations',
                ],
                'denominator': [
                    'average_trade_receivables',
                    'opening_receivables_plus_closing_receivables_divided_by_2',
                ],
            },
            'interpretation': [
                'efficiency_of_receivables_collection',
                'times_receivables_collected',
                'credit_management_efficiency',
            ],
            'related_metrics': [
                'receivables_days',
                'days_sales_outstanding',
                'dso',
                'average_collection_period',
                '365_divided_by_receivables_turnover',
            ],
        },
        'trade_payables_turnover_ratio': {
            'formula': [
                'trade_payables_turnover_ratio',
                'creditors_turnover_ratio',
                'net_credit_purchases_divided_by_average_trade_payables',
            ],
            'components': {
                'numerator': [
                    'net_credit_purchases',
                    'purchases',
                    'cost_of_materials_consumed',
                ],
                'denominator': [
                    'average_trade_payables',
                    'opening_payables_plus_closing_payables_divided_by_2',
                ],
            },
            'interpretation': [
                'payment_efficiency',
                'times_payables_paid',
                'supplier_payment_management',
            ],
            'related_metrics': [
                'payables_days',
                'days_payables_outstanding',
                'dpo',
                'average_payment_period',
                '365_divided_by_payables_turnover',
            ],
        },
        'net_capital_turnover_ratio': {
            'formula': [
                'net_capital_turnover_ratio',
                'working_capital_turnover_ratio',
                'revenue_divided_by_working_capital',
                'net_sales_divided_by_net_working_capital',
            ],
            'components': {
                'numerator': [
                    'revenue_from_operations',
                    'net_sales',
                ],
                'denominator': [
                    'working_capital',
                    'net_working_capital',
                    'current_assets_minus_current_liabilities',
                ],
            },
            'interpretation': [
                'efficiency_of_working_capital_utilization',
                'sales_generated_per_rupee_of_working_capital',
            ],
        },
        'asset_turnover_ratio': {
            'formula': [
                'asset_turnover_ratio',
                'total_asset_turnover',
                'revenue_divided_by_average_total_assets',
            ],
            'components': {
                'numerator': [
                    'revenue_from_operations',
                    'net_sales',
                ],
                'denominator': [
                    'average_total_assets',
                ],
            },
            'interpretation': [
                'efficiency_of_asset_utilization',
                'sales_generated_per_rupee_of_assets',
            ],
        },
        'fixed_asset_turnover_ratio': {
            'formula': [
                'fixed_asset_turnover_ratio',
                'revenue_divided_by_average_fixed_assets',
                'revenue_divided_by_average_ppe',
            ],
            'components': {
                'numerator': [
                    'revenue_from_operations',
                    'net_sales',
                ],
                'denominator': [
                    'average_fixed_assets',
                    'average_property_plant_equipment',
                    'average_net_block',
                ],
            },
            'interpretation': [
                'efficiency_of_fixed_asset_utilization',
                'productivity_of_fixed_assets',
            ],
        },
    },
    'valuation_ratios': {
        'earnings_per_share': {
            'formula': [
                'earnings_per_share',
                'eps',
                'net_profit_divided_by_weighted_average_shares',
            ],
            'components': {
                'basic_eps': [
                    'profit_attributable_to_equity_shareholders',
                    'weighted_average_number_of_shares',
                ],
                'diluted_eps': [
                    'adjusted_profit',
                    'weighted_average_diluted_shares',
                ],
            },
        },
        'price_earnings_ratio': {
            'formula': [
                'price_earnings_ratio',
                'pe_ratio',
                'market_price_per_share_divided_by_eps',
            ],
            'components': {
                'numerator': [
                    'market_price_per_share',
                    'closing_share_price',
                ],
                'denominator': [
                    'earnings_per_share',
                    'eps',
                ],
            },
        },
        'book_value_per_share': {
            'formula': [
                'book_value_per_share',
                'net_worth_per_share',
                'shareholders_equity_divided_by_number_of_shares',
            ],
            'components': {
                'numerator': [
                    'shareholders_equity',
                    'net_worth',
                ],
                'denominator': [
                    'number_of_equity_shares',
                ],
            },
        },
        'price_to_book_ratio': {
            'formula': [
                'price_to_book_ratio',
                'pb_ratio',
                'market_price_divided_by_book_value',
            ],
        },
        'dividend_payout_ratio': {
            'formula': [
                'dividend_payout_ratio',
                'dividends_divided_by_net_profit',
            ],
            'components': {
                'numerator': [
                    'dividends_paid',
                    'total_dividend',
                ],
                'denominator': [
                    'net_profit_after_tax',
                ],
            },
        },
        'dividend_yield': {
            'formula': [
                'dividend_yield',
                'dividend_per_share_divided_by_market_price',
            ],
        },
    },
    'ratio_disclosures': {
        'schedule_iii_requirements': [
            'ratio_for_current_year',
            'ratio_for_previous_year',
            'variance_percentage',
            'reason_for_variance_exceeding_25_percent',
            'explanation_for_significant_change',
        ],
        'presentation_format': [
            'numerator_description',
            'denominator_description',
            'ratio_value',
            'variance_analysis',
        ],
    },
}

# =============================================================================
# SECTION 55: GENERAL INFORMATION AND ACCOUNTING POLICIES
# =============================================================================

GENERAL_INFORMATION_AND_ACCOUNTING_POLICIES = {
    'corporate_information': {
        'company_details': [
            'name_of_company',
            'corporate_identity_number',
            'cin',
            'date_of_incorporation',
            'country_of_incorporation',
            'registered_office_address',
            'corporate_office_address',
            'nature_of_business',
            'principal_activities',
            'products_and_services',
            'industry_classification',
            'nic_code',
            'stock_exchange_listing',
            'parent_company',
            'ultimate_holding_company',
            'group_structure',
        ],
        'authorization_of_financial_statements': [
            'date_of_authorization',
            'authorized_by_board_of_directors',
            'date_of_board_meeting',
            'power_to_amend',
        ],
    },
    'basis_of_preparation': {
        'compliance_statement': [
            'compliance_with_ind_as',
            'compliance_with_companies_act_2013',
            'compliance_with_schedule_iii',
            'compliance_with_sebi_regulations',
            'compliance_with_other_regulations',
            'true_and_fair_view',
        ],
        'basis_of_measurement': [
            'historical_cost_basis',
            'fair_value_basis',
            'amortized_cost',
            'net_realizable_value',
            'present_value',
            'current_cost',
            'mixed_measurement_model',
        ],
        'functional_and_presentation_currency': [
            'functional_currency',
            'presentation_currency',
            'indian_rupees',
            'rounding_off',
            'amounts_in_lakhs',
            'amounts_in_crores',
            'amounts_in_millions',
        ],
        'use_of_estimates_and_judgments': [
            'use_of_estimates',
            'use_of_judgments',
            'critical_accounting_estimates',
            'key_sources_of_estimation_uncertainty',
            'significant_judgments',
            'management_assumptions',
            'inherent_uncertainty',
            'sensitivity_to_assumptions',
        ],
    },
    'significant_accounting_policies': {
        'revenue_recognition': [
            'revenue_recognition_policy',
            'revenue_from_contracts_with_customers',
            'identification_of_performance_obligations',
            'transaction_price_determination',
            'allocation_of_transaction_price',
            'recognition_over_time',
            'recognition_at_point_in_time',
            'variable_consideration',
            'significant_financing_component',
            'contract_modifications',
            'contract_costs',
            'principal_vs_agent',
            'bill_and_hold_arrangements',
            'consignment_arrangements',
            'right_of_return',
            'warranties',
            'licensing_arrangements',
        ],
        'property_plant_equipment': [
            'ppe_recognition',
            'initial_measurement',
            'subsequent_measurement',
            'cost_model',
            'revaluation_model',
            'depreciation_method',
            'straight_line_method',
            'written_down_value_method',
            'units_of_production_method',
            'useful_lives',
            'residual_value',
            'componentization',
            'major_inspection_costs',
            'decommissioning_costs',
            'borrowing_costs_capitalization',
            'capital_work_in_progress',
            'impairment',
            'derecognition',
        ],
        'intangible_assets': [
            'intangible_assets_recognition',
            'acquired_intangible_assets',
            'internally_generated_intangible_assets',
            'research_expenditure',
            'development_expenditure',
            'amortization_method',
            'useful_life_assessment',
            'finite_useful_life',
            'indefinite_useful_life',
            'impairment_testing',
        ],
        'investment_property': [
            'investment_property_recognition',
            'cost_model',
            'fair_value_model',
            'transfers_to_from_investment_property',
            'depreciation',
        ],
        'impairment_of_non_financial_assets': [
            'impairment_policy',
            'indicators_of_impairment',
            'cash_generating_units',
            'recoverable_amount',
            'value_in_use',
            'fair_value_less_costs_of_disposal',
            'goodwill_impairment',
            'reversal_of_impairment',
        ],
        'leases': [
            'lease_policy',
            'identification_of_lease',
            'right_of_use_assets',
            'lease_liabilities',
            'short_term_lease_exemption',
            'low_value_asset_exemption',
            'lease_term_determination',
            'discount_rate',
            'incremental_borrowing_rate',
            'subsequent_measurement',
            'lease_modifications',
            'sale_and_leaseback',
        ],
        'financial_instruments': [
            'financial_instruments_policy',
            'classification_and_measurement',
            'financial_assets_at_amortized_cost',
            'financial_assets_at_fvoci',
            'financial_assets_at_fvtpl',
            'financial_liabilities_measurement',
            'derecognition',
            'impairment_of_financial_assets',
            'expected_credit_loss',
            'simplified_approach',
            'general_approach',
            'provision_matrix',
            'hedge_accounting',
            'fair_value_hedges',
            'cash_flow_hedges',
            'net_investment_hedges',
            'embedded_derivatives',
            'offsetting',
        ],
        'inventories': [
            'inventories_policy',
            'cost_determination',
            'fifo',
            'weighted_average',
            'specific_identification',
            'net_realizable_value',
            'cost_components',
            'allocation_of_overheads',
            'write_down_to_nrv',
        ],
        'employee_benefits': [
            'employee_benefits_policy',
            'short_term_benefits',
            'post_employment_benefits',
            'defined_contribution_plans',
            'defined_benefit_plans',
            'actuarial_valuation',
            'projected_unit_credit_method',
            'remeasurements_in_oci',
            'long_term_employee_benefits',
            'termination_benefits',
            'share_based_payments',
        ],
        'provisions_and_contingencies': [
            'provisions_policy',
            'recognition_criteria',
            'measurement_of_provisions',
            'best_estimate',
            'risks_and_uncertainties',
            'present_value',
            'contingent_liabilities',
            'contingent_assets',
        ],
        'income_taxes': [
            'income_tax_policy',
            'current_tax',
            'deferred_tax',
            'temporary_differences',
            'unused_tax_losses',
            'unused_tax_credits',
            'recognition_of_deferred_tax_assets',
            'measurement_at_enacted_rates',
            'presentation',
            'uncertain_tax_positions',
        ],
        'foreign_currency': [
            'foreign_currency_policy',
            'functional_currency_determination',
            'initial_recognition',
            'subsequent_measurement',
            'monetary_items',
            'non_monetary_items',
            'exchange_differences',
            'translation_of_foreign_operations',
        ],
        'borrowing_costs': [
            'borrowing_costs_policy',
            'capitalization',
            'qualifying_assets',
            'capitalization_rate',
            'commencement_of_capitalization',
            'suspension_of_capitalization',
            'cessation_of_capitalization',
        ],
        'government_grants': [
            'government_grants_policy',
            'recognition',
            'grants_related_to_assets',
            'grants_related_to_income',
            'presentation',
            'repayment_of_grants',
        ],
        'fair_value_measurement': [
            'fair_value_policy',
            'fair_value_hierarchy',
            'level_1_inputs',
            'level_2_inputs',
            'level_3_inputs',
            'valuation_techniques',
            'transfers_between_levels',
        ],
        'segment_reporting': [
            'segment_reporting_policy',
            'operating_segments',
            'chief_operating_decision_maker',
            'segment_identification',
            'segment_measurement',
        ],
        'earnings_per_share': [
            'eps_policy',
            'basic_eps',
            'diluted_eps',
            'weighted_average_shares',
            'potential_equity_shares',
        ],
        'cash_flow_statement': [
            'cash_flow_policy',
            'indirect_method',
            'direct_method',
            'cash_and_cash_equivalents_definition',
            'bank_overdrafts_treatment',
        ],
    },
    'changes_in_accounting_policies': [
        'changes_in_accounting_policies',
        'new_standards_adopted',
        'amendments_adopted',
        'early_adoption',
        'retrospective_application',
        'prospective_application',
        'transition_provisions',
        'impact_of_changes',
        'standards_issued_but_not_effective',
        'expected_impact_of_new_standards',
    ],
    'critical_estimates_and_judgments': {
        'areas_of_significant_judgment': [
            'revenue_recognition_judgments',
            'lease_term_determination',
            'control_assessment',
            'principal_vs_agent_determination',
            'identification_of_performance_obligations',
            'going_concern_assessment',
            'impairment_indicators',
            'provisions_recognition',
            'contingencies_assessment',
            'tax_positions',
            'business_model_assessment',
            'significant_increase_in_credit_risk',
            'functional_currency_determination',
        ],
        'areas_of_significant_estimation': [
            'useful_lives_of_assets',
            'residual_values',
            'fair_value_measurements',
            'impairment_of_goodwill',
            'impairment_of_assets',
            'expected_credit_losses',
            'provisions_estimation',
            'defined_benefit_obligations',
            'actuarial_assumptions',
            'share_based_payment_valuation',
            'contingent_consideration',
            'deferred_tax_assets_recoverability',
            'percentage_of_completion',
            'warranty_provisions',
            'legal_provisions',
            'inventory_obsolescence',
        ],
    },
    'presentation_and_disclosure': {
        'materiality': [
            'materiality_concept',
            'materiality_for_financial_statements',
            'materiality_for_notes',
            'aggregation_and_disaggregation',
        ],
        'comparative_information': [
            'comparative_information',
            'prior_period_comparatives',
            'reclassification_of_comparatives',
            'reason_for_reclassification',
        ],
        'offsetting': [
            'offsetting_policy',
            'assets_and_liabilities_offsetting',
            'income_and_expenses_offsetting',
        ],
    },
}
